.github/workflows/pypi_release.yml
Workflow will be triggered whenever a tag formatted like `<project_path>-v<project_version>` is pushed.
To publish the `text2speech` extra version `1.0.0` one would need to push a `nodes/text2speech-v1.0.0` tag.
=> Add generic workflow to publish projects

nodes/text2speech/pyproject.toml
Fixes failing tests for `text2speech` package.
Related failure: https://github.com/deepset-ai/haystack-extras/actions/runs/4424729918/jobs/7758905520
More info in deepset-ai/haystack#4418.
=> Fix text2speech dependencies

nodes/text2speech/pyproject.toml
I found an issue related to a specific dependency, pyworld in the text2speech module. The project specifically requires pyworld version <= 0.2.12.
However, when attempting to install the library with the specified version using the command ```pip install pyworld<=0.2.12``` (or by default ```pip install farm-haystack-text2speech```), the installation process fails by deprecation with the following error:
```powershell
PS C:\Users\path pip install pyworld<=0.2.12
Collecting pyworld<=0.2.12
Using cached pyworld-0.2.12.tar.gz (222 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Installing backend dependencies ... done
Preparing metadata (pyproject.toml) ... error
error: subprocess-exited-with-error
× Preparing metadata (pyproject.toml) did not run …
```
=> Fixed pyworld dependency version for text2speech module

.github/workflows/components_instructor_embedders, components/README.md, components/hatch.toml, components/instructor-embedders/LICENSE.txt, components/instructor-embedders/README.md, components/instructor-embedders/instructor_embedders/__about__.py, components/instructor-embedders/instructor_embedders/__init__.py, components/instructor-embedders/pyproject.toml, components/instructor-embedders/tests/__init__.py
As discussed offline, for dependency reasons,
we would like to include the Instructor Embedders (for Haystack 2.x) in a sub-project of haystack-extras.
I set up and created the bare minimum to help the contributor move his PR to this repository.
=> Add instructor-embedders empty sub-project

components/instructor-embedders/instructor_embedders/__init__.py, components/instructor-embedders/pyproject.toml
The pinned version of `pyarrow` can't install on OSX. Removing the pin still works, not sure if we want to test the package in other environments to confirm.
Also exported the embedders in the root package for convenience.
=> [instructor] Fix osx install

components/instructor-embedders/instructor_embedders/instructor_document_embedder.py
Part of https://github.com/deepset-ai/haystack/issues/6107
Enrich documents with embeddings instead of recreating documents for `InstructorDocumentEmbedder`.
The Document class is not frozen anymore, so we can add the embedding to the document without recreating it.
@anakin87
=> `InstructorDocumentEmbedder`: Enrich documents with embeddings instead of recreating documents

components/instructor-embedders/instructor_embedders/instructor_document_embedder.py, components/instructor-embedders/instructor_embedders/instructor_text_embedder.py, components/instructor-embedders/tests/test_instructor_backend.py, components/instructor-embedders/tests/test_instructor_document_embedder.py, components/instructor-embedders/tests/test_instructor_text_embedder.py
- Updates the Document class usage in INSTRUCTOR Embedders:
`Document.text` --> `Document.content`
`Document.metadata` --> `Document.meta`
- Adds a simple usage example in the class docstrings for `InstructorDocumentEmbedder` and `InstructorTextEmbedder`.
=> refactor: Update `INSTRUCTOR Embedders` to work with new `Document` class

components/instructor-embedders/instructor_embedders/__about__.py
I'm bumping the version,
so that I can release v0.0.2 with the recent refactoring (#44).
=> bump Instructor Embedders version

document_stores/elasticsearch/src/elasticsearch_haystack/bm25_retriever.py, document_stores/elasticsearch/src/elasticsearch_haystack/document_store.py, document_stores/elasticsearch/tests/test_bm25_retriever.py, document_stores/elasticsearch/tests/test_document_store.py
I added this as a community member in one of the latest office hours told me how annoying it was to use fuzziness in Haystack 1.x. In the end he had to create his own Document Store to support it.
I belive it's good to show how much more flexible Haystack 2.x will be so I decided to add this as it took few minutes.
=> Add fuzziness support in Elasticsearch bm25 retrieval

document_stores/elasticsearch/src/elasticsearch_haystack/bm25_retriever.py, document_stores/elasticsearch/src/elasticsearch_haystack/document_store.py, document_stores/elasticsearch/tests/test_bm25_retriever.py, document_stores/elasticsearch/tests/test_document_store.py
Related to https://github.com/deepset-ai/haystack/issues/6271
(I also fixed a test that used `text` instead of `content` in Document initialization).
=> Elastiscsearch BM25Retriever: set `scale_score` default value to False

document_stores/elasticsearch/docker-compose.yml, document_stores/elasticsearch/src/elasticsearch_haystack/bm25_retriever.py, document_stores/elasticsearch/src/elasticsearch_haystack/document_store.py, document_stores/elasticsearch/tests/test_bm25_retriever.py, document_stores/elasticsearch/tests/test_document_store.py
Part of  https://github.com/deepset-ai/haystack/issues/5329
- Add basic support for Embedding retrieval in Elasticsearch Document Store
- `ElasticSearchEmbeddingRetriever` will be added in a subsequent PR.
- I chose to support only [Approximate kNN](https://www.elastic.co/guide/en/elasticsearch/reference/8.11/knn-search.html#knn-methods), which is the suggested approach compared to Exact, brute-force kNN.
- This Document Store is compatible with Elasticsearch>=8.11
Configuring vector fields in older versions required more manual effort on the part of the user (e.g., explicitly specifying the vector size at index creation).
- I haven't implemented scaling scores in the range [0, 1]. See #53 
- I would like to test also other unhappy paths, such as trying to write documents with embeddings …
=> Elasticsearch Document store - embedding retrieval

document_stores/elasticsearch/pyproject.toml
We decided to temporarily pin to avoid breaking changes while working on Elastic.
@silvanocerza will remove this pin when the Document/filters refactoring is finished.
=> Elasticsearch DS: temporarily pin `haystack-ai`

document_stores/elasticsearch/src/elasticsearch_haystack/document_store.py, document_stores/elasticsearch/tests/test_document_store.py
Fixes #58
We now distinguish the errors into `DuplicateDocumentError` and generic `DocumentStoreError`.
The `DuplicateDocumentError` is raised only at the appropriate Elasticsearch exception and when the duplicate policy is FAIL.
(Added a test that raises `DocumentStoreError`).
=> [Elasticsearch Document Store] improve error handling in `write_documents`

integrations/elasticsearch/pyproject.toml, integrations/elasticsearch/src/elasticsearch_haystack/bm25_retriever.py, integrations/elasticsearch/src/elasticsearch_haystack/document_store.py, integrations/elasticsearch/src/elasticsearch_haystack/embedding_retriever.py, integrations/elasticsearch/src/elasticsearch_haystack/filters.py, integrations/elasticsearch/tests/test_bm25_retriever.py, integrations/elasticsearch/tests/test_document_store.py, integrations/elasticsearch/tests/test_embedding_retriever.py, integrations/elasticsearch/tests/test_filters.py
This PR updates `ElasticSearchDocumentStore` to use the latest version of `haystack-ai`.
Including new testing base class and new filters logic.
=> Update `ElasticSearchDocumentStore` to use latest `haystack-ai` version

integrations/chroma/src/chroma_haystack/__about__.py, integrations/chroma/src/chroma_haystack/document_store.py, integrations/elasticsearch/src/elasticsearch_haystack/__about__.py, integrations/elasticsearch/tests/test_document_store.py, integrations/opensearch/src/opensearch_haystack/__about__.py, integrations/opensearch/tests/test_document_store.py
- document_store/protocol was renamed in https://github.com/deepset-ai/haystack/pull/6448
- this PR fixes the import in the Document Stores (fixes errors like this: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7094348178)
- increased the version numbers to prepare the new releases
=> Document Stores: fix protocol import

integrations/gradient/src/gradient_haystack/embedders/gradient_document_embedder.py, integrations/gradient/src/gradient_haystack/embedders/gradient_text_embedder.py, integrations/gradient/src/gradient_haystack/generator/base.py, integrations/instructor-embedders/instructor_embedders/embedding_backend/instructor_backend.py
Since integration packages depend on the respective external libraries, we should assume the dependency is there, without attempting to lazy-import it.
Note: I didn't remove it from `cohere` because that's done as part of https://github.com/deepset-ai/haystack-core-integrations/pull/80, to avoid conflicts
=> chore: remove LazyImport from integrations

integrations/cohere/README.md, integrations/cohere/pyproject.toml, integrations/cohere/src/cohere_haystack/embedders/__init__.py, integrations/cohere/src/cohere_haystack/embedders/document_embedder.py, integrations/cohere/src/cohere_haystack/embedders/text_embedder.py, integrations/cohere/src/cohere_haystack/embedders/utils.py, integrations/cohere/src/cohere_haystack/generator.py, integrations/cohere/tests/test_cohere_generators.py, integrations/cohere/tests/test_document_embedder.py, integrations/cohere/tests/test_text_embedder.py
Follow up of https://github.com/deepset-ai/haystack/pull/5831
=> [cohere] Add text and document embedders

integrations/cohere/src/cohere_haystack/__about__.py
Support for Cohere V3 models was added in #89.
It's time to release a new version and I'm simply increasing the version number...
=> Cohere: increase version to prepare release

integrations/cohere/src/cohere_haystack/embedders/utils.py
`API_BASE_URL` is unused and contains an outdated value.
It should be removed to avoid confusion.
=> Cohere: remove unused constant

integrations/chroma/pyproject.toml, integrations/cohere/pyproject.toml, integrations/elasticsearch/pyproject.toml, integrations/gradient/pyproject.toml, integrations/jina/pyproject.toml, integrations/unstructured/fileconverter/pyproject.toml, nodes/text2speech/pyproject.toml
Several integrations have outdated or wrong project URLs...
I'm leaving out `instructor-embedders`, since the URLs of this integration will be fixed in #95.
=> Fix project URLs

integrations/cohere/src/cohere_haystack/embedders/text_embedder.py, integrations/cohere/tests/test_text_embedder.py
Having `input_type = "search_query"` is a better default value for CohereTextEmbedder according to [Cohere Docs](https://docs.cohere.com/reference/embed)
=> Change default 'input_type' for CohereTextEmbedder

integrations/google-vertex/pyproject.toml, integrations/google-vertex/src/google_vertex_haystack/__about__.py, integrations/google-vertex/src/google_vertex_haystack/generators/chat/gemini.py, integrations/google-vertex/src/google_vertex_haystack/generators/gemini.py
* Fix some dependency issues when installing in Google Colab.
* Make `kwargs` in `GeminiGenerator` explicit
* Add `GeminiChatGenerator`
=> Update Google Vertex integration

integrations/chroma/pyproject.toml
Tests broke with the latest 0.4.20, to be investigated
=> chore: pin chroma version

.github/workflows/unstructured_fileconverter.yml, integrations/unstructured/fileconverter/pyproject.toml
~`latest` docker image broke the tests~
The latest release 0.11.4 broke the tests
=> chore: pin unstructured api version

integrations/elasticsearch/src/elasticsearch_haystack/document_store.py, integrations/elasticsearch/tests/test_document_store.py
Fixes #124.
Details in the original issue.
=> [Elasticsearch] - BM25 retrieval: not all terms must mandatorily match

integrations/cohere/src/cohere_haystack/embedders/document_embedder.py, integrations/cohere/src/cohere_haystack/embedders/text_embedder.py, integrations/cohere/src/cohere_haystack/generator.py, integrations/cohere/tests/test_cohere_generators.py, integrations/cohere/tests/test_document_embedder.py, integrations/google_vertex/src/google_vertex_haystack/generators/image_generator.py, integrations/gradient/tests/test_gradient_rag_pipelines.py, integrations/instructor_embedders/instructor_embedders_haystack/instructor_document_embedder.py, integrations/instructor_embedders/tests/test_instructor_document_embedder.py, integrations/jina/src/jina_haystack/document_embedder.py, integrations/jina/src/jina_haystack/text_embedder.py, integrations/jina/tests/test_document_embedder.py, integrations/jina/tests/test_text_embedder.py
- part of https://github.com/deepset-ai/haystack/issues/6570
- change `metadata` to `meta` (involves Embedders and Generators)
=> Change metadata to meta

integrations/google_vertex/src/google_vertex_haystack/generators/image_generator.py
fixes: #151 
This PR addresses a discrepancy in the default model used by VertexAIImageGenerator. According to the Vertex AI documentation, the correct default model for image generation is `imagegeneration`. However, the current default model is set to `imagetext`, which is designed for image captioning.
Updated the default model for VertexAIImageGenerator to `imagegeneration` to align with the Vertex AI documentation.
=> fixed: The default model of VertexAIImagegenerator

integrations/google_vertex/src/google_vertex_haystack/generators/chat/gemini.py, integrations/google_vertex/src/google_vertex_haystack/generators/gemini.py
To differentiate generators using Gemini we add this `VertexAI` prefix as we'd done with the `google-ai-haystack` integration that has the `GoogleAI` prefix for the Gemini generators.
=> Add VertexAI prefix to GeminiGenerator and GeminiChatGenerator components

integrations/ollama/src/ollama_haystack/generator.py
Language update to OllamaGenerator docstrings.
=> docs: Ollama docstrings update

integrations/cohere/src/cohere_haystack/chat/chat_generator.py, integrations/cohere/src/cohere_haystack/embedders/document_embedder.py, integrations/cohere/src/cohere_haystack/embedders/text_embedder.py, integrations/cohere/src/cohere_haystack/generator.py, integrations/cohere/tests/test_cohere_chat_generator.py, integrations/jina/src/jina_haystack/document_embedder.py, integrations/jina/src/jina_haystack/text_embedder.py, integrations/jina/tests/test_document_embedder.py, integrations/jina/tests/test_text_embedder.py, integrations/pinecone/src/pinecone_haystack/document_store.py, integrations/unstructured/fileconverter/src/unstructured_fileconverter_haystack/fileconverter.py
- part of https://github.com/deepset-ai/haystack/issues/6653
I improved the API keys reading logic and adopted it in all components that need it.
CI
=> Optimize API key reading

integrations/qdrant/src/qdrant_haystack/retriever.py, integrations/qdrant/tests/test_retriever.py
partially fixes: #134 
- QdrantRetriever ➔ QdrantEmbeddingRetriever
Not yet moved it inside the /retrievers folder, as there were no instances of other document stores following a similar structure.
=> renamed QdrntRetriever to QdrntEmbeddingRetriever

integrations/elasticsearch/src/elasticsearch_haystack/bm25_retriever.py, integrations/elasticsearch/src/elasticsearch_haystack/document_store.py
Solves deepset-ai/haystack#6601
=> Add more docstrings for `ElasticsearchDocumentStore` and `ElasticsearchBM25Retriever`

integrations/opensearch/src/opensearch_haystack/document_store.py
=> fix links in docstrings

integrations/ollama/tests/test_chat_generator.py
This test sometimes fails ([an example](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7482286030/job/20365554468)) because this small model (orca-mini)
refers to Glasgow as the second largest city in UK. :smile:
=> Ollama: improve test

integrations/weaviate/pyproject.toml, integrations/weaviate/src/weaviate_haystack/document_store.py, integrations/weaviate/tests/test_document_store.py
Relates to #131 
This PR implements a minimal initialization of `WeaviateDocumentStore` and the internal Weaviate client.
It also adds proper serialization of the Document Store.
We also fix the `weaviate-client` version to avoid breakages whenever the next upcoming version is released.
=> WeaviateDocumentStore initialization and serialization

integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_document_store.py
Depends on #214.
Now `WeaviateDocumentStore` can be initialized specifying a collection name, if that collection doesn't exist it will be created.
=> Add `collection_name` parameter and creation

integrations/cohere/src/cohere_haystack/chat/chat_generator.py, integrations/cohere/src/cohere_haystack/embedders/document_embedder.py, integrations/cohere/src/cohere_haystack/embedders/text_embedder.py, integrations/cohere/src/cohere_haystack/generator.py, integrations/cohere/tests/test_cohere_chat_generator.py, integrations/cohere/tests/test_cohere_generators.py, integrations/cohere/tests/test_document_embedder.py, integrations/cohere/tests/test_text_embedder.py
- part of https://github.com/deepset-ai/haystack-core-integrations/issues/227
- Related to https://github.com/deepset-ai/haystack-integrations/pull/128
- Rename `model_name` to `model` in the generators and embedders of the Cohere integration
=> chore!: Rename `model_name` to `model` in the Cohere integration

integrations/instructor_embedders/instructor_embedders_haystack/instructor_document_embedder.py, integrations/instructor_embedders/instructor_embedders_haystack/instructor_text_embedder.py, integrations/instructor_embedders/tests/test_instructor_document_embedder.py, integrations/instructor_embedders/tests/test_instructor_text_embedder.py
- part of https://github.com/deepset-ai/haystack-core-integrations/issues/227
- related to https://github.com/deepset-ai/haystack-integrations/pull/130
- Rename `model_name_or_path` to `model` in the embedders of the Instructor integration
=>  chore!: Rename `model_name_or_path` to `model` in the Instructor integration

integrations/opensearch/pyproject.toml, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/__init__.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/bm25_retriever.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/embedding_retriever.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/__init__.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/filters.py, integrations/opensearch/src/opensearch_haystack/__init__.py, integrations/opensearch/tests/test_bm25_retriever.py, integrations/opensearch/tests/test_document_store.py, integrations/opensearch/tests/test_embedding_retriever.py, integrations/opensearch/tests/test_filters.py
Part of #208 
See #100 for details
Note: this PR requires https://github.com/deepset-ai/haystack/pull/6714 that's not present in beta4, need to wait for beta5 to let the tests pass
=> move package under haystack_integrations/*

integrations/gradient/tests/test_gradient_document_embedder.py, integrations/gradient/tests/test_gradient_rag_pipelines.py, integrations/gradient/tests/test_gradient_text_embedder.py
Import paths for in-memory document store have changed, this PR updates them across the gradient integration
=> update import paths for beta5

integrations/chroma/example/example.py, integrations/chroma/src/haystack_integrations/components/retrievers/chroma/__init__.py, integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py
The retriever was originally introduced when Haystack components expected to receive `List[List[Document]]`, but we lately standardized the format to pass single queries and receive one single list of results. For this reason `ChromaSingleQueryRetriever` is being removed and `ChromaQueryRetriever` changed so it looks like the other retrievers and can be used as a drop-in replacement in existing pipelines.
=> Remove ChromaSingleQueryRetriever

integrations/gradient/src/gradient_haystack/embedders/gradient_document_embedder.py, integrations/gradient/src/gradient_haystack/embedders/gradient_text_embedder.py, integrations/gradient/tests/test_gradient_document_embedder.py, integrations/gradient/tests/test_gradient_text_embedder.py
- part of https://github.com/deepset-ai/haystack-core-integrations/issues/227
- The model card doesn't mention the parameter, so no change is needed
- Rename `model_name` to `model` in the embedders of the Gradient integration
=> chore!: Rename model_name to model in the Gradient integration

integrations/jina/src/jina_haystack/document_embedder.py, integrations/jina/src/jina_haystack/text_embedder.py, integrations/jina/tests/test_document_embedder.py, integrations/jina/tests/test_text_embedder.py
- part of  https://github.com/deepset-ai/haystack-core-integrations/issues/227
- related to https://github.com/deepset-ai/haystack-integrations/pull/131
- Rename model_name to model in the embedders of the Jina integration
=> chore!: Rename model_name to model in the Jina integration

integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/generator.py, integrations/llama_cpp/tests/test_generator.py
- part of  https://github.com/deepset-ai/haystack-core-integrations/issues/227
- the PR for the card is still open here: https://github.com/deepset-ai/haystack-integrations/pull/118 Changes were suggested accordingly
- Rename model_path to model in the embedders of the Llama.cpp integration
This integration is a bit different from the others because it only expects a model path, so the name might be justified. However, for consistency I preferred to standardize this one as well. Feel free to object this change if we prefer to leave the parameter's name unchanged instead.
=> chore!: Rename model_path to model in the Llama.cpp integration

integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_document_store.py
This PR implements the following methods:
* `filter_documents`
* `write_documents`
* `delete_documents`
`filter_documents` as of now doesn't support any filtering and returns all stored Documents, future PRs will add support for filters.
Depends on #269
=> Add filter, write and delete documents in Weaviate

integrations/instructor_embedders/pyproject.toml
After a year and a half, a new version of Sentence Transformers (2.3.0) was released yesterday.
Unfortunately, it is not compatible with Instructor Embedders. See the errors: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7704162608/job/20995940719
Related: https://github.com/xlang-ai/instructor-embedding/issues/106
With this PR, I am pinning Sentence Transformers for this package.
=> Instructor embedders: pin Sentence Transformers

integrations/pinecone/tests/conftest.py
Pinecone tests are often failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7704216518
I hope that errors can be avoided by increasing the sleep time: the time between a write operation and the next read to verify a condition.
=> increase pinecone sleep time

integrations/pinecone/src/haystack_integrations/document_stores/pinecone/document_store.py
Fixes #300.
I only changed the dummy vector from `[0.0] * self.dimension` to `[-10.0] * self.dimension`.
It is important to choose a highly improbable value for the user-supplied vectors, because this value is removed during retrieval.
=> Pinecone - change dummy vector

integrations/chroma/pyproject.toml
The integration doesn't work with `typing_extensions<4.8.0`. This PR pins `typing_extensions>=4.8.0` to make sure the requirement is respected.
=> Add typing_extensions pin to Chroma integration

integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py, integrations/pgvector/tests/conftest.py, integrations/pgvector/tests/test_embedding_retrieval.py
Implementation of the embedding retrieval for Pgvector Document Store.
The Embedding Retriever will be implemented in a future PR.
=> Pgvector - embedding retrieval

integrations/pinecone/pyproject.toml, integrations/pinecone/tests/conftest.py
[Pinecone tests keep failing](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7734112772/job/21087510975), despite my recent attempt to fix them in #288.
The error is "Too Many Requests".
So I am doing two things:
- decrease the concurrency in tests (lowering the number of workers from 3 to 2)
- decrease the sleep time a bit, since it does not seem to be responsible for this error
=> Pinecone - decrease concurrency in tests

integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py
The linter is failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7749291365/job/21133554644
This PR simplifies the condition, fixing the problem.
=> Pgvector: fix linting

.github/labeler.yml
- This PR updates labeler.yml to also take pgvector into account.
- I also changed the paths for the unstructured integration (refactored in #221).
=> Labeler: add new entry for pgvector

.github/workflows/cohere.yml
Fixes #338.
Integration tests for Cohere integration are not running as of now, this fixes it.
The `COHERE_API_KEY` has already been added to the repo secrets.
=> Add `COHERE_API_KEY` secret to CI environment

integrations/uptrain/example/example.py, integrations/uptrain/src/haystack_integrations/components/evaluators/evaluator.py, integrations/uptrain/src/haystack_integrations/components/evaluators/metrics.py, integrations/uptrain/tests/test_evaluator.py
The evaluator will automatically flatten them. This change allows other evaluators that take nested lists for contexts (like DeepEval) share the same, basic interface.
=> refactor!: `UptrainEvaluator` contexts are now passed as nested lists.

.github/utils/docstrings_checksum.py, .github/workflows/CI_docstring_labeler.yml
This PR adds a workflow and a script to label PRs that edit in any way a Python docstring.
The workflow is identical to the one used in Haystack core repository. 
The `docstrings_checksum.py` script has been slightly adjusted for this repo structure.
=> CI: Add script and workflow to label PRs that edit docstrings

.github/workflows/unstructured.yml
Fixes https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7807901669/job/21297174729
- I introduced a "Free up disk space" initial step.
- I moved the Docker container run from `services` to a workflow `step`, just to start after the "free up" step.
=> Unstructured: prevent "no space left on device" in tests

.github/workflows/CI_docstring_labeler.yml
This reverts commit 66bede7bd601c1e6dcd071ba0cae8ef9f4275974.
Workflow that automatically assign @dfokina as reviewer in PR that edit docstrings is failing. 
Revert the change for the time being to avoid blocking other PRs. 
Will investigate and find a different solution.
=> Revert "Change docstring labeler workflow to add Daria as reviewer (#357)"

.github/workflows/jina.yml, integrations/jina/pydoc/config.yml, integrations/jina/pyproject.toml
=> feat: Generate API docs for Jina

integrations/unstructured/src/haystack_integrations/components/converters/unstructured/converter.py, integrations/unstructured/tests/test_converter.py
Adding element index in the metadata when partition mode is by element
Close feature request: https://github.com/deepset-ai/haystack-core-integrations/issues/378
> Is your feature request related to a problem? Please describe.
> With unstructured we can do partition: one doc per file, one doc per page or one doc per elem.
> When doing one doc per elem there is no way to track orders of element coming from a same doucment.
> This informations can be usefull for example for a ContextExpander component.
> Let's say you retrieve an element, you can retrieve also the previous and next element to expand the current context .
> 
> Describe the solution you'd like
> Just automatically add index metadata.
> I will do a PR.
=> feat(unstructured): add element index as metadata

integrations/cohere/pyproject.toml, integrations/cohere/src/haystack_integrations/components/embedders/cohere/document_embedder.py, integrations/cohere/src/haystack_integrations/components/embedders/cohere/text_embedder.py, integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py, integrations/cohere/src/haystack_integrations/components/generators/cohere/generator.py, integrations/cohere/tests/test_cohere_chat_generator.py, integrations/cohere/tests/test_cohere_generators.py, integrations/cohere/tests/test_document_embedder.py, integrations/cohere/tests/test_text_embedder.py
=> refactor!: Use `Secret` for API keys in Cohere components

integrations/chroma/example/example.py, integrations/chroma/src/haystack_integrations/components/retrievers/chroma/__init__.py, integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py, integrations/chroma/tests/test_retriever.py
part of #406
ChromaQueryRetriever > ChromaQueryTextRetriever
=> Chroma: rename retriever

integrations/weaviate/pyproject.toml, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/_filters.py, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_document_store.py, integrations/weaviate/tests/test_filters.py
This PR add support for `filters` in `WeaviateDocumentStore.filter_documents()` method.
All tests are passing except for `test_comparison_not_equal_with_dataframe`. 
For some reason that test is not returning what we expect from Weaviate. 
I decided to skip it for the time being as I wanted to get this out of the door.
=> Implement filtering for `WeaviateDocumentStore`

integrations/qdrant/pyproject.toml, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py, integrations/qdrant/tests/test_dict_converters.py
Related to https://github.com/deepset-ai/haystack-core-integrations/issues/372
=> refactor!: Qdrant - update secret management

integrations/cohere/tests/test_cohere_chat_generator.py, integrations/cohere/tests/test_cohere_generators.py, integrations/cohere/tests/test_document_embedder.py, integrations/cohere/tests/test_text_embedder.py
- generally, we don't want to match the error message
- it causes errors like [this](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7909096256/job/21589539454): the error message of the Cohere API can easily change over time
(I also removed the match clause from other tests)
=> Choere - remove matching error message from tests

integrations/astra/examples/example.py, integrations/astra/examples/pipeline_example.py, integrations/instructor_embedders/pyproject.toml, integrations/instructor_embedders/src/haystack_integrations/components/embedders/instructor_embedders/embedding_backend/instructor_backend.py, integrations/instructor_embedders/src/haystack_integrations/components/embedders/instructor_embedders/instructor_document_embedder.py, integrations/instructor_embedders/src/haystack_integrations/components/embedders/instructor_embedders/instructor_text_embedder.py, integrations/instructor_embedders/tests/test_instructor_backend.py, integrations/instructor_embedders/tests/test_instructor_document_embedder.py, integrations/instructor_embedders/tests/test_instructor_text_embedder.py, integrations/llama_cpp/README.md, integrations/llama_cpp/examples/rag_pipeline_example.py
Based on #417 - please **do not merge** until the base branch has been merged
Migration to `model` was done in #229.
- Some examples are erroneously using the old `model_name_or_path`.
- For Instructor embedders, I am changing the attributes' names just because I found them confusing
=> model_name_or_path > model

integrations/pinecone/examples/example.py, integrations/pinecone/src/haystack_integrations/document_stores/pinecone/document_store.py, integrations/pinecone/tests/conftest.py, integrations/pinecone/tests/test_document_store.py, integrations/pinecone/tests/test_emebedding_retriever.py
=> [Pinecone] Use Haystack Secrets

integrations/weaviate/pydoc/config.yml, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/__init__.py, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/auth.py, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_auth.py, integrations/weaviate/tests/test_document_store.py
Fixes #369.
Weaviate supports different manner of authentication via some utility dataclasses. 
Cause of this it wasn't feasible to use an init parameterer for each possible secret, so we mirrored a bit their utility classes structures to use the `Secret` class.
You'll notice that I used a `default_factory` in all dataclasses fields cause we can't use `default` as `Secret` is not a frozen dataclass in the latest beta. When that changes we should be able to use `default`.
=> Update WeaviateDocumentStore authentication to use new Secret class

integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py
Fixes https://github.com/deepset-ai/haystack-core-integrations/pull/413#discussion_r1491426418
Removed the `filters` parameter from the `MongoDBAtlasDocumentStore.count()` method.
=> fix: remove filters from `MongoDBAtlasDocumentStore.count()` method

.github/workflows/CI_readme_sync.yml, integrations/chroma/README.md
- The env variable seemed to mess up with the API key contents, now passing the secret directly to `--key`, as per Readme's offical docs
- Also pin the action less aggressively, so we can pull updates more frequently (dependabot was late and made us make a big version jump)
Test workflow passed with this new configuration: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7948402876/job/21698363580
=> Fix Readme sync

integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/bm25_retriever.py, integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/embedding_retriever.py
The retrievers of elasticsearch only accept filters on initialization. They should also accept filters as argument to the `run` function.
=> Feat: Add filters to run function in retrievers of elasticsearch

.github/workflows/amazon_sagemaker.yml, integrations/amazon_sagemaker/pydoc/config.yml, integrations/amazon_sagemaker/pyproject.toml
From a [recent failed workflow](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7957150243/job/21719290510), I noticed that the API docs machinery was missing for Amazon Sagemaker integration.
I'm adding it.
=> Amazon Sagemaker - create API docs

integrations/amazon_bedrock/pydoc/config.yml, integrations/amazon_sagemaker/pydoc/config.yml, integrations/astra/pydoc/config.yml, integrations/chroma/pydoc/config.yml, integrations/cohere/pydoc/config.yml, integrations/deepeval/pydoc/config.yml, integrations/elasticsearch/pydoc/config.yml, integrations/fastembed/pydoc/config.yml, integrations/google_ai/pydoc/config.yml, integrations/google_vertex/pydoc/config.yml, integrations/gradient/pydoc/config.yml, integrations/instructor_embedders/pydoc/config.yml, integrations/jina/pydoc/config.yml, integrations/llama_cpp/pydoc/config.yml, integrations/mistral/pydoc/config.yml, integrations/mongodb_atlas/pydoc/config.yml, integrations/ollama/pydoc/config.yml, integrations/opensearch/pydoc/config.yml, integrations/pgvector/pydoc/config.yml, integrations/pinecone/pydoc/config.yml, integrations/qdrant/pydoc/config.yml, integrations/ragas/pydoc/config.yml, integrations/unstructured/pydoc/config.yml, integrations/uptrain/pydoc/config.yml, integrations/weaviate/pydoc/config.yml
`category_slug` changed on Readme from Haystack Integrations to Integrations API, which prevented docs from syncing
=> docs: update category slug

.github/workflows/CI_readme_sync.yml
Try to prevent failure like this: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7961842838/job/21733934609
caused by "No space left on device"
=> Docs workflow - clean up hatch env after docs generation

integrations/astra/src/haystack_integrations/document_stores/astra/astra_client.py
Small typo in the Astra DB integration to properly handle the sort field.
=> FIX: proper name for the sort param for Astra DB Integration

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/amazon_bedrock/tests/test_amazon_chat_bedrock.py
Related to [#415](https://github.com/deepset-ai/haystack-core-integrations/issues/415)
=> chore: Update Amazon Bedrock integration to use new generic callable (de)serializers for their callback handlers

integrations/uptrain/pyproject.toml, integrations/uptrain/src/haystack_integrations/components/evaluators/uptrain/evaluator.py, integrations/uptrain/tests/test_evaluator.py
UpTrain requires a project_name when using its API whereas openai does not. The integration will crash if no project_name is included.
This will allow for an eval declaration like so:
evaluator = UpTrainEvaluator(
metric=UpTrainMetric.METRIC,
api="uptrain",
project_name="uptrain-project",
)
This was the fix I found that resolved my issue. It might not be a full fix as I have not read too deep into the source code.
=> Allow passing in required project_name

integrations/uptrain/pyproject.toml, integrations/uptrain/src/haystack_integrations/components/evaluators/uptrain/evaluator.py, integrations/uptrain/tests/test_evaluator.py
This reverts commit ffe86a9 as it adds a superfluous parameter - API-specific params like `project_name` can be already be passed with the `api_params` init parameter.
This PR additionally clarifies this in the component's docstring and adds a sanity check to make sure the required API params are correctly passed.
=> fix: Revert "Allow passing in required project_name (#445)"

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py
Related to https://github.com/deepset-ai/haystack-core-integrations/issues/415
NOTE: requires a new beta release for the tests to pass. Don't merge!
=> chore: Use `serialize_callable` instead of `serialize_callback_handler` in Bedrock

integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py, integrations/elasticsearch/tests/test_document_store.py
[Elastic](https://www.elastic.co/) wants to provide a great developer experience with 3rd party integrations. In order to be able to prioritize maintenance and feature development efforts, we keep track of which integrations are popular by setting the `user-agent` header. We can then see usage statistics in the [Elastic Cloud](https://cloud.elastic.co/) metrics.
We want to gauge the usage of the Haystack integration and hence add a `user-agent` header here.
=> Elasticsearch: add user-agent header

integrations/mongodb_atlas/pyproject.toml
Fixes a typo in pyproject.toml that prevents releasing the package.
=> fix: `pyproject.toml` typo for MongoDB Atlas

.github/workflows/ollama.yml, integrations/ollama/src/haystack_integrations/components/embedders/ollama/document_embedder.py, integrations/ollama/src/haystack_integrations/components/embedders/ollama/text_embedder.py, integrations/ollama/tests/test_document_embedder.py, integrations/ollama/tests/test_text_embedder.py
Ollama has officially released embedding models with their 0.26 release. Before, we used a lightweight llm model orca-mini to embed, which is much slower. The Nomic-Embed-Text model is much more efficient and should be the standard for an embedded model. This requires the nomic-embed-text model to be pulled from the repo via "ollama pull nomic-embed-text".
https://ollama.com/library/nomic-embed-text
=> Changed Default Ollama Embedding models to supported model: nomic-embed-text

.github/workflows/optimum.yml, integrations/optimum/pydoc/config.yml, integrations/optimum/src/haystack_integrations/components/embedders/optimum/__init__.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/_backend.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/optimization.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/optimum_document_embedder.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/optimum_text_embedder.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/pooling.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/quantization.py, integrations/optimum/tests/test_optimum_document_embedder.py, integrations/optimum/tests/test_optimum_text_embedder.py
This PR adds support for Optimum-backed optimization and quantization of models.
=> feat!: Add support for Optimum optimizers and quantizers

integrations/mistral/src/haystack_integrations/components/embedders/mistral/document_embedder.py, integrations/mistral/src/haystack_integrations/components/embedders/mistral/text_embedder.py, integrations/mistral/src/haystack_integrations/components/generators/mistral/chat/chat_generator.py
Fixes https://github.com/deepset-ai/haystack/issues/7141
=> chore: update docstrings

integrations/jina/src/haystack_integrations/components/embedders/jina/document_embedder.py, integrations/jina/src/haystack_integrations/components/embedders/jina/text_embedder.py
fixes https://github.com/deepset-ai/haystack/issues/7139
=> Jina - review docstrings

integrations/pgvector/examples/example.py, integrations/pgvector/pydoc/config.yml, integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/embedding_retriever.py, integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py
- fixes https://github.com/deepset-ai/haystack/issues/7146
- fixes https://github.com/deepset-ai/haystack/issues/7198 (small change)
=> pgvector - review docstrings and API reference

integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py
Document store API was outdated
=> fix: make write_documents compatible with the DocumentStore protocol

integrations/llama_cpp/examples/llama_cpp_generator_example.py, integrations/llama_cpp/examples/rag_pipeline_example.py
llama.cpp examples were outdated.
- old `model_path` parameter
- old parameters in `Pipeline.connect`
=> llama.cpp - update examples

integrations/amazon_sagemaker/src/haystack_integrations/components/generators/amazon_sagemaker/sagemaker.py
- fixes https://github.com/deepset-ai/haystack/issues/7128
=> Update docs for Amazon Sagemaker

integrations/ragas/src/haystack_integrations/components/evaluators/ragas/evaluator.py, integrations/ragas/src/haystack_integrations/components/evaluators/ragas/metrics.py
- fixes https://github.com/deepset-ai/haystack/issues/7149
- fixes https://github.com/deepset-ai/haystack/issues/7201
=> docs: Update `ragas-haystack` docstrings

integrations/unstructured/pyproject.toml, integrations/unstructured/src/haystack_integrations/components/converters/unstructured/converter.py
fixes https://github.com/deepset-ai/haystack/issues/7150
=> Unstructured: review docstrings

integrations/unstructured/src/haystack_integrations/components/converters/unstructured/converter.py, integrations/unstructured/tests/test_converter.py
`from_dict` method is missing but it is necessary to properly deserialize the API key.
For example, this fails:
```python
import os
from haystack import default_from_dict
from haystack_integrations.components.converters.unstructured import UnstructuredFileConverter
os.environ["UNSTRUCTURED_API_KEY"] = "test"
conv = UnstructuredFileConverter()
ser_converter = conv.to_dict()
new_conv = default_from_dict(UnstructuredFileConverter, ser_converter)
```
error:
```
api_key_value = api_key.resolve_value() if api_key else None
AttributeError: 'dict' object has no attribute 'resolve_value'
```
---
**I added the missing `from_dict` method** and a related test.
=> unstructured: add missing `from_dict` method

integrations/uptrain/src/haystack_integrations/components/evaluators/uptrain/evaluator.py, integrations/uptrain/src/haystack_integrations/components/evaluators/uptrain/metrics.py
- fixes https://github.com/deepset-ai/haystack/issues/7151
- fixes https://github.com/deepset-ai/haystack/issues/7203
=> docs: Update `uptrain-haystack` docstrings

integrations/nvidia/pydoc/config.yml, integrations/nvidia/pyproject.toml, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/_schema.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/document_embedder.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/models.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/text_embedder.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/client.py, integrations/nvidia/tests/test_document_embedder.py, integrations/nvidia/tests/test_placeholder.py, integrations/nvidia/tests/test_text_embedder.py
- fixes https://github.com/deepset-ai/haystack-private/issues/70
=> feat: Add `NvidiaTextEmbedder`, `NvidiaDocumentEmbedder` and co.

integrations/mongodb_atlas/examples/example.py
part of #143
I improved the example, which had some issues and was incomplete
=> MongoDB: improve example

integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_document_embedder.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_text_embedder.py
- fixes https://github.com/deepset-ai/haystack/issues/7187
=> docs: Fix `integrations.fastembed` API docs

.github/workflows/ollama.yml, integrations/ollama/pyproject.toml
- testing Ollama using Docker started failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8164727809
- the integrations works correctly (locally tested)
- Github services are sometimes unreliable and Ollama can be installed without Docker
So I am dropping the installation via Docker and I'm installing it following [the official instructions](https://github.com/ollama/ollama?tab=readme-ov-file#linux).
=> Ollama: change testing workflow

integrations/fastembed/pyproject.toml, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/embedding_backend/fastembed_backend.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_document_embedder.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_text_embedder.py, integrations/fastembed/tests/test_fastembed_document_embedder.py, integrations/fastembed/tests/test_fastembed_text_embedder.py
While looking at #554 and at the cookbook, I found several opportunities to improve this integration.
Fixes #554
=> improvements to FastEmbed integration

integrations/ragas/src/haystack_integrations/components/evaluators/ragas/evaluator.py, integrations/ragas/src/haystack_integrations/components/evaluators/ragas/metrics.py, integrations/ragas/tests/test_evaluator.py
fixes #528 
- Extends metric param validation, so that it is done by our integration framework and not Ragas
=> [RAGAS] fix: Metric parameter validation and metric descriptors

integrations/astra/pyproject.toml, integrations/chroma/pyproject.toml, integrations/cohere/pyproject.toml, integrations/deepeval/pyproject.toml, integrations/elasticsearch/pyproject.toml, integrations/google_ai/pyproject.toml, integrations/google_vertex/pyproject.toml, integrations/gradient/pyproject.toml, integrations/jina/pyproject.toml, integrations/llama_cpp/pyproject.toml, integrations/mistral/pyproject.toml, integrations/nvidia/pyproject.toml, integrations/opensearch/pyproject.toml, integrations/optimum/pyproject.toml, integrations/pinecone/pyproject.toml, integrations/qdrant/pyproject.toml, integrations/ragas/pyproject.toml, integrations/uptrain/pyproject.toml, integrations/weaviate/pyproject.toml
The tests for some integrations showed the coverage of test files instead of the coverage of other files in the integration.
I tried to fix this in a standardized way, by changing the respective pyproject files.
=> Make tests show coverage

integrations/chroma/tests/test_document_store.py, integrations/cohere/tests/test_cohere_chat_generator.py, integrations/deepeval/tests/test_evaluator.py, integrations/elasticsearch/tests/test_document_store.py, integrations/mongodb_atlas/tests/test_retriever.py, integrations/opensearch/tests/test_document_store.py, integrations/pgvector/tests/conftest.py, integrations/pgvector/tests/test_document_store.py, integrations/pgvector/tests/test_embedding_retrieval.py, integrations/pgvector/tests/test_filters.py, integrations/pgvector/tests/test_retriever.py, integrations/weaviate/tests/test_document_store.py
To properly address #435,
it is best to completely separate unit tests from integration tests.
This PR attempts to do that, resulting in:
- removing the marker `pytest.mark.unit`
- adding the marker `pytest.mark.integration` where needed
- refactoring some tests so that they actually behave as unit tests
I was able to run all unit tests (not marked with `pytest.mark.integration`) locally, without API keys set and containers running.
=> Refactor tests

.github/workflows/anthropic.yml, integrations/anthropic/LICENSE.txt, integrations/anthropic/README.md, integrations/anthropic/example/documentation_rag_with_claude.py, integrations/anthropic/pydoc/config.yml, integrations/anthropic/pyproject.toml, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/__init__.py, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/__init__.py, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/generator.py, integrations/anthropic/tests/__init__.py, integrations/anthropic/tests/conftest.py, integrations/anthropic/tests/test_chat_generator.py, integrations/anthropic/tests/test_generator.py
This Pull Request introduces a new integration for the Haystack framework, enabling the use of Anthropic's Claude family of language models. Anthropic's API provides advanced features such as streaming responses and customizability, making it an excellent addition to Haystack's list of supported integrations.
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/139
The PR adds:
- A new top-level directory `integrations/anthropic` including:
- `src` directory containing the integration implementation
- `tests` directory with test files
- `pyproject.toml` defining build and packaging information
- `pydoc` directory with configuration and markdown file for automatically generated documentation
- `LICENSE.txt` for the Apache License 2.0
- An updated …
=> feat: Add AnthropicGenerator and AnthropicChatGenerator

integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/bm25_retriever.py, integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/embedding_retriever.py, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_embedding_retriever.py
Fixes https://github.com/deepset-ai/haystack/issues/7152
=> docs: fix docstrings

.github/workflows/google_ai.yml
This integration was mistakenly assigned to the same concurrency group as Google Vertex.
This sometimes caused tests to be skipped for no good reason...
=> Change Google AI concurrency group for tests

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_document_store.py
=> Fix opensearch errors bulk write

integrations/pinecone/tests/test_filters.py
Temporary solution for #590
The skipped tests should be reworked when Pinecone introduces a better handling of null values.
=> Pinecone: temporarily skip failing tests

integrations/cohere/tests/test_cohere_chat_generator.py
Sometimes the check fails with `message.meta["citations"]` being `None`. Nothing we can do about it, IMO tests shouldn't fail there.
=> test: relax test constraints

.github/workflows/deepeval.yml, .github/workflows/ragas.yml, .github/workflows/uptrain.yml
=> evaluation components - use API keys in tests

integrations/amazon_bedrock/pyproject.toml, integrations/amazon_sagemaker/pyproject.toml, integrations/anthropic/pyproject.toml, integrations/astra/pyproject.toml, integrations/chroma/pyproject.toml, integrations/cohere/pyproject.toml, integrations/deepeval/pyproject.toml, integrations/elasticsearch/pyproject.toml, integrations/fastembed/pyproject.toml, integrations/google_ai/pyproject.toml, integrations/google_vertex/pyproject.toml, integrations/gradient/pyproject.toml, integrations/instructor_embedders/pyproject.toml, integrations/jina/pyproject.toml, integrations/llama_cpp/pyproject.toml, integrations/mistral/pyproject.toml, integrations/mongodb_atlas/pyproject.toml, integrations/nvidia/pyproject.toml, integrations/ollama/pyproject.toml, integrations/opensearch/pyproject.toml, integrations/optimum/pyproject.toml, integrations/pgvector/pyproject.toml, integrations/pinecone/pyproject.toml, integrations/qdrant/pyproject.toml, integrations/ragas/pyproject.toml, integrations/unstructured/pyproject.toml, integrations/uptrain/pyproject.toml, integrations/weaviate/pyproject.toml
fixes #581
- Uptrain is expected to fail (see #571).
- I haven't touched the [`text2speech` nodes](https://github.com/deepset-ai/haystack-core-integrations/tree/main/nodes), which are deprecated and refer to Haystack 1.x.
=> remove references to Python 3.7

integrations/astra/src/haystack_integrations/document_stores/astra/document_store.py, integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py, integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py, integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py, integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py, integrations/pinecone/src/haystack_integrations/document_stores/pinecone/document_store.py, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/converters.py, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py
Fixes #604: see that for details
=> Make Document Stores initially skip `SparseEmbedding`

integrations/cohere/pyproject.toml
Cohere just released a major release of their client, and there are several breaking changes. Pinning the version to <5 for now.
Tracking issue: https://github.com/deepset-ai/haystack-core-integrations/issues/608
=> fix: Pin cohere version

.github/workflows/CI_readme_sync.yml
fixes #479
I modified the existing "Core / Sync docs with Readme" workflow
- does not run on main
- runs when pushing release tags or is manually activated
- only generates docs for the specified integration
I tested the workflow in this PR and seems to work properly: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8356934800/job/22875054669
=> CI: push docs when releasing a new version

.github/workflows/CI_readme_sync.yml
The workflow is failing when manually triggered: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8381537136/job/22967317316
This happens because the manually entered tag is ignored.
I am trying to fix this.
=> fix readme_sync workflow

.github/workflows/CI_readme_sync.yml
readme_sync still fails when manually triggered: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8386972874/job/22968297987
I hope this PR fixes it :slightly_smiling_face:
=> retry fixing readme_sync

integrations/weaviate/docker-compose.yml, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_document_store.py
Fix #520.
By default Weaviate doesn't return any score when retrieving objects.
This PR changes bm25 and embedding retrieval to return the score for each retrieved document.
Different Weaviate metadata fields are used for scoring, bm25 takes the score from the `score` metadata field, while embedding from the `certainty` field.
=> Fix Weaviate retrievers returning no score

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py, integrations/google_ai/tests/generators/test_gemini.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/code_generator.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/gemini.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/question_answering.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/text_generator.py
=> Google Generators: change `answers` to `replies`

.github/workflows/uptrain.yml
Tests are currently expected to fail, disabling nightlies
=> Disable nightly tests for uptrain

integrations/pinecone/src/haystack_integrations/components/retrievers/pinecone/embedding_retriever.py, integrations/pinecone/src/haystack_integrations/document_stores/pinecone/document_store.py, integrations/pinecone/tests/test_document_store.py, integrations/pinecone/tests/test_emebedding_retriever.py, integrations/pinecone/tests/test_filters.py
Also add some feature gates to tests
=> fix: Correctly deserialize Pinecone docstore in embedding retriever

integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py
fixes #616 
So far, metadata fields were analyzed during indexing, for example lowercased because the elasticsearch integration did not define a different mapping for them. When users tried to filter based on metadata fields by a string with uppercase letter or with whitespace, it is not automatically analyzed. Therefore the filter did not match.
- Add dynamic template that defines any additional index fields as mapping type `keyword`, which means they are not analyzed. This is the desired behavior. Same behavior as in other document stores such as OpenSearchDocumentStore.
- Explicitly defined the mapping type of the content field as `text`, which means it is analyzed
I tested Elasticsearch and OpenSearch locally.
```python
from haystack import Document
from haystack.components.retrievers …
```
=> [Elasticsearch] fix: Filters not working with metadata that contain a space or capitalization

integrations/qdrant/pydoc/config.yml, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/__init__.py, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/migrate_to_sparse.py
Add a utility function to migrate an existing `QdrantDocumentStore` to a new one with support for sparse embeddings.
Related to #578
Inspired by @lambda-science's migration script reported in https://github.com/deepset-ai/haystack-core-integrations/pull/578#issuecomment-2049202143 
Applies to on-premise and cloud instances of Qdrant but does not work for local in-memory/disk-persisted instances.
I tested it locally with 10K documents.
Since our tests are based on memory instances of Qdrant, to test the migration function in the CI,
we should rework our testing suite introducing Docker.
=> Qdrant: add migration utility function for Sparse Embedding support

integrations/qdrant/examples/embedding_retrieval.py, integrations/qdrant/pyproject.toml
Examples are missing for this integration.
I'm adding this simple example, also to help users figure out how to use Qdrant Document Store (see #642).
=> Qdrant: add embedding retrieval example

integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/__init__.py, integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/retriever.py, integrations/qdrant/tests/test_retriever.py
I realized that `QdrantSparseRetriever` should be `QdrantSparseEmbeddingRetriever`,
according to our [naming convention for Retrievers](https://docs.haystack.deepset.ai/docs/retrievers#naming-conventions).
Luckily, this feature has not yet been documented or promoted.
I'm renaming the retriever.
=> rename `QdrantSparseRetriever` to `QdrantSparseEmbeddingRetriever`

integrations/amazon_bedrock/pyproject.toml, integrations/amazon_sagemaker/pyproject.toml, integrations/anthropic/pyproject.toml, integrations/astra/pyproject.toml, integrations/chroma/pyproject.toml, integrations/cohere/pyproject.toml, integrations/deepeval/pyproject.toml, integrations/elasticsearch/pyproject.toml, integrations/fastembed/pyproject.toml, integrations/google_ai/pyproject.toml, integrations/google_vertex/pyproject.toml, integrations/gradient/pyproject.toml, integrations/instructor_embedders/pyproject.toml, integrations/jina/pyproject.toml, integrations/llama_cpp/pyproject.toml, integrations/mistral/pyproject.toml, integrations/mongodb_atlas/pyproject.toml, integrations/nvidia/pyproject.toml, integrations/ollama/pyproject.toml, integrations/opensearch/pyproject.toml, integrations/optimum/pyproject.toml, integrations/pgvector/pyproject.toml, integrations/pinecone/pyproject.toml, integrations/qdrant/pyproject.toml, integrations/ragas/pyproject.toml, integrations/unstructured/pyproject.toml, integrations/weaviate/pyproject.toml
Fixes #650 
- Once this PR gets merged, the change will be visible after the first release of each package.
- I propose we don't release the packages only for this reason
=> chore: add license classifiers

integrations/astra/src/haystack_integrations/document_stores/astra/document_store.py, integrations/astra/tests/test_document_store.py, integrations/astra/tests/test_retriever.py
Fixes #682 
It's now possible to pass the namespace to the document store constructor.
=> fix: pass namespace in the docstore init

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py
fixes #684 
Proposed Changes: Modified the to_dict method to properly serialize in case when the streaming_callback is None
=> fix: Fix streaming_callback serialization in AmazonBedrockChatGenerator

integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/retriever.py
Small improvements including:
- fixing not working examples
- removing defaults from docstrings (consistently with the codebase)
=> Qdrant - improve docstrings for retrievers

.github/workflows/CI_readme_sync.yml
Sync docs with all the Haystack versions available on Readme.
=> chore: sync integrations docs with all the available Haystack versions

integrations/pgvector/src/haystack_integrations/document_stores/pgvector/filters.py
Without this fix code can not be run on Py3.8 although it's in list of supported versions
=> Type hints in pgvector document store updated for 3.8 compability

integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_document_embedder.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_sparse_document_embedder.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_sparse_text_embedder.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_text_embedder.py, integrations/fastembed/tests/test_fastembed_sparse_text_embedder.py
`FastembedTextEmbedder` can only accept and process a string at a time.
`batch_size` parameter is practically ignored and misleading -> I'm removing it.
(Other minor docstrings improvements)
=> `FastembedSparseTextEmbedder` - remove `batch_size`

.github/workflows/CI_readme_sync.yml
Pass the Haystack docs version on readme when generating docs.
=> chore: pass the haystack docs version when generating docs

.github/workflows/langfuse.yml
* Fixes langfuse nightly tests
The only test, so far, we have is integration test so let's run all unit/integration tests
Resolves https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8962156252
=> fix: Fix langfuse nightly tests

integrations/astra/pyproject.toml, integrations/astra/tests/test_document_store.py
Fixes nightly tests https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8977420765/job/24656141167
Unit tests should not depend on actual authentication, this PR mocks the env vars needed.
=> fix: make unit tests pass

.github/workflows/nvidia.yml, integrations/nvidia/pyproject.toml, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/_nim_backend.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/_nvcf_backend.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/document_embedder.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/text_embedder.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/truncate.py, integrations/nvidia/src/haystack_integrations/components/generators/nvidia/_nim_backend.py, integrations/nvidia/src/haystack_integrations/components/generators/nvidia/_nvcf_backend.py, integrations/nvidia/src/haystack_integrations/components/generators/nvidia/generator.py, integrations/nvidia/tests/test_document_embedder.py, integrations/nvidia/tests/test_generator.py, integrations/nvidia/tests/test_text_embedder.py
Fixes #696.
This PR updates both Nvidia generator and embedders to support the new [API catalog endpoints](https://build.nvidia.com).
These new endpoints require a different API key from the previous ones so I opted to use an `NVIDIA_CATALOG_API_KEY` env var in tests to differentiate it from the previous one.
=> Update Nvidia integration to support new endpoints

.github/workflows/langfuse.yml, integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py, integrations/langfuse/tests/test_langfuse_span.py, integrations/langfuse/tests/test_tracer.py
- Updates LangfuseSpan to use `ChatMessage.to_openai_format` from Haystack 2.1.0
- Add unit tests for internal classes
- Adds brief pydocs to internal classes
=> chore: Use ChatMessage to_openai_format, update unit tests, pydocs

integrations/anthropic/pydoc/config.yml, integrations/langfuse/pydoc/config.yml, integrations/nvidia/pydoc/config.yml, integrations/pgvector/pydoc/config.yml
Pushing minor changes to those integration pydocs which are missing in Haystack documentation –– to force the new workflow.
=> docs: add missing api references

integrations/astra/src/haystack_integrations/document_stores/astra/astra_client.py
In view of upcoming changes in the Astra DB Data API, this PR explicitly sets a projection every time a `find` command is executed, in order to ensure all necessary fields of the document are returned by the API.
=> [Astra DB] Explicit projection when reading from Astra DB

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/adapters.py
ALLOWED_PARAMS has `max_tokens` but generation_kwargs was using `max_gen_len`.
Closes Issue : https://github.com/deepset-ai/haystack-core-integrations/issues/741
=> Fix: max_tokens typo in Mistral Chat

integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py, integrations/qdrant/tests/test_document_store.py
fixes #747 
Move the qdrant client access to the `client` property and defer database connection to the first usage of `self.client`
See the tracking issue for the details
=> feat: defer database connection to the first usage

integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py, integrations/cohere/src/haystack_integrations/components/generators/cohere/generator.py, integrations/cohere/tests/test_cohere_generators.py
- fixes failing CI after the `generate` API was discontinued by Cohere
Make the old generator a wrapper around the chat generator to ensure backward compatibility
Unit+integration tests
=> fix: remove support for generate API

integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py
As mentioned in the discord with @masci, making the get_distance and recreate_collection functions public. I also think the on_disk and use_sparse_embeddings could be optional parameters if there is no reason against this. 
I've also replaced the deprecated recreate_collection function and used the collection_exists check instead of the try-catch. Let me know if there is something that i've overlooked doing this.
unit tests, manual verification
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR …
=> feat: make get_distance and recreate_collection public, replace deprecated recreate_collection function

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_document_store.py
- fixes #749 
- Create a `self.client` property returning the client
- Move database connection logic into the property, so it's done when needed and not in the constructor
Unit tests
=> feat: defer the database connection to when it's needed

show_unreleased.sh
- fixes the problem of not knowing if an integration has changes in `main` that were not released yet.
Add a `./show_unreleased.sh` command at the root of the repo that will:
- show the diff of the changes that were not yet released
- show nothing if the integration has no changes in `main` that need to be released
Manually tested on a bunch of integrations, e.g.:
```
./show_unreleased.sh chroma
-> no output, means all good
```
- I've used …
=> ci: add `diff` command

integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py
- fixes failing CI
Not sure where this comes from, but in absence of filters we used to pass `None` in the query pipeline and now it raises an error. Changed to passing an empty dict instead.
=> fix: pass empty dict to filter instead of None

integrations/chroma/pyproject.toml
https://github.com/deepset-ai/haystack/actions/runs/9314071721/job/25642900567
Our current integration is only compatible with `chromadb>=0.5.0`, where the support for Ollama was introduced
pin `chromadb>=0.5.0`
=> chore: pin chromadb>=0.5.0

integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py, integrations/ollama/tests/test_chat_generator.py
Add streaming support for the OllamaChatGenerator class. I basically copied and adapted the logic from OllamaGenerator.
I integrated it into my application and tested it manually with various models on Ollama.
=> feat: Add streaming support to OllamaChatGenerator

integrations/nvidia/tests/test_document_embedder.py, integrations/nvidia/tests/test_generator.py, integrations/nvidia/tests/test_text_embedder.py
README.md says `Note: integration tests will be skipped unless the env var NVIDIA_API_KEY is set.`
with this MR, the statement is now true for all cases.
=> fix: align tests and docs on NVIDIA_API_KEY (instead of NVIDIA_CATALOG_API_KEY)

integrations/google_ai/tests/generators/chat/test_chat_gemini.py, integrations/google_ai/tests/generators/test_gemini.py
Google must have updated their `google-generativeai` library. And changed some enum values, this broke some serialization tests.
This PR fixes those failing tests.
=> Fix Google AI integration tests

.github/workflows/unstructured.yml, integrations/unstructured/pyproject.toml
Unstructured library doesn't support Python 3.8 as can be seen in [latest nightly test failure](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/9376015101/job/25815211259#step:9:58).
This is also made clear by [their `setup.py`](https://github.com/Unstructured-IO/unstructured/blob/fdb27378cb7fc25bcae66bf52bcfc16e051a42a8/setup.py#L96).
=> chore: Drop support for Python 3.8 for Unstructured integration

integrations/google_ai/tests/generators/chat/test_chat_gemini.py, integrations/google_ai/tests/generators/test_gemini.py
Tests for Google AI integration are not being skipped in PRs opened from forks. 
This should fix it [this kind of failures](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/9385898114/job/25845160481).
=> test: Fix tests skipping for Google AI integration

.github/workflows/amazon_bedrock.yml, integrations/amazon_bedrock/tests/conftest.py, integrations/amazon_bedrock/tests/test_chat_generator.py
- fixes #689
- when running from a fork, skip AWS authentication and integration tests
- slightly unrelated: also skip Mistral test if `HF_API_TOKEN` env var is not set (we can remove this once #732 is fixed)
CI: this PR comes from a fork. …
=> test: Amazon Bedrock - skip integration tests from forks

integrations/cohere/src/haystack_integrations/components/generators/cohere/generator.py
This Generator is a mere wrapper of the corresponding ChatGenerator but it is useful for simple use cases and we want to keep it.
Remove the warning message, which was not clear to users.
=> chore: `CohereGenerator` - remove warning about `generate` API

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/adapters.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py, integrations/amazon_bedrock/tests/test_generator.py
- model support update for Amazon Bedrock
- added support for
- Claude V3
- Llama3
- Command R
- added tests
- using messages API by default for Claude models is fine as all models on Bedrock support it (we did the same in Haystack v1 already) …
=> feat: support Claude v3, Llama3 and Command R models on Amazon Bedrock

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py
- fixes #816 
- Add support for `AzureOpenAIGenerator` and `AzureOpenAIChatGenerator`
- The Azure generators provide the same response payload as OpenAI, so no additional logic is needed
=> feat: add support for Azure generators

integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_document_store.py
- fixes #810 
A FilterError is raised when using legacy filters or used with other components like `CacheChecker`. 
This is because of the missing `convert(filters)` in `WeaviateDocumentStore`.
This PR adds the `convert` function.
- Added test
- Resolves #810 after the applying the changes in the PR
N/A …
=> fix: weaviate filter error

integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py, integrations/pgvector/tests/test_document_store.py, integrations/pgvector/tests/test_retrievers.py
- fixes #812 
Added the functionality to use custom names for indexes on pgvector document store.
Unit tests, integration tests and manually verification.
Feel free to give any feedback, this is my first PR to this project.
=> feat: add customizable index names for pgvector

integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py
- fixes #764 
Added the missing doc strings in QdrantDocumentStore class to generate documentation for API reference.
Existing unit tests
NA
=> doc: added docstrings for QdrantDocumentStore

integrations/amazon_bedrock/pyproject.toml, integrations/amazon_sagemaker/pyproject.toml, integrations/anthropic/pyproject.toml, integrations/astra/pyproject.toml, integrations/chroma/pyproject.toml, integrations/cohere/pyproject.toml, integrations/deepeval/pyproject.toml, integrations/elasticsearch/pyproject.toml, integrations/fastembed/pyproject.toml, integrations/google_ai/pyproject.toml, integrations/google_vertex/pyproject.toml, integrations/gradient/pyproject.toml, integrations/instructor_embedders/pyproject.toml, integrations/jina/pyproject.toml, integrations/langfuse/pyproject.toml, integrations/llama_cpp/pyproject.toml, integrations/mistral/pyproject.toml, integrations/mongodb_atlas/pyproject.toml, integrations/nvidia/pyproject.toml, integrations/ollama/pyproject.toml, integrations/opensearch/pyproject.toml, integrations/optimum/pyproject.toml, integrations/pgvector/pyproject.toml, integrations/pinecone/pyproject.toml, integrations/qdrant/pyproject.toml, integrations/ragas/pyproject.toml, integrations/unstructured/pyproject.toml, integrations/weaviate/pyproject.toml
- fixes #799 
- Introduce `pytest-rerunfailures` to retry test execution and possibly reduce failures due to network connectivity
- To minimize the impact of this PR, add the retry logic to any `hatch run test` script. The plugin supports a more granular configuration but in this PR I want to avoid a case-by-case strategy
- To avoid timing out, we now run the tests with `-x`, so we exit immediately after the first retry. Several tests might fail for the same reason, so we avoid piling up too many retries before exiting.
- (unrelated) reformatted the toml files
CI
- Please let me know if you agree with the `-x` strategy
- I set a 30 seconds delay in-between retries, I'm open to change that number
- Also let me know if 3 attempts is ok …
=> ci: retry tests to reduce flakyness

integrations/amazon_bedrock/pyproject.toml, integrations/amazon_sagemaker/pyproject.toml, integrations/anthropic/pyproject.toml, integrations/astra/pyproject.toml, integrations/chroma/pyproject.toml, integrations/cohere/pyproject.toml, integrations/deepeval/pyproject.toml, integrations/elasticsearch/pyproject.toml, integrations/fastembed/pyproject.toml, integrations/google_ai/pyproject.toml, integrations/google_vertex/pyproject.toml, integrations/gradient/pyproject.toml, integrations/instructor_embedders/pyproject.toml, integrations/jina/pyproject.toml, integrations/langfuse/pyproject.toml, integrations/llama_cpp/pyproject.toml, integrations/mistral/pyproject.toml, integrations/mongodb_atlas/pyproject.toml, integrations/nvidia/pyproject.toml, integrations/ollama/pyproject.toml, integrations/opensearch/pyproject.toml, integrations/optimum/pyproject.toml, integrations/pgvector/pyproject.toml, integrations/qdrant/pyproject.toml, integrations/ragas/pyproject.toml, integrations/unstructured/pyproject.toml, integrations/weaviate/pyproject.toml
- fixes #844 
- Tests are failing because some integrations do not depend on `pytest-rerunfailures`, introduced in #836 to retry failing tests -> I added the dependency
- #836 added the config to retry tests to hatch `test` script, while most of our tests run via hatch `test-cov` script -> I added the same config to hatch `test-cov` script. I also tried to find a better way to avoid this config duplication, but had no luck.
CI
- I've used …
=> ci: install `pytest-rerunfailures` where needed; add retry config to `test-cov` script

integrations/pinecone/pyproject.toml
Pinecone tests have been overlooked in recent work on automatically retrying failing tests (#836 and #845).
(tests failed and not retried: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/9654201625)
Add retry configurations to existing ones in Pinecone test scripts
CI
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, …
=> ci: add retry config to Pinecone test

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_bm25_retriever.py, integrations/opensearch/tests/test_document_store.py, integrations/opensearch/tests/test_embedding_retriever.py
- fixes having left-over indexes due to unintended index creations
- add `create_index` init param to disable automatic index creation
- add `create_index()` method for more control over (manually) creating indexes
- added integration test …
=> feat: add create_index option to OpenSearchDocumentStore

integrations/opensearch/pyproject.toml, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/bm25_retriever.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/embedding_retriever.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_bm25_retriever.py, integrations/opensearch/tests/test_document_store.py, integrations/opensearch/tests/test_embedding_retriever.py
- fixes support for custom OpenSearch queries
- add `custom_query` param
- we support ~`str`~ and `dict` as custom_query: the former is easier to use with YAML, the latter is easier to use with ~python~JSON
- added tests
- What do I mean with easier with YAML? See how a already properly formated OpenSearch query in JSON can be simply copied into yaml under https://docs.cloud.deepset.ai/docs/opensearch-queries-for-boosting-retrieval#used-in-a-pipeline  …
=> feat: add custom_query param to OpenSearch retrievers

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/adapters.py, integrations/amazon_bedrock/tests/test_chat_generator.py
- fixes #732
If AmazonBedrockChatGenerator is used with a mistral model while there is no env var HF_TOKEN, we now use a fallback tokenizer model that is not gated and has similar tokenization behavior: "NousResearch/Llama-2-7b-chat-hf". We log a warning if the fallback tokenizer is used.
This PR doesn't change the behavior if AmazonBedrockChatGenerator is used with a mistral model while an env var HF_TOKEN is set and the user has access to "mistralai/Mistral-7B-Instruct-v0.1". The user might have access to the model either because it's cached or because it can be downloaded from the hub.
* Added two new unit tests.
* I checked that tokenization with "NousResearch/Llama-2-7b-chat-hf" and "mistralai/Mistral-7B-Instruct-v0.1" yields a similar number of tokens on 20 SQuAD example documents. …
=> feat: Use non-gated tokenizer as fallback for mistral in AmazonBedrockChatGenerator

integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/bm25_retriever.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/embedding_retriever.py, integrations/opensearch/tests/test_bm25_retriever.py, integrations/opensearch/tests/test_embedding_retriever.py
- fixes serialization of the recently added `custom_query` param for OpenSearch retrievers
- added param to serialization
- adjusted tests
=> fix: serialization for custom_query in OpenSearch retrievers

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_document_store.py
- legacy filters have not been supported so far with OpenSearchDocumentStore except for `filter_documents()`
- add support for legacy filters to `_bm25_retrieval()` and `_embedding_retrieval()`
=> fix: support legacy filters with OpenSearchDocumentStore

integrations/unstructured/pyproject.toml
- fixes errors like this: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/9708777441/job/26796197528
A new version of unstructured has been released and for some reason, they did not include `psutil`.
I've added it to dependencies.
CI …
=> build: add `psutil` dependency to Unstructured integration

integrations/opensearch/pyproject.toml, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/bm25_retriever.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/embedding_retriever.py, integrations/opensearch/tests/test_bm25_retriever.py, integrations/opensearch/tests/test_embedding_retriever.py
In a hybrid retrieval setting, it can occurr that one retriever raises an error (e.g. due to a too long query for BM25), but the other is fine. In such cases it's better to return the results of the working retriever and ignore the failed ones instead of getting no results at all.
- add `raise_on_failure` param to OpenSearch retrievers
- added tests …
=> feat: add raise_on_failure param to OpenSearch retrievers

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py, integrations/amazon_bedrock/tests/test_generator.py
- fixes #785 
- fixes #783 
- Added 'truncate' parameter to initialization method. 
- Added kwargs in serialization method
Updated unit tests
Integration tests
NA
=> feat: made truncation optional for BedrockGenerator

integrations/optimum/src/haystack_integrations/components/embedders/optimum/_backend.py
HF fixed a typo in a minor release.
=> fix: Fix typo in the `ORTModel.inputs_names` field to align with upstream

integrations/astra/src/haystack_integrations/components/retrievers/astra/retriever.py, integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py, integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/bm25_retriever.py, integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/embedding_retriever.py, integrations/mongodb_atlas/src/haystack_integrations/components/retrievers/mongodb_atlas/embedding_retriever.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/bm25_retriever.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/embedding_retriever.py, integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/embedding_retriever.py, integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/keyword_retriever.py, integrations/pinecone/src/haystack_integrations/components/retrievers/pinecone/embedding_retriever.py, integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/retriever.py, integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/bm25_retriever.py, integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/embedding_retriever.py
- Fixes pydoc text mistake for all retrievers
- Do a search for `chosen at document store initialization` - ensure it is replaced by `chosen at retriever initialization`
=> chore: Minor retriever pydoc fix

integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py, integrations/chroma/tests/test_document_store.py
- fixes #462 
Update `_query_result_to_documents` to also run without metadata 
Added a unit test
NA
=> fix: Allow search in ChromaDocumentStore without metadata

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py
- fixes #855
Fixes the tests failures by correctly declaring the function schema using a new utility function `FunctionDeclaration.from_function().
I ran tests locally.
N/A
=> Fix Google AI tests failing

integrations/qdrant/src/haystack_integrations/document_stores/qdrant/filters.py, integrations/qdrant/tests/test_filters.py
- fixes #846 
Previous function creates a unnecessary nested structure of Filters causing logic errors. Then uses the `squeeze_filter` to simplify the structure which wrongly deletes some parts of filters.
I tried implementing a solution which handles different cases of filters while creating thus no need to squeeze it afterwards.
Created four examples for manual testing of converted filters and their results
Existing unit and integration tests
**Example comparison**
Haystack filter
```
filter_criteria = {
"operator": "AND",
"conditions": [
{"field": "meta.file_name", "operator": "in", "value": ["file1", "file2"]},
{
"operator": "OR",
"conditions": [
{"field": "meta.classification.details.category1", "operator": ">=", "value": 0.85},
{"field": "meta.classification.details.category2", …
```
=> fix: errors in convert_filters_to_qdrant

integrations/astra/src/haystack_integrations/components/retrievers/astra/retriever.py, integrations/astra/tests/test_retriever.py
=> fix: `Astra` - Fallback to default filter policy when deserializing retrievers without the init parameter

integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py, integrations/chroma/tests/test_retriever.py
=> fix: `Chroma` - Fallback to default filter policy when deserializing retrievers without the init parameter

integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/retriever.py, integrations/qdrant/tests/test_retriever.py
=> fix: `qdrant` - Fallback to default filter policy when deserializing retrievers without the init parameter

integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py, integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/bm25_retriever.py, integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/embedding_retriever.py, integrations/elasticsearch/tests/test_bm25_retriever.py, integrations/elasticsearch/tests/test_embedding_retriever.py
=> fix: `ElasticSearch` - Fallback to default filter policy when deserializing retrievers without the init parameter

integrations/pinecone/src/haystack_integrations/components/retrievers/pinecone/embedding_retriever.py, integrations/pinecone/tests/test_embedding_retriever.py
=> fix: `pinecone` - Fallback to default filter policy when deserializing retrievers without the init parameter

integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py, integrations/chroma/tests/test_document_store.py
- fixes #891
Adds a `metadata` parameter do ChromaDocumentStore to be passed directly to chroma client’s `create_collection` method.
integration tests
=> feat: Add metadata parameter to ChromaDocumentStore.

integrations/mongodb_atlas/src/haystack_integrations/components/retrievers/mongodb_atlas/embedding_retriever.py, integrations/mongodb_atlas/tests/test_retriever.py
=> fix: `Mongo` - Fallback to default filter policy when deserializing retrievers without the init parameter

integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/embedding_retriever.py, integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/keyword_retriever.py, integrations/pgvector/tests/test_retrievers.py
=> fix: `PgVector` - Fallback to default filter policy when deserializing retrievers without the init parameter

integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/bm25_retriever.py, integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/embedding_retriever.py, integrations/weaviate/tests/test_bm25_retriever.py, integrations/weaviate/tests/test_embedding_retriever.py
=> fix: `weaviate` - Fallback to default filter policy when deserializing retrievers without the init parameter 

integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py, integrations/chroma/tests/test_document_store.py
- fixes #904
- It is important because starting from 2.3.0 we are automatically populating `meta` with `_split_overlap` when using the `DocumentSplitter` (https://github.com/deepset-ai/haystack/pull/7933). `_split_overlap` is a list, unsupported by Chroma.
- Check if the value of each item in `meta` has a type supported in Chroma. If not, discard it and emit a warning.
CI, new test. …
=> fix: `ChromaDocumentStore` - discard `meta` items when the type of their value is not supported in Chroma

integrations/pinecone/tests/conftest.py
- fixes https://github.com/deepset-ai/haystack-core-integrations/actions/runs/10032414872/job/27724082100
- the imported `NotFoundException` is available in different modules depending on the `pinecone-client` version
In case the exception import fails, try another import
CI …
=> chore: Pinecone - fix import in conftest

integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py
- Weaviate released weaviate-client 4.7.0 library on 23.7.24 - this version started failing our CI tests.
- Seems like weaviate client removed internal method _get_all and introduced list_all. 
- This fix uses list_all
=> fix: Weaviate: Use collections.list_all instead of collections._get_all

integrations/ragas/pyproject.toml, integrations/ragas/src/haystack_integrations/components/evaluators/ragas/metrics.py, integrations/ragas/tests/test_evaluator.py
- this metric was removed in ragas [0.1.11](https://github.com/explodinggradients/ragas/releases/tag/v0.1.11). (I cannot find much explanation about this removal.)
- CI failures: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/10050341672
- remove the metric from the Haystack integration
CI
I don't know if it is preferable to handle it differently. Let me know your thoughts... …
=> chore: Ragas - remove context relevancy metric

integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/document_embedder.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/text_embedder.py, integrations/nvidia/src/haystack_integrations/components/generators/nvidia/generator.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/utils.py, integrations/nvidia/tests/test_base_url.py, integrations/nvidia/tests/test_document_embedder.py, integrations/nvidia/tests/test_generator.py, integrations/nvidia/tests/test_text_embedder.py
Expected url format: **http://host:port**
- Accept valid urls(/v1, ../v1/embeddings .../v1/completions .../v1/rankings) with UserWarning
- Error handling in case url does not follow `http://host:port` or above formats
- For NvidiaDocumentEmbedder and NvidiaTextEmbedder `/v1` route is allowed and following warning is given for `v1/embeddings ` endpoint
UserWarning: Expected format is 'http://host:port/'. Rest is ingnored.
- For NvidiaGenerator `/v1` route is allowed and following warning is given for `v1/chat/completions ` endpoint
UserWarning: Expected format is 'http://host:port/'. Rest is ingnored.
- All other routes are rejected with ValueError:
Base URL path is not recognized. Expected format is 'http://host:port/'. Rest is ingnored.
cc: @mattf @dglogo @sumitkbh
=> Raise warning for base_url ../embeddings .../completions .../rankings

integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py
Unnecessary exposure of resolved Mongodb connection string, making it prone to leaks.
Avoid storing the connection string value.
Ran the existing tests
=> fix: remove exposure of connection_string

integrations/llama_cpp/pyproject.toml
- fixes #938 
Latest version of llama-cpp-python has bugs.
Pin the dependency for llama-cpp-python to an older version 
Ran the tests
=> fix: pin llama-cpp-python to an older version

integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/chat/chat_generator.py, integrations/llama_cpp/tests/test_chat_generator.py
part of https://github.com/deepset-ai/haystack/issues/8144
Create a utility function and use it instead of `to_openai_format`
CI, new test
Tests will fail due to #938
=> refactor: introduce `_convert_message_to_llamacpp_format` utility function

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py
=> Docs: Update GoogleChatGenerator docstrings

integrations/llama_cpp/pyproject.toml
- related to #938
The existing bug on `llama-cpp-python` has been fixed in 0.2.87.
I'm pinning `llama-cpp-python>=0.2.87`
CI
=> chore: pin `llama-cpp-python>=0.2.87`

integrations/anthropic/example/documentation_rag_with_claude.py
- Properly use ChatPromptBuilder init with documents variable
- Inject document content into prompt not just str of the document
- Verify component connections
- Verify output is based on fetched document
=> chore: Update Anthropic example, use ChatPromptBuilder properly

integrations/jina/pyproject.toml, integrations/jina/tests/test_document_embedder.py, integrations/jina/tests/test_ranker.py, integrations/jina/tests/test_text_embedder.py
- fix ruffing  after ruff 0.6.0 has been released
- exclude tests from ruffing
=> chore: Jina - ruff update, don't ruff tests

integrations/chroma/example/example.py, integrations/chroma/pyproject.toml, integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py, integrations/chroma/tests/test_document_store.py, integrations/chroma/tests/test_retriever.py
- fix ruffing after ruff 0.6.0 has been released
- exclude tests from ruff
=> chore: Chroma - ruff update, don't ruff tests

integrations/langfuse/pyproject.toml, integrations/langfuse/src/haystack_integrations/components/connectors/langfuse/langfuse_connector.py
=> chore: langfuse - ruff update, don't ruff tests

integrations/weaviate/pyproject.toml, integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/bm25_retriever.py, integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/embedding_retriever.py, integrations/weaviate/tests/test_auth.py, integrations/weaviate/tests/test_bm25_retriever.py, integrations/weaviate/tests/test_document_store.py, integrations/weaviate/tests/test_embedding_retriever.py
=> chore: weaviate - ruff update, don't ruff tests

integrations/ollama/examples/chat_generator_example.py, integrations/ollama/examples/embedders_example.py, integrations/ollama/examples/generator_example.py, integrations/ollama/pyproject.toml, integrations/ollama/tests/test_chat_generator.py, integrations/ollama/tests/test_document_embedder.py, integrations/ollama/tests/test_generator.py, integrations/ollama/tests/test_text_embedder.py
=> chore: ollama - ruff update, don't ruff tests

integrations/mongodb_atlas/examples/example.py, integrations/mongodb_atlas/pyproject.toml, integrations/mongodb_atlas/src/haystack_integrations/components/retrievers/mongodb_atlas/embedding_retriever.py, integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py, integrations/mongodb_atlas/tests/test_document_store.py, integrations/mongodb_atlas/tests/test_embedding_retrieval.py, integrations/mongodb_atlas/tests/test_retriever.py
**Note:**
We need to integrate https://github.com/deepset-ai/haystack-core-integrations/pull/971 first
=> chore: mongo - ruff update, don't ruff tests

integrations/pgvector/examples/embedding_retrieval.py, integrations/pgvector/examples/hybrid_retrieval.py, integrations/pgvector/pyproject.toml, integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/embedding_retriever.py, integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/keyword_retriever.py, integrations/pgvector/tests/conftest.py, integrations/pgvector/tests/test_document_store.py, integrations/pgvector/tests/test_embedding_retrieval.py, integrations/pgvector/tests/test_filters.py, integrations/pgvector/tests/test_keyword_retrieval.py, integrations/pgvector/tests/test_retrievers.py
- fix ruffing after ruff 0.6.0 has been released
- exclude tests examples from ruff
**Note:** 
We first need to merge https://github.com/deepset-ai/haystack-core-integrations/pull/970
=> chore: pgvector ruff update, don't ruff tests

integrations/nvidia/pyproject.toml, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/document_embedder.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/text_embedder.py, integrations/nvidia/src/haystack_integrations/components/generators/nvidia/generator.py
Fix lints broken by `ruff==0.6`.
CI
=> fix: Lints in `nvidia-haystack`

integrations/fastembed/examples/example.py, integrations/fastembed/examples/sparse_example.py, integrations/fastembed/pyproject.toml, integrations/fastembed/tests/test_fastembed_document_embedder.py, integrations/fastembed/tests/test_fastembed_sparse_document_embedder.py, integrations/fastembed/tests/test_fastembed_sparse_text_embedder.py, integrations/fastembed/tests/test_fastembed_text_embedder.py
=> chore: fastembed - ruff update, don't ruff tests

integrations/elasticsearch/pyproject.toml, integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/bm25_retriever.py, integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/embedding_retriever.py, integrations/elasticsearch/tests/test_bm25_retriever.py, integrations/elasticsearch/tests/test_document_store.py, integrations/elasticsearch/tests/test_embedding_retriever.py, integrations/elasticsearch/tests/test_filters.py
=> chore: elasticsearch - ruff update, don't ruff tests

integrations/langfuse/src/haystack_integrations/components/connectors/langfuse/langfuse_connector.py
None
I propose to add a link to Langfuse to help people figure out what Langfuse actually is when browsing the api reference.
I did not test it
None
=> docs: add link to langfuse in LangfuseConnector

integrations/llama_cpp/examples/rag_pipeline_example.py, integrations/llama_cpp/pyproject.toml, integrations/llama_cpp/tests/test_chat_generator.py, integrations/llama_cpp/tests/test_generator.py
=> chore: lamma_cpp - ruff update, don't ruff tests

integrations/qdrant/examples/embedding_retrieval.py, integrations/qdrant/pyproject.toml, integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/retriever.py, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/migrate_to_sparse.py, integrations/qdrant/tests/test_converters.py, integrations/qdrant/tests/test_dict_converters.py, integrations/qdrant/tests/test_document_store.py, integrations/qdrant/tests/test_filters.py, integrations/qdrant/tests/test_legacy_filters.py, integrations/qdrant/tests/test_retriever.py
=> chore: qdrant - ruff update, don't ruff tests

integrations/opensearch/pyproject.toml, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/bm25_retriever.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/embedding_retriever.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_auth.py, integrations/opensearch/tests/test_bm25_retriever.py, integrations/opensearch/tests/test_document_store.py, integrations/opensearch/tests/test_embedding_retriever.py, integrations/opensearch/tests/test_filters.py
=> chore: opensearch - ruff update, don't ruff tests

integrations/instructor_embedders/pyproject.toml, integrations/instructor_embedders/tests/test_instructor_backend.py, integrations/instructor_embedders/tests/test_instructor_document_embedder.py, integrations/instructor_embedders/tests/test_instructor_text_embedder.py
=> chore: instructor-embedders - ruff update, don't ruff tests

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py
- fixes https://github.com/deepset-ai/haystack/issues/8240
Remove usage of deprecated code (replacement code published in Haystack 2.4.0).
CI
=> refactor: Remove usage of deprecated `ChatMessage.to_openai_format`

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/adapters.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/amazon_bedrock/tests/test_chat_generator.py
- fixes #7687
- Something change in AmazonBedrock and the PR I merged had no effect
unit tests, integration tests, manual verification, instructions for manual tests
- `generators/amazon_bedrock/chat/adapters.py`is at 59%
- `generators/amazon_bedrock/chat/chat_generator.py` is at 51%
```
cmd [1] | coverage run -m pytest -m integration --reruns 3 --reruns-delay 30 -x
============================= test session starts ==============================
platform linux -- Python 3.9.19, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/runner/work/haystack-core-integrations/haystack-core-integrations/integrations/amazon_bedrock
configfile: pyproject.toml
plugins: rerunfailures-14.0, anyio-4.4.0
collected 152 items / 140 deselected / 12 selected
tests/test_chat_generator.py::TestMistralAdapter::test_default …
```
=> fix: normalising ChatGenerators output

integrations/amazon_bedrock/CHANGELOG.md, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/adapters.py, integrations/amazon_bedrock/tests/test_chat_generator.py
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/975
Allow the tools kwargs for AWS Bedrock Anthropic models because it is listed as valid here: https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html
I did not, as it's a tiny fix and I didn't really have time to setup the whole testing process. …
=> fix(Bedrock): allow tools kwargs for AWS Bedrock Claude model

integrations/pinecone/src/haystack_integrations/document_stores/pinecone/document_store.py, integrations/pinecone/tests/test_document_store.py
- fixes https://github.com/deepset-ai/haystack/issues/8181
- fixes #919
- unit tests, integration tests and manual verification
=> fix: skip unsupported meta fields in PineconeDB

integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/document_embedder.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/text_embedder.py, integrations/nvidia/src/haystack_integrations/components/generators/nvidia/generator.py, integrations/nvidia/tests/conftest.py, integrations/nvidia/tests/test_base_url.py, integrations/nvidia/tests/test_document_embedder.py, integrations/nvidia/tests/test_generator.py, integrations/nvidia/tests/test_text_embedder.py
Improved embedding models are available. Update the default model to nvidia/nv-embedqa-e5-v5.
Additionally, tests for other available models.
`NVIDIA_API_KEY=... hatch run test`
This may be a breaking change if someone is specifically relying on the NV-Embed-QA default. …
=> feat: update default embedding model to nvidia/nv-embedqa-e5-v5

integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py, integrations/qdrant/tests/test_document_store.py
This PR updates the Qdrant integration to use the new [Query API](https://qdrant.tech/blog/qdrant-1.10.x/) that supersedes the search API.
It also support server-side fusion of the hybrid results.
=> refactor: Use Qdrant's Query API

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py, integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py, integrations/google_ai/tests/generators/test_gemini.py
- fixes #1002 
Add `streaming_callback` to `init` and `run` methods of `GoogleAIGeminiGenerator` and `GoogleAIGeminiChatGenerator`.
- Updated and ran existing unit tests
- Added a test for streaming
- Tested locally on my system
Similar to the PR for VertexAI: [1014](https://github.com/deepset-ai/haystack-core-integrations/pull/1014) 
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR …
=> Enable streaming in GoogleAIGemini

integrations/nvidia/src/haystack_integrations/components/rankers/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/components/rankers/nvidia/ranker.py, integrations/nvidia/src/haystack_integrations/components/rankers/nvidia/truncate.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/nim_backend.py, integrations/nvidia/tests/test_base_url.py, integrations/nvidia/tests/test_ranker.py
NVIDIA NIMs (hosted on https://build.nvidia.com and downloadable) support reranking models. This adds an NvidiaRanker component to access those models.
1. should the input documents be mutated to add a score?
2. the ranker endpoints are not standardized, so i introduced an endpoint arg to rank(). an alternative is to refactor all components to pass the full inference endpoint to the backend. …
=> feat: add NVIDIA NIM ranker support

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py, integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py, integrations/google_ai/tests/generators/test_gemini.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/gemini.py, integrations/google_vertex/tests/test_gemini.py
- part of fixing #1024 
Replaces the use of deprecated `gemini-pro-vision` and `gemini-ultra` from code and docstrings.
Ran existing tests
Tested locally
=> fix: remove the use of deprecated gemini models

integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/bm25_retriever.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/embedding_retriever.py
=> docs: Update opensearch retriever docstrings

integrations/amazon_bedrock/tests/test_chat_generator.py, integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py, integrations/ollama/examples/chat_generator_example.py
- fixes #1026 
- Updated the role assigned to model responses from `system` to `assistant` for both `GoogleGeminiChatGenerator` and `VertexAIGeminiChatGenerator`.
- Reviewed and verified consistency across other generators to ensure correct role assignment.
Ran existing tests …
=> fix: chat roles for model responses in chat generators

integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py
The `QdrantDocumentStore` did not properly implement the `DocumentStore` protocol.
- fixes #1039
Ensure that the `write_documents` and `delete_documents` methods match the type expectations of the `DocumentStore` protocol.
Manual verification. Can't test via hatch, as it's currently trashed on my system.
This is technically a breaking change, because it changes the name of the `ids` argument in `delete_documents` to `document_ids`.
- I've …
=> fix!: fix type errors in `QdrantDocumentStore`; rename `ids` (parameter of `delete_documents`) to `document_ids`

integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/truncate.py, integrations/nvidia/tests/test_embedding_truncate_mode.py
- fixes #1027 
Add missing `NONE` member to `EmbeddingTruncateMode`
Ran existing test.
Ran test locally.
Add unit test for `EmbeddingTruncateMode`
Implemented [`_missing_`](https://docs.python.org/3/library/enum.html#enum.Enum._missing_) for `EmbeddingTruncateMode`. Reasoning is to ensure that a ValueError with message is raised consistently, whether a user instantiates the enum directly or through the `from_str()` method. I tested instantiation both ways in the unit test.
- I added unit …
=> fix: Missing Nvidia embedding truncate mode

integrations/weaviate/pyproject.toml
- weaviate-client 3 doesn't include the `weaviate.collections` package. This means that client version is not compatible with this integration
=> fix: restrict weaviate-client

integrations/google_vertex/pyproject.toml
There is a [reproducible bug](https://github.com/googleapis/proto-plus-python/issues/483) that causes serialization to fail on Windows for Gemini Components in Google Vertex integration.
Pinning the version of `protobuf` to `<5.28` seems to solve the issue
This usually fails in CI on Windows, I don't have a Windows machine at the ready so CI will do.
I'll open a tracking issue to unpin this as soon as the [original bug 
](https://github.com/googleapis/proto-plus-python/issues/483) is fixed.
- I have updated the related issue with new insights and …
=> Ping `protobuf` to `<5.28` to fix Google Vertex Components serialization

.github/workflows/weaviate.yml, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py
- fixes #1057
- extend the existing condition to take into account also URLs ending with ".weaviate.cloud"
- replace `connect_to_wcs` (deprecated) with `connect_to_weaviate_cloud`
CI, manual test on Weaviate Cloud (before the fix, I could not connect) …
=> fix: Weaviate - fix connection issues with some WCS URLs

integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py
Fixes failed nightly run most likely due to updates in linting rules and the fix makes sense as well.
=> chore: ChromaDocumentStore lint fix

integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py, integrations/chroma/tests/test_document_store.py
- fixes CI linting errors: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/10755366118
- fix the linting error
- remove the usage of `np.array` to handle embeddings: our `embedding` is a `list` of `float`
CI, added new assertions to an existing test to verify that the returned `embedding` is a `list` of `float`
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR …
=> refactor: fix chroma linting; do not use numpy

integrations/ragas/pyproject.toml
`ragas==0.1.17` breaks our integration seemingly due to changes to expected column names for certain metrics.
CI
=> fix: Add upper-bound pin to `ragas` dependency in `ragas-haystack`

integrations/astra/src/haystack_integrations/document_stores/astra/filters.py, integrations/astra/tests/test_document_store.py
- fixes #1037 
Correctly map `id` to `_id`. 
Added integration test `TestDocumentStore.test_filter_documents_by_id`
=> fix: AstraDocumentStore filter by id

integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/retriever.py, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py, integrations/qdrant/tests/test_document_store.py, integrations/qdrant/tests/test_retriever.py
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1045
Adding the `group_by` and `group_size` parameters to Qdrant Retrievers.
See: https://qdrant.tech/documentation/concepts/hybrid-queries/#grouping and https://api.qdrant.tech/master/api-reference/search/query-points-groups
This allow to specify a maximum number of chunks to retrieve for a specific metadata value. Useful to force the Retriever to retriever for many documents instead of focusing on one.
Added new test for each retriever as well as fixing previous test like converting to dict.
The test are flaky sometimes in the number of documents retriever.
Technically it can never be more documents than `top_k * group_size`, but sometimes it's less. (I guess it can be less than `top_k`)
In the context of `group_by` …
=> feat: Qdrant - Add group_by and group_size optional parameters to Retrievers

integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py
- Removes legacy filter support in PgVector (i.e. use of `convert` from from `haystack-ai`)
- See https://github.com/deepset-ai/haystack/pull/8342 for more details
=> chore: PgVector - remove legacy filter support

integrations/pinecone/src/haystack_integrations/document_stores/pinecone/document_store.py
- Removes legacy filter support in Pinecone (i.e. use of `convert` from from `haystack-ai`)
- See https://github.com/deepset-ai/haystack/pull/8342 for more details
=> chore: Pinecone - remove legacy filter support

integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_document_store.py
- Removes legacy filter support in Weaviate (i.e. use of `convert` from from `haystack-ai`)
- See https://github.com/deepset-ai/haystack/pull/8342 for more details
- Removes outdated test
=> chore: Weaviate - remove legacy filter support

integrations/elasticsearch/CHANGELOG.md, integrations/opensearch/CHANGELOG.md, integrations/pgvector/CHANGELOG.md, integrations/pinecone/CHANGELOG.md, integrations/weaviate/CHANGELOG.md
I ran git-cliff with parameters from github CI runs that failed. Note that most changelogs have this unreleased section while elastic has the actual tag. I wasn't sure what's right here, perhaps you know - I'd guess the actual tag?
=> chore: Update changelog after removing legacy filters

integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py, integrations/cohere/tests/test_cohere_chat_generator.py
- we forgot to update Cohere LLM so that the meta token counting format matches OpenAI
- we need this format to match for general portability of generators
- we need this to turn on token counting and generation span in Langfuse integration
=> feat: Cohere LLM - adjust token counting meta to match OpenAI format

integrations/langfuse/example/chat.py, integrations/langfuse/pyproject.toml, integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py, integrations/langfuse/tests/test_tracing.py
- Adds GENERATION span (tag) Langfuse support for HuggingFace, Anthropic and Cohere LLMs
- Adds token counting (except HuggingFaceAPIChatGenerator and HuggingFaceAPIGenerator)
- Cohere support  is contingent to https://github.com/deepset-ai/haystack-core-integrations/pull/1086
- All tests were done manually in addition to updated automated integration tests.
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/887
- Screenshot below show Anthropic sonnet, other LLMs look similar
=> feat: Langfuse - support generation span for more LLMs

integrations/langfuse/tests/test_tracing.py
Attempts to resolve a nightly test [failure](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/10913148211) which seems to be stemming from Langfuse traces not being available right after the pipeline test run. Not sure if this delay will help put I don't see any other course of action at them moment. If you do please say so. 
If this test fails again tonight - I'll contact the Langfuse people for advice.
=> fix: Add delay to flush the Langfuse traces

integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py, integrations/ollama/tests/test_chat_generator.py
While working on https://github.com/deepset-ai/haystack/issues/8190, I discovered that these methods are missing.
Some parameters ('streaming_callback`) need a specific serialization.
Add the missing methods.
CI, new tests.
=> fix: Ollama Chat Generator - add missing `to_dict` and `from_dict` methods

integrations/llama_cpp/pyproject.toml
failing tests: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11043172578
pin `llama-cpp-python<0.3.0`
CI
=> fix: pin `llama-cpp-python<0.3.0`

integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py, integrations/chroma/tests/test_document_store.py
- fixes #1116 
In `search` and `search_embeddings` methods, skip filtering in case `filters=={}`.
CI, new assertion in existing test.
=> Chroma: empty filters should behave as no filters

integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/document_embedder.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/text_embedder.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/nim_backend.py, integrations/nvidia/tests/test_document_embedder.py, integrations/nvidia/tests/test_text_embedder.py
Nvidia (Nim) embedding endpoints will raise an error if empty strings are passed to them. This PR adds checks to the document and text embedder components to prevent that.
Additionally improves error handling in the Nim backend by displaying the remote response in the error message.
Unit tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, …
=> feat: Raise error when attempting to embed empty documents/strings with Nvidia embedders

integrations/langfuse/example/chat.py, integrations/langfuse/src/haystack_integrations/components/connectors/langfuse/langfuse_connector.py, integrations/langfuse/tests/test_tracing.py
- WIP, used to demonstrate a possible solution to https://github.com/deepset-ai/haystack-core-integrations/issues/916
=> Langfuse: add invocation_context to identify traces

integrations/google_vertex/pyproject.toml, integrations/google_vertex/tests/chat/test_gemini.py, integrations/google_vertex/tests/test_gemini.py
- Tests failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11171554730/job/31056492960
- to fix the tests, adopt the correct format for `FunctionDeclaration`, copied from [docs](https://cloud.google.com/vertex-ai/generative-ai/docs/reference/python/latest#function-calling).
- I also verified that our integration only works with `google-cloud-aiplatform>=1.61`, so I updated the pin
CI …
=> chore: pin `google-cloud-aiplatform>=1.61` and fix tests

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py, integrations/amazon_bedrock/tests/test_chat_generator.py, integrations/amazon_bedrock/tests/test_generator.py
more info here: https://aws.amazon.com/de/blogs/machine-learning/getting-started-with-cross-region-inference-in-amazon-bedrock/
for now this feature is only available for anthropic claude models
=> modify regex to allow cross-region inference in bedrock 

integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/embedding_backend/fastembed_backend.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_sparse_document_embedder.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_sparse_text_embedder.py, integrations/fastembed/tests/test_fastembed_backend.py, integrations/fastembed/tests/test_fastembed_sparse_document_embedder.py, integrations/fastembed/tests/test_fastembed_sparse_text_embedder.py
- fixes #1096
if qdrant/bm25 model is chosen, there is a new config available to do fine tuning
CI, added new unit tests
=> feat: introduce `model_kwargs` in Sparse Embedders (can be used for BM25 parameters)

integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py, integrations/ollama/src/haystack_integrations/components/generators/ollama/generator.py, integrations/ollama/tests/test_chat_generator.py, integrations/ollama/tests/test_generator.py
- Partially resolves #1129
Added keep_alive parameter to `OllamaGenerator` and `OllamaChatGenerator`
Ran unit tests:
```bash
hatch run test -m"not integration"
```
Manual tests:
Set keep alive to 0 and checked process consumptions.
```python
from haystack_integrations.components.generators.ollama import OllamaGenerator, OllamaChatGenerator
from haystack.dataclasses import ChatMessage, ChatRole
generator = OllamaGenerator(keep_alive=0)
replies = generator.run("Say hello").get("replies")
assert replies and replies[0].strip() != ''
generator = OllamaChatGenerator(keep_alive=0)
message = ChatMessage(content="Hello", role=ChatRole.USER, name=None)
replies = generator.run([message]).get("replies")
assert replies and replies[0].meta['done'] == True
```
The processes immediately getting unloaded …
=> feat: add `keep_alive` parameter to Ollama Generators

integrations/google_ai/pyproject.toml, integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py
Tests are failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11337043949
The conversion of function calls into dictionaries is not working properly.
- Use the chunk dictionaries to access all required attributes (instead of Google Proto objects).
- Officially drop Python 3.8 in this package (`google-generativeai` never supported it)
CI …
=> fix: make sure that streaming works with function calls - (drop python3.8)

integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/gemini.py, integrations/google_vertex/tests/chat/test_gemini.py, integrations/google_vertex/tests/test_gemini.py
- fixes #1130 
The `project` is automatically set during authentication using Google Cloud ADCs, which is required for configuration. Therefore, we can make the `project-id` optional in the component `init`.
- Ran existing tests
- Manual testing using examples …
=> fix: make "project-id" parameter optional during initialization

.github/workflows/weaviate.yml, integrations/weaviate/pyproject.toml, integrations/weaviate/tests/test_document_store.py
Weaviate tests started failing (https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11382891630/job/31667385516?pr=1142) due to a new release: https://github.com/weaviate/weaviate-python-client/releases/tag/v4.9.0
- pin the new version of the client
- drop python 3.8, as they did
- adjust the test
CI …
=> fix: compatibility with Weaviate 4.9.0

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py, integrations/amazon_bedrock/tests/test_generator.py
- fixes #1125
If `truncate` is `False`, do not initialize the `PromptHandler` (which internally downloads the tokenizer).
In the Generator, the `PromptHandler` is only used to truncate the text if needed.
CI + a new unit test.
This change only applies to `AmazonBedrockGenerator`.
I would have liked to do the same for the corresponding Chat Generator.
Unfortunately, in the Chat Generator, the `PromptHandler` (and its internal tokenizer) have 2 different purposes:
- transform messages into text with special tokens (via `tokenizer.apply_chat_template`)
- truncate the text, like in the Generator
Therefore, we cannot easily get rid of the tokenizer.
(I hope we can prioritize #977 soon: this would greatly simplify the Chat Generator.) …
=> refactor: avoid downloading tokenizer if `truncate` is `False`

integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py, integrations/elasticsearch/tests/test_document_store.py
- fixes #1149
The problem is related to the fact that we allow passing `headers` in `**kwargs`, but then we also pass a custom `headers` field containing the `user-agent`.
Extract `headers` from `**kwargs` and integrate the `user-agent` into the existing headers.
CI, new unit test
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, …
=> fix: Elasticsearch - allow passing headers

.github/workflows/CI_stale.yml
In Haystack repo, we have a [similar Stalebot](https://github.com/deepset-ai/haystack/blob/c7b898994e371e376dd3b7236620eeca05f3f463/.github/workflows/stale.yml):
if an issue is tagged with `community-triage`, it is tagged as stale after 30 days with no activity, then closed after 10 additional days.
Introduce a Stalebot workflow for core-integrations …
=> chore: introduce Stalebot

integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py
Some methods of Qdrant Document Store allow specifying the `index` parameter.
This comes from the Haystack 1.x implementation.
In 2.x, we are enforcing the convention where a Document Store corresponds to a specific index/collection.
Having some methods where you can specify `index` is inconsistent and fuels user confusion.
See https://github.com/deepset-ai/haystack-core-integrations/issues/942
- remove `index` parameter from internal and public methods
- this is a breaking change -> I will release a new major version
CI
- I have updated the related …
=> refactor!: Qdant - remove `index` parameter from methods

integrations/google_vertex/tests/chat/test_gemini.py, integrations/google_vertex/tests/test_gemini.py
- Nightly tests are failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11603564730/job/32310766803
- probably a new version was released, that introduced a new field (`property_ordering`)
- Fix the failing test, introducing the new field 
CI …
=> chore: fix Vertex tests

integrations/fastembed/pyproject.toml
- tests are failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11655952323/job/32451370656
- related fastembed issue: https://github.com/qdrant/fastembed/issues/385
Temporarily pin `onnxruntime<1.20.0`.
We should remove this pin in the future: I would expect that fastembed will support `onnxruntime<1.20.0` or they will pin the library themselves.
CI …
=> chore: fastembed - pin `onnxruntime<1.20.0`

integrations/chroma/pyproject.toml, integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py, integrations/chroma/src/haystack_integrations/document_stores/chroma/filters.py, integrations/chroma/tests/test_document_store.py
- failing tests: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11655758403
- in 0.5.17, Chroma introduced some breaking changes:
- writing documents that do not contain a valid string (`None`) causes an error
- they changed filter default: from `{}` to `None`
- incorporate their changes
- pin `chroma>=0.5.17`
CI
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my …
=> fix: adapt our implementation to breaking changes in Chroma 0.5.17 

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py, integrations/langfuse/tests/test_tracer.py
- see https://github.com/deepset-ai/haystack/pull/8444
Support TTFT by casting isoformat to a datetime object and include it in a generation.
Unit test. I also have E2E tests in my version, which is almost the same but not exactly.
=> feat: add support for ttft

integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_document_store.py
- temporary fix for #1172 
In case `_split_overlap` meta field is present, do not write it.
CI, new test.
=> fix: Weaviate - skip `_split_overlap` meta field

integrations/weaviate/pyproject.toml
- fixes dependency conflicts
- we had conflicting packages when installing weaviate with other doctores due to pinning the pydoc markdown package
=> fix: dependency for weaviate document store

integrations/deepeval/pyproject.toml
- nightly tests are failing for python 3.9 https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11807852571
- pin `langchain` dependency for python 3.9
CI
In the long run, I would like to unpin `deepeval` and support more recent versions,
but it's not trivial (we haven't done that for a while). …
=> fix: deepeval - pin indirect dependencies based on python version

integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/gemini.py, integrations/google_vertex/tests/test_gemini.py
- twin PR of #1177
We are removing support for tools in order to produce a `List[str]` output type, for consistency with other generators.
Users interested in tool calling should use the corresponding Chat Generator.
- remove support for tools
- change output type to `List[str]`
CI
This is a breaking change and I will release a major version.
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) …
=> fix: `VertexAIGeminiGenerator` - remove support for tools and change output type

integrations/nvidia/pyproject.toml, integrations/nvidia/src/haystack_integrations/__init__.py, integrations/nvidia/src/haystack_integrations/components/__init__.py, integrations/nvidia/src/haystack_integrations/components/embedders/__init__.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/document_embedder.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/text_embedder.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/truncate.py, integrations/nvidia/src/haystack_integrations/components/generators/__init__.py, integrations/nvidia/src/haystack_integrations/components/generators/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/components/generators/nvidia/generator.py, integrations/nvidia/src/haystack_integrations/components/rankers/__init__.py, integrations/nvidia/src/haystack_integrations/components/rankers/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/components/rankers/nvidia/ranker.py, integrations/nvidia/src/haystack_integrations/components/rankers/nvidia/truncate.py, integrations/nvidia/src/haystack_integrations/utils/__init__.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/nim_backend.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/utils.py, integrations/nvidia/tests/__init__.py, integrations/nvidia/tests/conftest.py, integrations/nvidia/tests/test_base_url.py, integrations/nvidia/tests/test_document_embedder.py, integrations/nvidia/tests/test_embedding_truncate_mode.py, integrations/nvidia/tests/test_generator.py, integrations/nvidia/tests/test_ranker.py, integrations/nvidia/tests/test_text_embedder.py
- Fixes the sede of the NvidiaRanker. Previously broken and not tested.
- Adds license headers to files
- Adds `__init__.py` files. I realize not strictly needed, but doesn't hurt. 
- Reenables some tests (forgotent `test_` prefix) and adds some new ones
- added tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, …
=> fix: Fixes to NvidiaRanker

integrations/fastembed/README.md, integrations/fastembed/examples/ranker_example.py
Following https://github.com/deepset-ai/haystack-core-integrations/pull/1178, I forgot to change the Readme.md.
So, I added an example for the new code and tested and fixed the others.
Also, I found an issue on the examples/ranker_example.py that I wrote
I checked the page and each example manually.
Plus, I ran the unit tests and the linter
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for …
=> docs: Fastembed Ranker - update readme and fix example

.github/workflows/CI_pypi_release.yml, cliff.toml
- fixes #1176 
Change the `--include-path` glob to include all files in the integration folder to track for changelog generation.
Change the `cliff.toml` config file so that PRs that don't follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) appear in the changelog in a separate category.
I also split CI and Chores sections.
I tested this locally.
This is the before:
```markdown
- Add support for ttft (#1161)
- Adopt uv as installer (#1142)
- Update ruff linting scripts and settings (#1105)
- Add invocation_context to identify traces (#1089)
- Langfuse - support generation span for more LLMs (#1087)
- Remove usage of deprecated `ChatMessage.to_openai_format` (#1001)
- Add link to langfuse in LangfuseConnector (#981)
- Do not retry tests in `hatch run test` command …
```
=> ci: Fix changelog generation

integrations/azure_ai_search/pyproject.toml
- fixes: a failing job likely caused due to mismatch of tag name for release
https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11952076315/job/33317043747
Fix the tag name in `pyproject.toml` file.
NA
NA
=> fix: Fix tag name for version release

integrations/ollama/pyproject.toml, integrations/ollama/src/haystack_integrations/components/embedders/ollama/__init__.py, integrations/ollama/src/haystack_integrations/components/embedders/ollama/document_embedder.py, integrations/ollama/src/haystack_integrations/components/embedders/ollama/text_embedder.py, integrations/ollama/src/haystack_integrations/components/generators/ollama/__init__.py, integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py, integrations/ollama/src/haystack_integrations/components/generators/ollama/generator.py, integrations/ollama/tests/test_chat_generator.py
- tests are failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/11963832597/job/33355031427
- yesterday, a new version of the Ollama python client was released: they introduce pydantic and this breaks some of our assumptions to use python dictionaries
- See https://github.com/ollama/ollama-python/releases/tag/v0.4.0; https://github.com/ollama/ollama-python/pull/276
- update our code to make it work with `ollama>=0.4.0`
- pin `ollama>=0.4.0`
CI, manual tests
- I …
=> fix: adapt to Ollama client 0.4.0

README.md
I think this information should be present here.
This should help maintainers not forget to tag the right commit.
=> chore: improve README release section

.github/workflows/pgvector.yml, integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py, integrations/pgvector/tests/test_document_store.py, integrations/pgvector/tests/test_retrievers.py
Related Issues
Normal Postgresql User failed to connect PG host, because missing the admin role.
Create Extension need HIGH Permission in many cloud environment, like Azure https://learn.microsoft.com/en-us/azure/postgresql/extensions/how-to-allow-extensions?tabs=portal#create-extension
Proposed Changes:
Recommend to remove to check extension if exists pgvector in every connection.
Operational Level like DBA can create Vector extension once
Developer can connect it without considering this precondition.
How did you test it?
manual tests
Notes for the reviewer
Checklist
I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_ …
=> feat: add `create_extension` parameter to control vector extension creation

integrations/amazon_bedrock/src/haystack_integrations/components/embedders/amazon_bedrock/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/embedders/amazon_bedrock/document_embedder.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/__init__.py, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/__init__.py, integrations/azure_ai_search/src/haystack_integrations/document_stores/azure_ai_search/__init__.py, integrations/chroma/src/haystack_integrations/components/retrievers/chroma/__init__.py, integrations/cohere/src/haystack_integrations/components/embedders/cohere/document_embedder.py, integrations/cohere/src/haystack_integrations/components/generators/cohere/__init__.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/__init__.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_document_embedder.py, integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_sparse_document_embedder.py, integrations/fastembed/src/haystack_integrations/components/rankers/fastembed/ranker.py, integrations/google_ai/src/haystack_integrations/components/generators/google_ai/__init__.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/__init__.py, integrations/google_vertex/tests/chat/test_gemini.py, integrations/instructor_embedders/src/haystack_integrations/components/embedders/instructor_embedders/instructor_document_embedder.py, integrations/jina/src/haystack_integrations/components/embedders/jina/document_embedder.py, integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/__init__.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/__init__.py, integrations/nvidia/src/haystack_integrations/components/embedders/nvidia/document_embedder.py, integrations/nvidia/src/haystack_integrations/utils/nvidia/__init__.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/__init__.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/optimum_document_embedder.py, integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/__init__.py, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/__init__.py
- several linting failures related to a ruff update. See for example https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12000920087/job/33450688446
- fix linting/isort: for each affected integration, I ran `hatch env prune` + `hatch run lint:fmt`
CI …
=> chore: fix linting/isort

integrations/astra/src/haystack_integrations/document_stores/astra/astra_client.py, integrations/astra/tests/test_embedding_retrieval.py
- fixes #1204
- After upgrading the astrapy lib [#1145](https://github.com/deepset-ai/haystack-core-integrations/pull/1145) there is a bug that don't limit the number of results when using an embedding search. As a result of this, many more expected documents are retrieved.
- Integration test.
- Add `test_embedding_retrieval.py` following the same pattern as in other store integrations. …
=> fix: Astra - fix embedding retrieval top-k limit

integrations/jina/src/haystack_integrations/components/connectors/jina/reader.py
In the `JinaReaderConnector`, the name of the output edge has been incorrectly set to `document` instead of `documents`.
This is wrong and not consistent with the name of the key in the returned dictionary (`documents`).
Rename the output edge to `documents`
CI …
=> fix: `JinaReaderConnector` - fix the name of the output edge

integrations/chroma/pyproject.toml
- Chroma tests on python 3.8 are failing due to missing `tokenizers`: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12060032349/job/33629714424
- this happens because the latest version of `tokenizers` does not have binaries for python 3.8 (see https://github.com/chroma-core/chroma/pull/3202)
- pin `tokenizers`, as they do in https://github.com/chroma-core/chroma/pull/3211
CI
- the pin will be removed as soon as Chroma releases a new version where they adopt the pin themselves
- (in general, we should think about when to discontinue python 3.8 compatibility)
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/ …
=> chore: Chroma - pin `tokenizers`

integrations/chroma/pyproject.toml
- fixes #1225
Now that Chroma internally pin the `tokenizers` library, remove our pin
CI
=> chore: Chroma - unpin `tokenizers`

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py, integrations/langfuse/tests/test_tracer.py
- fixes #1230 
Add a warning during `LangfuseTracer` initialization in case tracing is disabled.
Tested locally by running the tracer with `LangufuseConnector` in the following cases:
- importing `haystack.Pipeline` before setting `HAYSTACK_CONTENT_TRACING_ENABLED` (warning raised)
- importing `haystack.Pipeline` after setting `HAYSTACK_CONTENT_TRACING_ENABLED` (no warning)
I have not added unit tests because it requires to clear haystack modules and re-import it while having the appropriate HAYSTACK_CONTENT_TRACING_ENABLED env variable set. I though about adding it by removing haystack imports via sys.modules, and re-importing having HAYSTACK_CONTENT_TRACING_ENABLED=false for raising the warning, but apparently by doing so other tests fails, I think I would have to re-import the module …
=> feat: warn if LangfuseTracer initialized without tracing enabled

integrations/langfuse/tests/test_tracing.py, integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/chat/chat_generator.py, integrations/llama_cpp/tests/test_chat_generator.py, integrations/mistral/tests/test_mistral_chat_generator.py
- part of #1236
- use `text` instead of `content` for `ChatMessage` in **Llama.cpp**, Langfuse and Mistral
- I did the changes in a single PR because we only need a release for **Llama.cpp** (for others, I'm only changing the tests)
CI
=> chore: use `text` instead of `content` for `ChatMessage` in Llama.cpp, Langfuse and Mistral

integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py, integrations/ollama/tests/test_chat_generator.py
- part of #1236
- use `text` instead of `content` for `ChatMessage` in Ollama
- (this change won't last long. Ollama proper support for Tools and new messages has already been done in experimental)
CI
=> chore: use `text` instead of `content` for `ChatMessage` in Ollama

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py
- part of #1236 (accessing `text` instead of `content`)
- while working on the previous point, I noticed that in messages from function, the `content` is a `dict` instead of `str` (see [Haystack `ChatMessage` definition](https://github.com/deepset-ai/haystack/blob/248dccbdd341941b988b622c51c26d1b9af66876/haystack/dataclasses/chat_message.py#L31)). This happened also because in integrations we skipping mypy checks for Haystack (this is not easy to fix) - see https://github.com/deepset-ai/haystack-core-integrations/blob/92830654d2db3350a48a7eabc337c8bc8075612b/integrations/google_ai/pyproject.toml#L150-L153
- fix the content type
- use `text` instead of `content` to access the text
CI
- This is a bug fix but also a breaking change. To make things clearer, I think that we can release a major …
=> fix: GoogleAI - fix the content type of `ChatMessage` `content` from function

integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py
- part of #1236 (accessing `text` instead of `content`)
- twin PR of #1241 (see it for details and review it first)
- I noticed that in messages from function, the `content` is a `dict` instead of `str` (see [Haystack `ChatMessage` definition](https://github.com/deepset-ai/haystack/blob/248dccbdd341941b988b622c51c26d1b9af66876/haystack/dataclasses/chat_message.py#L31)). This happened also because in integrations we skipping mypy checks for Haystack (this is not easy to fix)
- fix the content type
- use `text` instead of `content` to access the text
CI
- This is a bug fix but also a breaking change. To make things clearer, I think that we can release a major version
- In the future, when new `ChatMessage` + `Tool` are adopted, we should refactor the tool calling section of this Chat …
=> fix: Google Vertex - fix the content type of `ChatMessage` `content` from function

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py, integrations/amazon_bedrock/tests/test_generator.py
- fixes support for model_arn as model_id
- `model_family` param which explicitly chooses model adapter if it can't be infered from model name
- added tests
=> feat: support model_arn in AmazonBedrockGenerator

integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/bm25_retriever.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_bm25_retriever.py
Updates the doc string of the fuzziness parameter and the type. Accepts string or int
=> chore: Update docstring and type of fuzziness

integrations/snowflake/src/haystack_integrations/components/retrievers/snowflake/snowflake_table_retriever.py, integrations/snowflake/tests/test_snowflake_table_retriever.py
=> chore: add application name

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/amazon_bedrock/tests/test_chat_generator.py
- Use positional argument in ChatMessage class methods
- access `text` instead of `content`
Local run with Haystack main branch, CI
=> fix: fixes to Bedrock Chat Generator for compatibility with the new ChatMessage

integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py, integrations/anthropic/tests/test_chat_generator.py
- nigthly test failing, related to prompt caching: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12383597750/job/34566600812
- make the Chat Generator compatible with both new and old `ChatMessage` (this is temporary: we will port soon the Chat Generator with Tool support from experimental)
- fix prompt caching tests
CI …
=> fix: make Anthropic compatible with new `ChatMessage`; fix prompt caching tests

.github/workflows/amazon_bedrock.yml, .github/workflows/amazon_sagemaker.yml, .github/workflows/anthropic.yml, .github/workflows/astra.yml, .github/workflows/azure_ai_search.yml, .github/workflows/chroma.yml, .github/workflows/cohere.yml, .github/workflows/deepeval.yml, .github/workflows/elasticsearch.yml, .github/workflows/fastembed.yml, .github/workflows/google_ai.yml, .github/workflows/google_vertex.yml, .github/workflows/instructor_embedders.yml, .github/workflows/jina.yml, .github/workflows/langfuse.yml, .github/workflows/llama_cpp.yml, .github/workflows/mistral.yml, .github/workflows/mongodb_atlas.yml, .github/workflows/nvidia.yml, .github/workflows/ollama.yml, .github/workflows/opensearch.yml, .github/workflows/optimum.yml, .github/workflows/pgvector.yml, .github/workflows/pinecone.yml, .github/workflows/qdrant.yml, .github/workflows/ragas.yml, .github/workflows/snowflake.yml, .github/workflows/unstructured.yml, .github/workflows/weaviate.yml
After the release of the new `ChatMessage` in https://github.com/deepset-ai/haystack/pull/8640, I was expecting several failures in the nightly tests with Haystack main.
Indeed, I encountered these failures locally by executing the following steps:
```shell
...
cd "$dir"
hatch env prune
hatch run uv pip install git+https://github.com/deepset-ai/haystack.git
hatch run uv pip freeze
```
However the nightly CI tests did not fail... :thinking: 
Then I realized what's the difference:
https://github.com/deepset-ai/haystack-core-integrations/blob/3a3419a21bcc08da7cdf52d033c89656112dad98/.github/workflows/amazon_bedrock.yml#L84
We are not using uv there, so the tests don't run with Haystack main, but with the latest stable release.
- use uv to install Haystack main in the test environment
Local …
=> ci: make nightly tests actually run with Haystack main branch

integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py
- small fix to ensure that the Ollama Chat Generator is compatible with both old and new `ChatMessage`
These changes are temporary. We will soon port Ollama from experimental to introduce proper tool support.
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, …
=> fix: make Ollama Chat Generator compatible with new `ChatMessage`

integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py, integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/chat/chat_generator.py, integrations/llama_cpp/tests/test_chat_generator.py
- fixes to ensure that the llama.cpp Chat Generator is compatible with both old and new `ChatMessage`
=> fix: make llama.cpp Chat Generator compatible with new `ChatMessage`

integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py
- small fixes to ensure that the Google Vertex Chat Generator is compatible with both old and new `ChatMessage`
=> fix: make Google Vertex Chat Generator compatible with new ChatMessage

integrations/cohere/tests/test_cohere_chat_generator.py, integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py
- fixes to ensure the Google AI Chat Generator is compatible with both old and new `ChatMessage`
- small fixes in Cohere tests (no need to release a new version for them)
These changes are temporary. I hope to get rid of them soon, once we reimplement this ChatGenerator to add proper tool support. …
=> fix: make GoogleAI Chat Generator compatible with new `ChatMessage`; small fixes to Cohere tests

integrations/nvidia/src/haystack_integrations/components/rankers/nvidia/ranker.py
- fixes #1259
Model `nvidia/llama-3.2-nv-rerankqa-1b-v2` be added to set of known model's by adding it's endpoint to `_MODEL_ENDPOINT_MAP`.
Simple addition of  `"nvidia/llama-3_2-nv-rerankqa-1b-v2": "https://ai.api.nvidia.com/v1/retrieval/nvidia/llama-3_2-nv-rerankqa-1b-v2/reranking"`  to the map.
Running the Hatch tests and manual verification by importing the changed `NvidiaRanker()` instead.
Run the Google Colab provided in #1259 to reproduce the issue.
This was set to `feat:` instead of `fix:` on comparing with #1183.
- I have updated the related …
=> feat: add model `nvidia/llama-3.2-nv-rerankqa-1b-v2` to `_MODEL_ENDPOINT_MAP`

.github/workflows/chroma.yml, integrations/chroma/pyproject.toml, integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py
- nightly tests are failing https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12575566340/job/35050656749 due to a breaking change in Chroma v0.6.0 - https://docs.trychroma.com/production/administration/migration#migration-log
- small fix in the code
- pin `chromadb>=0.6.0`
- since Chroma no longer supports python 3.8, drop it in our integration (and run tests with 3.11 instead)
CI
- I've used one of the [conventional …
=> fix: updates for Chroma 0.6.0

integrations/mistral/tests/test_mistral_chat_generator.py
- `OpenAIChatGenerator` was refactored in https://github.com/deepset-ai/haystack/pull/8666 and Mistral inherits from it
- failing nightly tests with Haystack main: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12575726108/job/35051031568
Fix tests
CI; local tests with Haystack main. …
=> test: adapt Mistral to OpenAI refactoring

integrations/nvidia/src/haystack_integrations/components/rankers/nvidia/ranker.py
None
*Feature*: adds Fine-tuned Mistral-7B-v0.1 LLM as reranker to the set of known model's by adding it's endpoint to `_MODEL_ENDPOINT_MAP`
* ran `pytest tests/test_ranker.py`
* ran locally with test code with hatch venv `nvidia-haystack`
```py
from haystack_integrations.components.rankers.nvidia import NvidiaRanker
from haystack.utils import Secret
ranker = NvidiaRanker(
model="nv-rerank-qa-mistral-4b:1",
api_key=Secret.from_env_var("NVIDIA_API_KEY"),
)
ranker.warm_up()
```
https://build.nvidia.com/nvidia/rerank-qa-mistral-4b?snippet_tab=Python
https://docs.api.nvidia.com/nim/reference/nvidia-rerank-qa-mistral-4b …
=> feat: add nv-rerank-qa-mistral-4b:1 reranker

integrations/anthropic/tests/test_chat_generator.py, integrations/cohere/tests/test_cohere_chat_generator.py
Anthropic and Cohere nightly tests with Haystack main are failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12681186127/job/35344406772 - https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12681372385/job/35344956395
This happens after we explicitly prohibited the serialization of lambdas in https://github.com/deepset-ai/haystack/pull/8683
- Remove the affected tests - serialization of callables is already tested in other tests in the respective test suites, with proper functions
CI
- I have updated the …
=> test: remove tests involving serialization of lambdas

integrations/anthropic/tests/test_generator.py, integrations/anthropic/tests/test_vertex_chat_generator.py, integrations/cohere/tests/test_cohere_generator.py
In #1281, I forgot to remove some tests and nightly tests failed again.
https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12700578430
https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12700763790
- Remove the affected tests - serialization of callables is already tested in other tests in the respective test suites, with proper functions
CI …
=> test: remove more tests involving serialization of lambdas

integrations/pgvector/README.md, integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py, integrations/pgvector/tests/test_document_store.py
- fixes #1275
In pgvector if HNSW index should drop, only index_name was used, but not schema_name. So if there were multiple schemas, the index was not dropped and could not be recreated.
The check was added directly to the code, so if the index existed and should be dropped, the Error is raised, because I consider it as critical Error.
I tested this on multiple machines with similar setups, and the behavior was not consistent. On one PC this fix was needed, but on the other PC this fix was not needed, and it was working even without the fix, but I was not able to discover the difference...
But I believe that the fix is correct, and should be applied.
=> fix: PgvectorDocumentStore - use appropriate schema name if dropping index

integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py, integrations/cohere/tests/test_cohere_chat_generator.py
- related to https://github.com/deepset-ai/haystack/issues/8583
- nightly test failure: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12778810943/job/35622334343
Create Chat Messages appropriately
CI
=> fix: Cohere - fix `ChatMessage` creation

integrations/mistral/pyproject.toml, integrations/mistral/tests/test_mistral_chat_generator.py
- part of #1273
- in #1271, I modified Mistral tests to be compatible with both Haystack 2.8.0 and 2.9.0
- pin `haystack-ai>=2.9.0`
- simplify test
CI
=> chore: Mistral - pin  `haystack-ai>=2.9.0` and simplify test

integrations/langfuse/pyproject.toml, integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py
- part of #1273
- in #1272, I introduced a not-so-nice check to make the tracer compatible with both Haystack 2.8.0 and 2.9.0
- pin `haystack-ai>=2.9.0`
- simplify message conversion
CI
=> chore: Langfuse - pin `haystack-ai>=2.9.0` and simplify message conversion

integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py
Nightly tests with Haystack main are failing due to the removal of `FUNCTION` role in https://github.com/deepset-ai/haystack/pull/8725
failing test: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12799206032/job/35684798292
- Gently handle the removal, checking if `FUNCTION` role is available …
=> chore: Vertex - gently handle the future removal of `FUNCTION` role

integrations/llama_cpp/pyproject.toml, integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/chat/chat_generator.py, integrations/llama_cpp/tests/test_chat_generator.py
Nightly tests with Haystack main are failing due to the removal of `ChatMessage.from_function` in https://github.com/deepset-ai/haystack/pull/8725
failing test: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12799444834/job/35685509040
- Avoid using `ChatMessage.from_function` in tests - if not available
- Partially unrelated: pin `haystack-ai>=2.9.0` to remove a previously introduced compatibility check
You may notice how this PR is doing some workarounds to avoid tests failing.
I'll soon create an issue to keep track of proper implementation of Tool support in llama.cpp. …
=> chore: llama.cpp - gently handle the removal of `ChatMessage.from_function`

integrations/google_ai/pyproject.toml, integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py
Nightly tests with Haystack main are failing due to the removal of `FUNCTION` role and  `ChatMessage.from_function` in https://github.com/deepset-ai/haystack/pull/8725
failing test: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12799530567/job/35685749382
- Gently handle the removal, checking if `FUNCTION` role is available
- avoid using `ChatMessage.from_function` in tests - if not available
You may notice how this PR is doing some workarounds to avoid tests failing.
I'll soon create an issue to keep track of proper implementation of Tool support in Google AI. …
=> chore: Google-AI - gently handle the removal of `FUNCTION` role and `ChatMessage.from_function`

integrations/anthropic/example/prompt_caching.py, integrations/anthropic/pyproject.toml, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/vertex_chat_generator.py, integrations/anthropic/tests/test_chat_generator.py, integrations/anthropic/tests/test_vertex_chat_generator.py
- fixes #1258
@vblagoje 
This started as a simple porting of your work from experimental.
Then I realized that some parts were missing and implemented them:
- prompt caching support
- Open-AI compatible usage meta
- (adaptation for Anthropic on Vertex)
CI, new tests
I tried to port tests from experimental, but also keep existing ones that cover otherwise untested behaviors.
Technically, this change could be non-breaking, but I would prefer to release a new major version to be sure, since we changed the implementation a lot.
- I have updated the related …
=> feat: Anthropic - support for Tools + refactoring

integrations/amazon_bedrock/pyproject.toml
- nightly tests have been failing for several days: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12858522724/job/35847742797
- this happens because of a bug in Transformers 4.48.0: https://github.com/huggingface/transformers/issues/35639
- Since the maintainers of Transformers do not plan to publish a bugfix release, pin `transformers!=4.48.0`
CI …
=> fix: Bedrock - pin `transformers!=4.48.0`

integrations/optimum/pyproject.toml, integrations/optimum/tests/test_optimum_document_embedder.py, integrations/optimum/tests/test_optimum_text_embedder.py
- tests have been failing for several days: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12858475671
- there are 2 types of errors: one is related to `transformers==4.48.0` (https://github.com/huggingface/transformers/issues/35639)
- another error is `AttributeError: 'ORTModelForFeatureExtraction' object has no attribute 'input_names'. Did you mean: 'inputs_names'`. I cannot reproduce it locally but only in the CI.
- my impression is that pinning `transformers` causes strange dependency resolution. I also think we don't need that specific pin: it is already pinned by Optimum - see https://github.com/huggingface/optimum/blob/0a2b843ed4da48002e36d529fee5b1c607d6f301/setup.py#L51
- unpin `transformers` and let `optimum` handle the dependency
CI
- I have read the …
=> fix: Optimum - do not explictly pin `transformers`

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py
Refines the tracing logic to handle different types of spans and their proper end()ing. 
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1262
- Added support for finalizing both regular and generation spans by extending type checks.
- Introduced comments to clarify the span ending logic and lifecycle management.
Internal change not visible to clients
- Relying on existing unit tests
- Verified manually via `chat.py` example that generated this [trace](https://cloud.langfuse.com/trace/5c85a1ff-9b01-40fd-891d-042bb860a085)
- Contrast that trace to [this one](https://cloud.langfuse.com/project/clvdk4bcb000099hzwhts3g66/traces/4fdfd20a-fc29-4e61-a6ba-1e7062d78483) that doesn't have end() called for generation. The end result is that the latency for generation is not …
=> fix: End langfuse generation spans properly

integrations/langfuse/pyproject.toml, integrations/langfuse/src/haystack_integrations/components/connectors/langfuse/langfuse_connector.py, integrations/langfuse/tests/test_tracing.py
Enhances the LangfuseConnector by adding support for custom HTTP clients, allowing for greater flexibility and control over API communication.
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1151
- Introduced an optional `httpx.Client` parameter to the `LangfuseConnector` to allow custom HTTP client usage.
- Updated constructor and documentation to include the new `httpx_client` parameter.
- Ensured that the `httpx_client` is integrated into the Langfuse API call handling.
With these changes, users can now pass a custom HTTP client to the LangfuseConnector as shown in the code snippet below:
```python
from httpx import Client
from haystack_integrations.components.connectors.langfuse import LangfuseConnector
custom_client = Client(timeout=10.0)
connector = …
```
=> feat: LangfuseConnector - add httpx.Client init param

integrations/cohere/src/haystack_integrations/components/embedders/cohere/document_embedder.py, integrations/cohere/src/haystack_integrations/components/embedders/cohere/embedding_types.py, integrations/cohere/src/haystack_integrations/components/embedders/cohere/text_embedder.py, integrations/cohere/src/haystack_integrations/components/embedders/cohere/utils.py, integrations/cohere/src/haystack_integrations/components/rankers/cohere/ranker.py, integrations/cohere/tests/test_cohere_ranker.py, integrations/cohere/tests/test_document_embedder.py, integrations/cohere/tests/test_text_embedder.py
- Migrates our Cohere integration to V2 (embedder(s) and ranker).
- Embedders can now use `embedding_types` to choose the size of the embeddings, providing more control over memory usage and performance.
- (Chat)Generator migration is done in a separate [PR](https://github.com/deepset-ai/haystack-core-integrations/pull/1318).
- Introduced `EmbeddingTypes` enum to define and manage supported embedding types:
- **Allowed values**:
- `float`: Default float embeddings (valid for all models).
- `int8`: Signed int8 embeddings (valid for v3 models only).
- `uint8`: Unsigned int8 embeddings (valid for v3 models only).
- `binary`: Signed binary embeddings (valid for v3 models only).
- `ubinary`: Unsigned binary embeddings (valid for v3 models only).
- Updated `CohereDocumentEmbedder` and …
=> refactor: Migrate Cohere to V2

.github/workflows/CI_pypi_release.yml
To address issues with unpredictable automatic changelog commits in pypi releases of our subprojects, this PR introduces automated pull requests for changelog updates. This provides more control and flexibility, enabling quick reviews, easy edits, and better handling of edge cases. It also allows us to refine the `cliff.toml` configuration without the risk of unexpected errors in changelogs.
- Replaced the `add-and-commit` action with the `create-pull-request` action to open pull requests for changelog updates instead of committing directly.
- Configured the action to create a new branch and a well-structured pull request for each changelog modification.
- Improved messaging in created PRs 
Upon each release, the workflow will execute the following:
```yaml
uses: …
```
=> ci: Automatically open PR for subproject CHANGELOG.md updates

.github/workflows/CI_pypi_release.yml
A fix for previous PR that missed the base branch target for https://github.com/deepset-ai/haystack-core-integrations/pull/1328
=> fix: Fix failing automatic PR generation for changelog

integrations/amazon_bedrock/src/haystack_integrations/components/rankers/amazon_bedrock/ranker.py, integrations/amazon_bedrock/tests/test_ranker.py
Issue not created
A tiny fix for the Ranker models I integrated in previous MR to handle cases where document list is empty (that can happens with Retrievers or filters after retrieval). The Ranker should just return the empty document list instead of crashing (AWS Bedrock API doesn't like an empty document list and throw an error).
Added a new unit test to confirm the good behaviour.
None. It's a small minor bug fix with no breaking change …
=> Fix(Bedrock): Reranker fails when document list is Empty

integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py, integrations/google_vertex/tests/chat/test_gemini.py
The usage example in the [docstring](https://github.com/deepset-ai/haystack-core-integrations/blob/3b5efec90a280dbc36565941a057653efa6383bc/integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py#L84) is failing with:
`google.api_core.exceptions.BadRequest: 400 POST https://us-central1-aiplatform.googleapis.com/v1/projects/gen-lang-client-0206209522/locations/us-central1/publishers/google/models/gemini-2.0-flash-exp:generateContent?%24alt=json%3Benum-encoding%3Dint: Unable to submit request because it has an empty text parameter. Add a value to the parameter and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini`
This happens because when building assistant response, an empty `text` is created …
=> fix: VertexAIGeminiChatGenerator - do not create messages with empty text

integrations/pgvector/src/haystack_integrations/document_stores/pgvector/filters.py, integrations/pgvector/tests/test_filters.py
- fixes: #1340
Currently the metadata used for filtering are limited to : 
- `==`
- `!=`
- `>`
- `>=`
- `<`
- `<=`
- `in`
- `not in`
According to this haystack page: [here](https://docs.haystack.deepset.ai/docs/metadata-filtering)
I came upon a problem that I wanted to check if a specific metadata include a specific string (this is similar to str contains in python). 
I resolved this by manually adding the LIKE and NOT_LIKE operator to haystack pg vector.
Maybe we need to update it for all other databases as welll?
=> feat: Pgvector - add like and not like filters

integrations/azure_ai_search/src/haystack_integrations/document_stores/azure_ai_search/document_store.py
- fixes currently, `query_type = "simple"` is set in the `client.search` request for BM25 and hybrid retrieval. This is blocking semantic queries as the user should be able to pass `query_type = "semantic"`  in `kwargs` along with semantic configuration. 
Remove setting `query_type = "simple"` from `_bm25_retrieval` and `_hybrid_retrieval` methods of `AzureAISearchDocumentStore`. By removing this specification the type will still default to "simple", leaving the behaviour unchanged. 
CI / and locally tested semantic queries
- I have updated the related …
=> fix: remove setting `query_type="simple"` in retrieval request

.github/workflows/amazon_bedrock.yml, .github/workflows/amazon_sagemaker.yml, .github/workflows/anthropic.yml, .github/workflows/astra.yml, .github/workflows/azure_ai_search.yml, .github/workflows/chroma.yml, .github/workflows/cohere.yml, .github/workflows/deepeval.yml, .github/workflows/elasticsearch.yml, .github/workflows/fastembed.yml, .github/workflows/google_ai.yml, .github/workflows/google_vertex.yml, .github/workflows/instructor_embedders.yml, .github/workflows/jina.yml, .github/workflows/langfuse.yml, .github/workflows/llama_cpp.yml, .github/workflows/mistral.yml, .github/workflows/mongodb_atlas.yml, .github/workflows/nvidia.yml, .github/workflows/ollama.yml, .github/workflows/opensearch.yml, .github/workflows/optimum.yml, .github/workflows/pgvector.yml, .github/workflows/pinecone.yml, .github/workflows/qdrant.yml, .github/workflows/ragas.yml, .github/workflows/snowflake.yml, .github/workflows/unstructured.yml, .github/workflows/weaviate.yml
After #1330, every time we release a new integration, a PR with the proposed CHANGELOG change is opened and tests run on it, wasting time and computational resources.
- for each integration, do not run tests if only CHANGELOG.md is modified
Not easy to test before merging.
Some tests failures are unrelated to this PR. …
=> ci: skip tests when only CHANGELOG.md is modified

.github/workflows/google_ai.yml
- nightly tests are often failing with "429 Resource has been exhausted": https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13103967998/job/36555829567
- this likely happens because too many requests are sent in a short period of time (https://groups.google.com/g/adwords-api/c/gcKvh1C3GX4?pli=1)
- set `max-parallel: 2` in the GitHub workflow to have a maximum of 2 jobs running at the same time ([docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel))
CI
- I have …
=> test: GoogleAI - reduce tests concurrency

.github/workflows/ollama.yml
- Ollama tests are failing often: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13147246857/job/36687949059
- this happens for several reasons, including network errors and subtle bugs on some Ollama versions
After some attempts, I decide to make this testing workflow more structured and robust:
- separate Ollama installation and model pulling
- add a retry mechanism for these different steps: if they fail, it's not possible that python tests will pass
- (python tests already have a retry mechanism)
CI
if you look at latest CI runs, you'll notice that the pulling step sometimes failed and has been retried …
=> ci: make Ollama testing workflow more robust

integrations/langfuse/tests/test_tracing.py
- nightly tests often fail: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13190420961/job/36822188315
- add `time.sleep(5)` to `test_custom_span_handler`: we need to wait for the response to be generated and the trace to be created
CI …
=> test: Langfuse - wait before retrieving the trace in `test_custom_span_handler`

integrations/llama_cpp/pyproject.toml, integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/chat/chat_generator.py, integrations/llama_cpp/tests/test_chat_generator.py
- fixes https://github.com/deepset-ai/haystack/issues/8737
- replace the old implementation of function calling with a new one, centered on our unified `Tool` abstraction (breaking)
- introduce missing `to_dict`/`from_dict` methods
- incorporate potential tokenizer download in `warm_up` (instead of `__init__`)
CI, several new tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR …
=> feat!: llama.cpp - unified support for tools + refactoring

integrations/mistral/pyproject.toml, integrations/mistral/src/haystack_integrations/components/embedders/mistral/document_embedder.py, integrations/mistral/src/haystack_integrations/components/generators/mistral/chat/chat_generator.py, integrations/mistral/tests/test_mistral_chat_generator.py
- fixes https://github.com/deepset-ai/haystack/issues/8736
- mostly based on OpenAIChatGenerator code
=> adding tools to MistralChatGenerator - based on OpenAIChatGenerator

integrations/pgvector/pyproject.toml, integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py, integrations/pgvector/src/haystack_integrations/document_stores/pgvector/filters.py, integrations/pgvector/tests/test_document_store.py, integrations/pgvector/tests/test_filters.py
This is the first PR to remove support for `dataframe` in document stores.
I'm doing that for Pgvector.
This is a breaking change -> I will release a major version of this integration.
CI;
I also tested locally that a table created with the current version of the Document Store still works with the new version (but does not support writing `dataframe`). …
=> chore: pgvector - remove support for dataframe

integrations/langfuse/tests/test_tracing.py
- langfuse nightly tests failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13319664714/job/37201718240
- make polling the Langfuse API more robust in tests:
- always sleep 10 seconds before calling the API (5 seconds is too short a time)
- centralize the logic in a utility function
CI …
=> test: langfuse - make polling more robust in tests

integrations/pinecone/src/haystack_integrations/document_stores/pinecone/document_store.py, integrations/pinecone/src/haystack_integrations/document_stores/pinecone/filters.py, integrations/pinecone/tests/test_filters.py
- remove dataframe support from Pinecone
This is a breaking change -> I will release a major version of this integration.
CI
=> chore!: pinecone - remove dataframe support

integrations/elasticsearch/pyproject.toml, integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py, integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/filters.py, integrations/elasticsearch/tests/test_document_store.py
- Remove dataframe support from Elasticsearch
CI; new tests
=> chore!: Elasticsearch - remove dataframe support

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/filters.py, integrations/opensearch/tests/test_document_store.py
- Remove dataframe support from OpenSearch
- also explicitly skip `SparseEmbedding` (initially forgotten in #606)
CI; new tests
=> chore!: OpenSearch - remove dataframe support

integrations/chroma/tests/test_document_store.py
- nightly tests are failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13360047675
- the test was introduced in #1373, but for some reason the test temporarily passed
- relax the test
- check that `content` has the expected value
- check that `blob` and `dataframe` are absent or `None`
- do not make assertions about the `embedding` field, which is automatically computed by Chroma
CI …
=> fix: Chroma - relax dataframe/blob test

integrations/langfuse/src/haystack_integrations/components/connectors/langfuse/langfuse_connector.py
=> docs: fixing typo in Langfuse API docstring

integrations/weaviate/pyproject.toml, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/_filters.py, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_bm25_retriever.py, integrations/weaviate/tests/test_document_store.py, integrations/weaviate/tests/test_embedding_retriever.py
- Remove dataframe support from Weaviate
CI; added specific tests;
I also tested locally that a collection created with the current version of the Document Store still works with the new version (but skips dataframe during writing and reading).
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) …
=> chore!: Weaviate - remove dataframe support

integrations/opensearch/pyproject.toml, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/bm25_retriever.py, integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/embedding_retriever.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_bm25_retriever.py, integrations/opensearch/tests/test_document_store.py, integrations/opensearch/tests/test_embedding_retriever.py
- fixes #1392
- Async support for `OpenSearchDocumentStore` and its retrievers.
- This is mostly a migration of work done in https://github.com/deepset-ai/haystack-experimental/pull/96 and other PRs approved in experimental.
- I took care of fixing some errors and integrating async with small features/changes merged in this integration and absent in the original experiment.
- (I also took the opportunity to adopt Haystack logging in OpenSearch - see #1409)
CI; migrated many new tests.
Even if this is a large PR, this is not a breaking change (original tests pass without requiring significant modifications). …
=> feat: OpenSearch - async support

integrations/unstructured/pyproject.toml
- nightly tests failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13380658910/job/37368547644
- pin `unstructured-client` to the latest working version
- unrelated: remove `psutil` dependency (added in #854 and no longer required)
CI
Unstructured is a complex ecosystem (library, clients, Docker image, free and paid APIs) and this is just a temporary fix to ensure that things work again.
I'll open an issue to track ideas for maintenance and refactoring of this integration.
- I have updated the related issue with new insights …
=> fix: Unstructured - pin client version

integrations/mistral/tests/test_mistral_chat_generator.py
While running unit tests locally with `hatch run test -m "not integration"`,
I discovered that `test_live_run_with_tools` was not marked as integration (and failed for lack of the env var).
- mark the test appropriately
CI
=> chore: Mistral - mark test as integration

integrations/ragas/example/evaluation_from_pipeline_example.py, integrations/ragas/example/evaluation_with_components_example.py, integrations/ragas/pyproject.toml, integrations/ragas/src/haystack_integrations/components/evaluators/ragas/evaluator.py, integrations/ragas/tests/test_evaluator.py
- Ragas now has HaystackLLMWrapper which will allow users to use Haystack LLMs as evaluators
=> feat: use HaystackLLMWrapper instead of LangChain in Ragas evaluators

integrations/azure_ai_search/tests/conftest.py, integrations/azure_ai_search/tests/test_document_store.py
While running unit tests locally with `hatch run test -m "not integration"`,
I encountered several errors due to the fact that the test suite tries to clean up Azure indexes at the end of session, even if I only run local unit tests.
I should be able to locally run the unit tests without worrying about API keys or encountering errors.
- refactor the `cleanup_indexes` fixture to only clean up indexes when we execute integration tests
- add some missing integration markers
Local runs; CI
- …
=> test: Azure AI Search - improvements to the test suite

integrations/pinecone/pyproject.toml
- Fixes #1430
Replace `pinecone-client` dependency with `pinecone`
CI only
Alternative would be to pin version of `pinecone-client` to >=3,<6.0.0
6.0.0 includes some breaking changes listed at the bottom of the release notes: https://github.com/pinecone-io/pinecone-python-client/releases/tag/v6.0.0
We should therefore release a new major version of the integration after this PR got merged. …
=> fix: replace `pinecone-client` dependency with `pinecone`

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py, integrations/google_ai/tests/generators/test_gemini.py
- failing nightly test https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13533769319/job/37821499273#step:8:112
`google.api_core.exceptions.NotFound: 404 models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.`
Support for gemini 1.0 pro ended on Feb 18, 2025: https://ai.google.dev/gemini-api/docs/changelog#02-18-2025
Related PR in haystack-integrations: https://github.com/deepset-ai/haystack-integrations/pull/304
- Changing the model in tests from gemini-pro to gemini-1.5-pro
- Changing the model also in the docstring code example
Only CI
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CO …
=> test: change model from unsupported gemini-pro to gemini-1.5-pro

integrations/opensearch/pyproject.toml
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1437
=> fix: OpenSearchDocumentStore depends on async opensearch-py

.github/workflows/nvidia.yml, integrations/nvidia/tests/test_document_embedder.py, integrations/nvidia/tests/test_text_embedder.py
- fixes https://github.com/deepset-ai/haystack-private/issues/105
- We run the integration tests weekly on Sundays instead of nightly
- We run the tests only with Python version 3.9 instead of 3.9 and 3.10
- For the parameterized embedder integration tests, we only use two models instead of six. I suggest NV-Embed-QA as it is also used in the example code snippet and nvidia/nv-embedqa-e5-v5 because support for it was most recently added in https://github.com/deepset-ai/haystack-core-integrations/pull/1015 .
Only CI
Integration tests won't run before we add more credits to Nvidia API account. …
=> test: Reduce Nvidia API calls in integration tests

integrations/amazon_bedrock/tests/test_chat_generator.py, integrations/anthropic/tests/test_chat_generator.py, integrations/cohere/tests/test_cohere_chat_generator.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py, integrations/google_vertex/tests/chat/test_gemini.py, integrations/mistral/tests/test_mistral_chat_generator.py
Adds `connection_type_validation` to the expected dicts when converting a pipeline to a dict.
Only updated tests
=> fix: Update serialization/deserialization tests to add new parameter `connection_type_validation`

integrations/anthropic/pyproject.toml, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py, integrations/anthropic/tests/test_chat_generator.py
- fixes #1380 
• Added async support to `AnthropicChatGenerator` with new `run_async` method
• Introduced `AsyncAnthropic` client initialization alongside existing sync client
• Refactored code to extract common functionality into `prepare_messages_and_tools`
• Added `_process_response` and `_process_response_async` methods to handle API responses
• Added async tests :
- Basic async functionality tests
- Live integration tests
• Made `convert_anthropic_chunk_to_streaming_chunk` and `_remove_cache_control static` methods
• Fixed usage metadata handling with proper Anthropic `Usage` type
• Maintained backward compatibility with existing sync functionality
- unit tests, integration tests, CI tests
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrat …
=> feat: adding async run to `AnthropicChatGenerator`

integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py
=> fix: apply ddtrace workaround to chat generator

integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/generator.py
Fixes wrong use of the haystack logger and adds the thinking parameter to allowed params.
=> feat: Support thinking parameter in Anthropic generators

integrations/anthropic/src/haystack_integrations/components/generators/anthropic/generator.py, integrations/anthropic/tests/conftest.py, integrations/anthropic/tests/test_generator.py
With [Claude 3.7](https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking#implementing-extended-thinking) the API supports the `thinking` parameter to enable extended thinking mode, e.g.:
```
"thinking": {
"type": "enabled",
"budget_tokens": 1024
}
```
Example:
https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking#implementing-extended-thinking
Note that thinking output is separated from normal text output, other than for example for Deepseek-R1. So we have to decide how to incorporate thinking output into the reply. Per default we include it using <thinking></thinking> tags, whereas this behavior is fully controllable via parameters:
- `include_thinking`: if `False` no thinking output is incorporated into the reply (default: `True`)
- `thinking_tag`: the …
=> feat: support extended thinking mode with AnthropicGenerator

integrations/pinecone/tests/conftest.py
Pinecone nightly tests have been failing intermittently for several days: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13688201316/job/38276265885
It seems that Pinecone servers got slower recently
- increase the sleep time: tests take longer, but hopefully we will get less failures
CI …
=> test: pinecone - increase sleep time in tests

.github/workflows/qdrant.yml, integrations/qdrant/pyproject.toml, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py, integrations/qdrant/tests/test_document_store.py
- related to #1434 (and #729)
- It happened several times that users try to use an existing Qdrant collection with Haystack and get errors
- when we are sure that the existing collection was created without Haystack and is not compatible, raise an informative error
CI; added several tests 
I will also take care of updating docs
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: …
=> refactor: Qdrant - raise error if existing collection is not compatible with Haystack

integrations/azure_ai_search/tests/conftest.py, integrations/deepeval/tests/test_evaluator.py, integrations/mongodb_atlas/tests/test_document_store.py, integrations/mongodb_atlas/tests/test_embedding_retrieval.py, integrations/mongodb_atlas/tests/test_fulltext_retrieval.py, integrations/pinecone/tests/test_document_store.py, integrations/pinecone/tests/test_filters.py
Reviewing https://github.com/deepset-ai/haystack-core-integrations/pull/1450 (community PR), I understood that some tests requiring API keys or other credentials were failing instead of being skipped (we don't pass Secrets in PRs from forks).
- Mongo: check more robustly if the credentials are set; credentials should be present and not empty. If not, skip tests.
- Azure AI Search: the conditions introduced in #1425 to clean up indexes after the test session are too complex and don't work properly. I implemented a simpler approach: if the API keys are present and not empty, just clean up the indexes.
CI; this PR is created from a fork. …
=> test: skip tests that require credentials on PRs from forks for some integrations

integrations/astra/pyproject.toml, integrations/astra/src/haystack_integrations/document_stores/astra/document_store.py, integrations/astra/tests/test_document_store.py
=> chore: Astra - pin `haystack-ai>=2.11.0` and remove dataframe checks

integrations/chroma/pyproject.toml, integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py, integrations/chroma/tests/test_document_store.py
=> chore: Chroma - pin haystack and remove dataframe checks

integrations/azure_ai_search/pyproject.toml, integrations/azure_ai_search/src/haystack_integrations/document_stores/azure_ai_search/document_store.py, integrations/azure_ai_search/tests/test_document_store.py
=> chore: Azure AI - pin haystack and remove dataframe checks

integrations/elasticsearch/pyproject.toml, integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py, integrations/elasticsearch/tests/test_document_store.py
=> chore: Elasticsearch - pin haystack and remove dataframe checks; add `aiohttp` dependency

integrations/opensearch/pyproject.toml, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_document_store.py
=> chore: OpenSearch - pin haystack and remove dataframe checks

integrations/pinecone/pyproject.toml, integrations/pinecone/src/haystack_integrations/document_stores/pinecone/document_store.py
- remove dataframe checks (no tests)
CI
=> chore: Pinecone - pin haystack and remove dataframe checks

integrations/snowflake/pyproject.toml
Nightly failures due to missing pandas dependency: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13777255521/job/38528856377
- add pandas dependency
CI
=> build: Snowflake - add pandas depenency

integrations/weaviate/pyproject.toml, integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py, integrations/weaviate/tests/test_document_store.py
=> chore: Weaviate - pin haystack and remove dataframe checks

integrations/qdrant/pyproject.toml, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/converters.py, integrations/qdrant/tests/test_converters.py
=> chore: qdrant - pin haystack and remove dataframe checks

integrations/mistral/pyproject.toml, integrations/stackit/pyproject.toml
Nightly failures: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13777505362/job/38529576009 
https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13777522873/job/38529623183
This likely happens because pytz was a dependency of pandas, removed in 2.11.0
- add pytz to test dependencies
- CI
- Mistral tests run but fail: this seems related to https://github.com/deepset-ai/haystack/pull/8968 and I won't fix it in this PR
- I added unit tests and …
=> test: Mistral/Stackit - add pytz test dependency

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py
I noticed `_ensure_index_exists` was erroneously called for each invocation of the CRUD operations of the Document Store.
This should only happen once, at initialization.
- call `_ensure_index_exists` only at initialization
CI
=> fix: OpenSearch - call `_ensure_index_exists` only at initialization

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/auth.py, integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_auth.py
- fixes AWS IAM Auth support for OpenSearch when using async API
- wrap AWSAuth for async support
- use `AsyncHttpConnection` as default connection class for `AsyncOpenSearch` (required for IAM Auth)
- added tests and tested manually against AWS Managed OpenSearch
- `AsyncOpenSearch` is safe to use as it is a subclass of the default connection class that adds a bunch of functionality (such as IAM Auth support) …
=> feat: AWS IAM Auth support for OpenSearch async

integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py, integrations/pgvector/tests/test_document_store.py
- fixes #1354
- modify the `_create_table_if_not_exists` method to be usable by non-admin users when the table already exists
CI; added a new test for the method
=> fix: pgvector - improve `_create_table_if_not_exists` to be used without admin rights

integrations/amazon_bedrock/pyproject.toml, integrations/amazon_bedrock/src/haystack_integrations/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/common/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/embedders/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/adapters.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py, integrations/amazon_bedrock/src/haystack_integrations/components/rankers/__init__.py, integrations/amazon_bedrock/tests/test_generator.py
- Removed `truncate` from `to_dict` since it's no longer supported
- Updated warning message to reflect that only `truncate` is deprecated. `max_length` still performs a function we would like to keep
- Updated docstrings to make it easier to find the model specific parameters
Updated tests …
=> refactor: Update AWS Bedrock with improved docstrings and warning message

integrations/weights_bias/src/haystack_integrations/components/connectors/weave_connector.py, integrations/weights_bias/src/haystack_integrations/tracing/weave/tracer.py, integrations/weights_bias/tests/test_tracer.py, integrations/weights_bias/tests/test_weave_connector.py
- mitigates https://github.com/deepset-ai/haystack/issues/9014 by allowing to pass `autopatch_settings` to `weave.init`
- add `weave_init_kwargs` to `WeaveConnector`
- (de)serialize AutopatchSettings
- added tests
Usage in yaml to disable autopatch:
```yaml
type: haystack_integrations.components.connectors.weave_connector.WeaveConnector
init_parameters:
pipeline_name: test_pipeline
weave_init_kwargs:
autopatch_settings:
disable_autopatch: true
``` …
=> feat: add weave_init_kwargs to WeaveConnector

integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py
- fixes #1550
Bug was introduced in https://github.com/deepset-ai/haystack-core-integrations/pull/1484 and I solved it by passing kwargs just like in similar cases in mentioned PR.
unit tests, manual verification
none
=> fix: `TypeError` in `QdrantDocumentStore` when handling duplicate documents

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_document_store.py
- fixes running OpenSearch BM25 retrieval with `custom_query` without passing `filters`raises exception:
```haystack.errors.FilterError: Filters must be a dictionary```
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1268
- fix usage when no `filters` are passed
- added test
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, …
=> fix: OpenSearch custom_query use without filters

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py, integrations/opensearch/tests/test_document_store.py
- fixes #1559
- take into consideration `self._return_embedding` in `filter_documents` method: if `False`, do not return embedding
- (unrelated: fix typo in fixture)
CI; new test
I'm convinced that `filter_documents` always returned embeddings since the introduction of the integration.
So, while #1559 seems to make sense, I would treat as a breaking change (it changes the default behavior of the Document Store) -> I will release a major version …
=> feat!: OpenSearch - apply `return_embedding` to `filter_documents`

cliff.toml
- During the release of an integration, the changelog is generated, including previous commits to update the changelog ("Update changelog for..."). This information is not useful and makes the changelog chaotic.
- There is a mechanism in place to avoid this, but it was not updated after https://github.com/deepset-ai/haystack-core-integrations/pull/1328 (where the commit message was changed)
- Update the Git cliff template to account for the new commit message format for changelog updates ([Tera templating syntax](https://keats.github.io/tera/docs/#in-checking))
I can't find a quick way to test this.
I suggest we just try... …
=> fix: do not include changelog update commits in changelog

integrations/amazon_bedrock/tests/test_chat_generator.py, integrations/anthropic/tests/test_chat_generator.py, integrations/cohere/tests/test_cohere_chat_generator.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py, integrations/google_vertex/tests/chat/test_gemini.py, integrations/mistral/tests/test_mistral_chat_generator.py, integrations/ollama/tests/test_chat_generator.py
- fixes #1580
- in serialization tests, take into account `inputs_from_state` and `outputs_to_state` tool parameters if they exist (they will be introduced in Haystack 2.12.0)
CI.
For each integration, I also locally ran the unit tests with Haystack main branch, similarly to what our nightly tests do.
*Bedrock test failures seems unrelated to this PR.* …
=> test: update tool serialization in tests to include `inputs_from_state` and `outputs_to_state`

cliff.toml
- follow up of #1566
- the changes in #1566 were effective, but now some commits with the legacy message ("Update the changelog") appear in the changelog (see #1586 for example)
- skip also commit messages with the legacy format
No easy ways to test it. …
=> fix: do not include changelog update commits in changelog - legacy format support

integrations/amazon_bedrock/src/haystack_integrations/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/common/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/embedders/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/rankers/__init__.py
Remove inits in folders that should be treated as namespace packages instead of regular packages.
More info [here](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages) but basically for package names that are shared across integrations e.g. haystack_integrations, components, retrievers, etc. we want to make sure these are treated as namespace packages so the namespaces are shareable when installing multiple integrations at once.
Additional info:
- in this [comment](https://github.com/deepset-ai/haystack-core-integrations/pull/1591#issuecomment-2774902527)
- and original [PR](https://github.com/deepset-ai/haystack-core-integrations/pull/1591)  …
=> fix: amazon-bedrock-haystack remove init files to make them namespace packages

integrations/nvidia/src/haystack_integrations/__init__.py, integrations/nvidia/src/haystack_integrations/components/__init__.py, integrations/nvidia/src/haystack_integrations/components/embedders/__init__.py, integrations/nvidia/src/haystack_integrations/components/generators/__init__.py, integrations/nvidia/src/haystack_integrations/components/rankers/__init__.py, integrations/nvidia/src/haystack_integrations/utils/__init__.py
Remove inits in folders that should be treated as namespace packages instead of regular packages.
More info [here](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages) but basically for package names that are shared across integrations e.g. haystack_integrations, components, retrievers, etc. we want to make sure these are treated as namespace packages so the namespaces are shareable when installing multiple integrations at once.
Additional info:
- in this [comment](https://github.com/deepset-ai/haystack-core-integrations/pull/1591#issuecomment-2774902527)
- and original [PR](https://github.com/deepset-ai/haystack-core-integrations/pull/1591)  …
=> fix: nvidia-haystack remove init files to make them namespace packages

.github/workflows/llama_cpp.yml, integrations/llama_cpp/pyproject.toml, integrations/llama_cpp/tests/test_chat_generator.py
- nightly failures: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/14232191293
- our test environment depends on `sentencepiece`, which has installation issues with python 3.13: https://github.com/google/sentencepiece/issues/1103
- test with python 3.12 instead
- clarify in pyproject.toml why we install `transformers[sentencepiece]`
CI …
=> test: test llama.cpp with python 3.12

cliff.toml
We recently improved changelog generation to exclude commits that only perform changelog updates
However, some of these commits are still included: see https://github.com/deepset-ai/haystack-core-integrations/pull/1599 for an example.
After investigation, I discovered that in this case, there have been manual edits and the commit message is different: see https://github.com/deepset-ai/haystack-core-integrations/commit/63738bddfd795edc7b3608ef6290ddfe24be6e38. It includes "update changelog for" (lowercase).
- update cliff.toml to perform a case-insensitive check using [`lower` filter](https://keats.github.io/tera/docs/#lower). …
=> fix: perform case-insensitive check on changelog generation

cliff.toml
- errors in changelog generation: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/14259834586/job/39968917378
- fix the cliff.toml configuration
I finally found a simple way to test it locally:
- installation: `brew install git-cliff`
- run: `git-cliff --config=cliff.toml --include-path "integrations/nvidia/**/*" --tag-pattern "integrations/nvidia-v*"`
Seems to work correctly now.
- I've used one of the [conventional …
=> fix: fix changelog generation

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py, integrations/google_ai/tests/generators/test_gemini.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/gemini.py, integrations/google_vertex/tests/test_gemini.py
- Related to https://github.com/deepset-ai/haystack-core-integrations/issues/1440#issue-2881165596
- Replace gemini-pro by gemini-2.0-flash in tests
- Replace gemini-1.5-pro by gemini-2.0-flash in tests and code example
- Replace gemini-1.5-flash by gemini-2.0-flash in tests
The tests are mocking the model call so it doesn't really change the behavior of the test. Still gemini-pro support ends this month and gemini-1.5-flash in September.
- …
=> tests: upgrade gemini models

integrations/chroma/pyproject.toml, integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py
Follow up of https://github.com/deepset-ai/haystack-core-integrations/pull/1618
Make it so the integration works with older versions of chroma
=> fix: Make chroma backwards compatible

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/vertex_chat_generator.py, integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py, integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py, integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py, integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/chat/chat_generator.py, integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py
- In https://github.com/deepset-ai/haystack/pull/9190, we renamed the deserialization utility function
- nightly tests with main are expected to fail for this reason
- use the new function if available, otherwise fall back to the old one
CI; local tests with Haystack main
We don't need to release these changes right now.
In any case, I created an issue describing what we need to do after 2.13.0 release: #1625. …
=> chore: update ChatGenerators with `deserialize_tools_or_toolset_inplace`

integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py, integrations/ollama/src/haystack_integrations/components/generators/ollama/generator.py, integrations/ollama/tests/test_chat_generator.py, integrations/ollama/tests/test_generator.py
- fixes https://github.com/deepset-ai/hayhooks/issues/104
Add streaming_callback to run method of OllamaGenerator and OllamaChatGenerator so streaming works in hayhooks
added tests
=> feat: Add `streaming_callback` to run methods of OllamaGenerator and OllamaChatGenerator

integrations/mcp/examples/hayhooks/pipeline_wrapper.py, integrations/mcp/examples/mcp_sse_client.py, integrations/mcp/examples/mcp_stdio_client.py, integrations/mcp/examples/time_pipeline.py, integrations/mcp/src/haystack_integrations/tools/mcp/mcp_tool.py, integrations/mcp/tests/test_mcp_tool.py
To simplify and standardize the use of MCPTool across different deployment contexts—whether in standalone scripts, sync/async environments, or Hayhooks-based REST deployments. This is achieved by introducing AsyncExecutor and using it for MCPTool invocation. 
- fixes https://github.com/deepset-ai/haystack/issues/9137
- Introduced `AsyncExecutor`: a utility for executing async code in sync contexts, enabling cleaner and safer integration of MCPTool.
- Added `PipelineWrapper` example: a concrete `examples/hayhooks/pipeline_wrapper.py` of deploying MCPTool in a Haystack pipeline using Hayhooks, exposing it as a REST API.
- Enhanced client-server communication and tool invocation with improved logging for easier debugging and observability.
Example hayhooks pipeline wrapper of a time tool in …
=> feat: Add AsyncExecutor in MCPTool, ensure MCPTool works in hayhooks

.github/workflows/CI_stale.yml
We renamed the `community-triage` label to `information-needed` to better communicate its purpose. This label can be applied to issues that need additional information from the user.
Modify stalebot configuration to reflect the new label name. …
=> chore: update label name for stalebot

integrations/mistral/tests/test_mistral_chat_generator.py
- Nightly tests failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/14434845695/job/40474230283
- In this test, we initialize `MistralChatGenerator` with `generation_kwargs={"tool_choice": "any"}`, even if we don't provide tools. In the past, this parameter was ignored and everything worked. Now there have probably been updates to OpenAI (which we use for calling Mistral) and we are getting errors.
- remove `tool_choice` parameter from `test_live_run_streaming`
CI
- I have updated the related issue with new insights and …
=> test: Mistral - remove unneeded `tool_choice` parameter from `test_live_run_streaming`

integrations/stackit/tests/test_stackit_document_embedder.py, integrations/stackit/tests/test_stackit_text_embedder.py
=> fix: Fix Stackit sede tests

integrations/mcp/pydoc/config.yml
Adding MCPToolset to do pydoc.
=> docs: add MCPToolset to do pydoc

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py
We observed "Creating a new trace without a parent span is not recommended for operation `haystack.agent.run`" when running agent only examples - no pipeline. This warning is confusing to users. This fix removes it by adding it to allowed span roots.
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1653
Allow `haystack.agent.run` to be span root 
Manual testing with agent only examples
=> fix: Langfuse - remove warning "Creating a new trace without a parent span is not recommended ..."

integrations/cohere/src/haystack_integrations/components/rankers/cohere/ranker.py, integrations/cohere/tests/test_cohere_ranker.py
- [Nightly tests are failing](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/14786049398/job/41514528760) because the default model has been shutdown: https://docs.cohere.com/docs/deprecations#2024-12-02-rerank-v20
- replace the default model with the suggested one
- remove unused `max_chunks_per_doc parameter`: we were already ignoring this parameter and warning the user. Since I will release a new major version, this seems like a good time to remove this parameter.
CI
It can be considered a breaking change, so I will release a new major version.
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CO …
=> chore!: `CohereRanker` - change default model and remove `max_chunks_per_doc parameter`

integrations/cohere/pyproject.toml, integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py
Update `CohereChatGenerator` to support initialization and run method with a `Toolset`.
* Modified the `tools` parameter of `CohereChatGenerator` to accept either a list of `Tool` objects or a `Toolset` instance.
* Added serialization logic to handle `Toolset` in the `to_dict()` method of `CohereChatGenerator`.
* Updated relevant tests to validate initialization and behavior when using a `Toolset`.
`CohereChatGenerator` can now be initialized with a `Toolset`, streamlining tool configuration:
```python
toolset = Toolset(tools)  # where tools is a list of Tool objects
generator = CohereChatGenerator(api_key="your-key", tools=toolset)
```
Users can now pass a `Toolset` directly, enabling more structured tool management.
Manual tests, Toolset is extensively tested already elsewhere
Please …
=> feat: Add Toolset support to CohereChatGenerator

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py, integrations/langfuse/tests/test_tracer.py
This PR enhances the Langfuse tracing integration for Haystack's `ToolInvoker` component. Previously, the Langfuse span for a `ToolInvoker` step was named after its register pipeline name (e.g., "tool_invoker"). This change updates the span name *after* execution to include the specific tools called and their invocation counts, making traces significantly more informative and aiding observability, especially in complex agentic pipelines.
Here is the trace before:
Here is the trace after:
- Modified `DefaultSpanHandler.handle` in `integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py`.
- Added logic to extract tool names and invocation counts from the `ToolInvoker`'s input `ChatMessage.tool_calls`.
- Utilized `collections.Counter` to aggregate tool counts.
- Updated …
=> feat: Enhance Langfuse ToolInvoker span naming

README.md, integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py
The pgvector document store does not currently report SQL exceptions, which makes debugging difficult. 
Using hayhooks, for example, with this patch, the error goes from this:
```
│ Server error: Pipeline execution failed: The following component failed to run: │
│ Component name: 'indexing:writer'                                               │
│ Component type: 'DocumentWriter'                                                │
│ Error: Could not write documents to PgvectorDocumentStore.                      │
│ You can find the SQL query and the parameters in the debug logs.                │
```
to this:
```
│ Server error: Pipeline execution failed: The following component failed to run:
│ Component name: 'indexing:writer'
│ Component type: 'DocumentWriter'
│ Error: Could not write …
```
=> feat: pgvector - make error messages more informative

integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py, integrations/ollama/tests/test_chat_generator.py
- fixes #1686
Update _handle_streaming_response() to return data in the same format as a non-streaming-response. Specifically:
- use the metadata from the last streaming chunk which has the completion information
- convert the metadata to OpenAI format and insert it into the ChatMesssage (instead of an object outside the replies)
Updated streaming tests to add assertions for metadata `done` and `usage` fields to validata metadata exists and returns usage in OpenAI format.
Here is a comparison of the ollama chat generator with and without streaming callbacks to show the the return values are the same. The linked bug shows the previous value for streaming callbacks.
OllamaChatGenerator without streaming_callback
```
{'replies': [ChatMessage(_role=<ChatRole.ASSISTANT: 'assistant'>, …
```
=> fix: ollama streaming metadata 1686

integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py, integrations/mongodb_atlas/tests/test_document_store.py
- make embedding filed configurable 
We should make this field configurable since we can't assume a data format of our customers. 
Even the sample dataset from mongodb you can use in atlas uses a different key to store embeddings: https://huggingface.co/datasets/MongoDB/embedded_movies
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, …
=> fix: hard coded embedding field for mongodb

integrations/anthropic/tests/test_chat_generator.py
- nightly tests failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/14895585564/job/41837347229
- this is probably related to the recent introduction of [Web search tool](https://docs.anthropic.com/en/docs/build-with-claude/tool-use/web-search-tool)
- fix `test_convert_anthropic_chunk_to_streaming_chunk` to include `server_tool_use` in `mata['usage']`
CI …
=> test: Anthropic - add `server_tool_use` to `usage`

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/utils.py, integrations/amazon_bedrock/tests/test_chat_generator.py, integrations/amazon_bedrock/tests/test_chat_generator_utils.py
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1677
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1680
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1681
**Fixing Multi Tool Calling**
Repairs the expected formatting of the bedrock messages.
Basically if a ChatMessage has multiple Tool Calls in it then the corresponding Tool Result ChatMessage must also contain both tool results. This is currently not possible because the ToolInvoker in Haystack returns a separate ChatMessage per Tool Call no matter if the original Tool Calls came one from one or multiple ChatMessages.
As a workaround, we retroactively repair the bedrock formatted messages to regroup the Tool Results based on how the Tool Calls are grouped. 
This …
=> fix: Fix BedrockChatGenerator to be able to handle multiple tool calls from one response

integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py, integrations/mongodb_atlas/tests/test_document_store.py, integrations/mongodb_atlas/tests/test_fulltext_retrieval.py
- Allows defining an embedding field & content field that is used to load the documents content and embedding. This is particularly helpful for existing indexes that contain some sort of textfield and an embedding
- add a key `content_field` thats used to identify the `content` field of haystack docs while loading 
- apply the loading logic to the embedding vector key mapping `embedding_field`
- remove the unnessary projections. The whole docstore shoud anyways mainly works with haystack (with an exception of the two cases above). Therefore we don't need to remove some keys when we load the same ones. Benefit here is just that for existing datasets, the rest will just end up in the metadata key. 
⚠️ just keep in mind that either you can load the flattened or the `meta` nesting
GH summary: …
=> feat: support custom content field

integrations/amazon_bedrock/pydoc/config.yml, integrations/amazon_bedrock/src/haystack_integrations/components/rankers/amazon_bedrock/__init__.py, integrations/amazon_bedrock/src/haystack_integrations/components/rankers/amazon_bedrock/ranker.py, integrations/amazon_bedrock/tests/test_ranker.py
- Related to https://github.com/deepset-ai/haystack-core-integrations/issues/1544
- Rename BedrockRanker to AmazonBedrockRanker but keep BedrockRanker as an alias inheriting from AmazonBedrockRanker
- Exclude BedrockRanker from pydocs config
- Expose both AmazonBedrockRanker and BedrockRanker in module init file
- Add deprecation warning to BedrockRanker init …
=> refactor: add AmazonBedrockRanker and keep BedrockRanker as alias

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py
- fixes #1673
- Extend error message shown when the model family could not be detected, which means it is unsupported
=> chore: extend error message for unknown model family in AmazonBedrockGenerator

integrations/google_vertex/src/haystack_integrations/components/embedders/google_vertex/document_embedder.py, integrations/google_vertex/src/haystack_integrations/components/embedders/google_vertex/text_embedder.py
- 1699 but only partially, documentation to follow
The VertexAITextEmbedder's docstrings were structured incorrectly, which showed garbled text in the API Reference.
Additionally fixed similar issues in the DocumentEmbedder.
=> docs: fix VertexAI Embedders docstrings

integrations/stackit/pydoc/config.yml
Add currently missing STACKIT Embedders to API Reference.
=> docs: add missing STACKIT Embedders to API Reference

integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/vertex_chat_generator.py, integrations/mistral/src/haystack_integrations/components/generators/mistral/chat/chat_generator.py
- related to https://github.com/deepset-ai/haystack/issues/9366
- Fixing example ChatMessage responses to include TextContent, fix `_name` and `_meta` format.
=> docs: update ChatMessage examples

integrations/langfuse/tests/test_tracing.py
Integration test skipping wasn't working as intended meaning when community members opened PRs that updated Langfuse the tests failed instead of skipped.
Ran tests locally with unset env variables to check they were skipped …
=> test: Update how test skipping works in Langfuse

.github/workflows/amazon_bedrock.yml, integrations/amazon_bedrock/tests/test_chat_generator.py, integrations/amazon_bedrock/tests/test_ranker.py
When working locally with Bedrock, I cannot run integration tests because they are skipped if `AWS_CI_ROLE_ARN` and `AWS_REGION` env vars are not set. `AWS_CI_ROLE_ARN` in particular is specific to Haystack CI. If the AWS account is properly configured and these skip conditions are removed, I can successfully run the integration tests.
- remove skipif condition from integration tests
- cosmetic refinements to GitHub workflow
- local tests
- CI: I have created this PR from a fork and integration tests are correctly skipped (from CI, not from tests code)
In general, I found it hard to skip tests from code programmatically because I think that there are several different legitimate ways to authenticate to AWS. So I'm just relying on the CI for this aspect.
What will happen after this PR?
In …
=> ci: Bedrock - improve worfklow; skip tests from CI

integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/retriever.py, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/filters.py, integrations/qdrant/src/haystack_integrations/document_stores/qdrant/migrate_to_sparse.py, integrations/qdrant/tests/test_document_store.py
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1786#issuecomment-2909698240
Deepcopy the returned client params in `_prepare_client_params` to prevent changing the original class attributes.
This specifically only occurs when you run a hosted version of QDrant (but not when running the in memory version), initialize the client and then run `to_dict`.
Added a unit test …
=> fix: Fix exposing Qdrant api-key in `metadata` field when running `to_dict`

.github/workflows/google_vertex.yml, integrations/google_vertex/pyproject.toml
- fixes #1795
- add CI job
- remove incorrect dependency and pinned `haystack-ai>=2.11.0` (the integration uses `StreamingCallbackT` that was introduced in that version)
CI
This is not a breaking change -> I will release a bugfix version. …
=> build: add pins for Vertex

.github/workflows/optimum.yml, integrations/optimum/pyproject.toml, integrations/optimum/tests/test_optimum_document_embedder.py, integrations/optimum/tests/test_optimum_text_embedder.py
- fixes #1803
- pin optimum
- add CI job
- modify some tests to make them faster and proper unit tests
- test with python 3.13 (now onnx supports it) 
CI
Not breaking -> bugfix release
=> build: add pins for Optimum

.github/workflows/CI_license_compliance.yml
- failing license compliance: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/15288339909/job/43003064649 - this happens because a new version of ollama-python was released but they wrongly removed the MIT specification from pyproject.toml (I opened an issue for this: https://github.com/ollama/ollama-python/issues/522)
- put Ollama in the list of exclusions (and remove Cohere, that now comes with the correct license specification)
- refactor the workflow to also run when it is modified
CI
- I have updated the related issue with …
=> chore: review license compliance workflow

.github/workflows/unstructured.yml, integrations/unstructured/pyproject.toml
- fixes #1809 
- "haystack-ai>=2.0.0",
- "unstructured>=0.15.0",
- "unstructured-client>=0.21.0"
=> build: pinning `unstructured` to lowest working versions

integrations/cohere/pyproject.toml, integrations/cohere/src/haystack_integrations/components/embedders/cohere/text_embedder.py, integrations/cohere/tests/test_text_embedder.py
- fixes #1508 
Added `run_async` conversion for `CohereTextEmbedder`
- Added a new test case for testing asynio
- Also update existing testcase
=> feat: add run_async support for CohereTextEmbedder

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py
The newly released Google GenAI Haystack integration includes a `GoogleGenAIChatGenerator` component that wasn't included in Langfuse's list of supported chat generators. This meant that Google GenAI chat interactions weren't receiving proper generation-level tracing and metadata extraction in Langfuse, limiting observability for users of this integration.
- **Core component**: Added `GoogleGenAIChatGenerator` to `_SUPPORTED_CHAT_GENERATORS` list
- **Key features**: 
- Enables generation-level spans for `GoogleGenAIChatGenerator`
- Provides proper token usage and model metadata extraction
- Ensures consistent tracing behavior across all supported chat generators
- **Integration**: Google GenAI chat components now receive the same detailed tracing treatment as other supported generators
- …
=> feat: Add detailed tracing for GoogleGenAIChatGenerator

integrations/pinecone/tests/test_filters.py
- fixes #590
- re-enable the tests that were skipped due to Pinecone handling of null values. They made progress on this aspect and the tests run successfully.
CI
=> test: Pinecone - reenable tests for `comparison_not_equal` and `or_operator`

integrations/langfuse/pyproject.toml
- #1903: the new Langfuse SDK is not compatible with the current integration
- temporarily pin langfuse<3.0.0
CI
=> chore: pin langfuse<3.0.0

CONTRIBUTING.md, README.md, integrations/amazon_bedrock/README.md, integrations/amazon_sagemaker/README.md, integrations/anthropic/README.md, integrations/chroma/README.md, integrations/cohere/README.md, integrations/deepeval/README.md, integrations/elasticsearch/README.md, integrations/google_vertex/README.md, integrations/langfuse/README.md, integrations/mongodb_atlas/README.md, integrations/nvidia/README.md, integrations/ollama/README.md, integrations/opensearch/README.md, integrations/pgvector/README.md, integrations/pinecone/README.md, integrations/qdrant/README.md, integrations/ragas/README.md, integrations/unstructured/README.md, integrations/weaviate/README.md
- update all mentions of Hatch scripts in Markdown files to reflect the new scripts introduced in #1898
=> chore: update md files for new hatch scripts

.github/workflows/pgvector.yml, integrations/pgvector/pyproject.toml, integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/embedding_retriever.py, integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/keyword_retriever.py, integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py, integrations/pgvector/src/haystack_integrations/document_stores/pgvector/filters.py, integrations/pgvector/tests/test_document_store_async.py
(this means testing with all dependencies installed, differently from `hatch run lint:typing` that did not install dependencies)
- fix the type errors by refactoring the Document Store a bit
- introduce stricter configuration in pyproject.toml (and fix small errors)
CI
- I added unit tests and updated …
=> fix: fix pgvector types + add py.typed

.github/workflows/elasticsearch.yml, integrations/elasticsearch/pyproject.toml, integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/bm25_retriever.py, integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/embedding_retriever.py, integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py
=> fix: fix Elasticsearch types + add py.typed

integrations/google_genai/src/haystack_integrations/components/embedders/google_genai/document_embedder.py, integrations/google_genai/src/haystack_integrations/components/embedders/google_genai/text_embedder.py, integrations/google_genai/src/haystack_integrations/components/generators/google_genai/chat/chat_generator.py, integrations/google_genai/tests/test_document_embedder.py, integrations/google_genai/tests/test_text_embedder.py
- GEMINI_API_KEY is used in all the docs
=> chore: Use GEMINI_API_KEY as default env var for the api key (in addition to GOOGLE_API_KEY)

.github/workflows/instructor_embedders.yml
- nightly tests failure: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/15623348070/job/44027576451
- in short, sentencepiece (a dependency of sentence-transformers) cannot be installed on Windows with Python 3.13: see https://github.com/google/sentencepiece/issues/1111 and other similar issues
- (Instructor embedder should be moved to staging in a near future: #1883)
- do not test this integration with Windows + Python 3.13
CI …
=> chore: stop testing instructor-embedders on windows + python 3.13

integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py, integrations/anthropic/tests/test_chat_generator.py
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1947
Updates `_convert_streaming_chunks_to_chat_message` to properly handle when a Tool Call is made with no arguments. Previoulsy we were getting a JSON decode error when `arguments=""`. Now we properly check for this case and set the arguments to `{}`.
Added a unit test and an integration test …
=> fix: `AnthropicChatGenerator` now properly can call tools that have no arguments when streaming is enabled

.github/workflows/unstructured.yml, integrations/unstructured/pyproject.toml, integrations/unstructured/src/haystack_integrations/components/converters/unstructured/converter.py
- run `hatch run test:types ` and fix type errors
- introduce stricter configuration in pyproject.toml (and fix small errors)
CI
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, …
=> fix: fix Unstructured types + add py.typed

.github/utils/deepset_sync.py, .github/workflows/sync_code_to_deepset.yml
- similar to https://github.com/deepset-ai/haystack/pull/9555
I am proposing a github workflow and a small script to sync haystack contents with a deepset workspace whenever code is pushed to main. This will help us build MCP/Agentic features on top of the codebase and it is needed for the documentation.
Before the action is merged, we need to add a deepset api key to the repository secrets.
@julian-risch and @agnieszka-m have more context about this.
Manual testing.
- I added unit tests …
=> docs: sync code to deepset

integrations/pgvector/examples/embedding_retrieval.py, integrations/pgvector/examples/hybrid_retrieval.py
In the past, pgvector used the `ankane/pgvector`docker image.
Now it needs `pgvector/pgvector` (with a mandatory tag; latest does not exist).
I've already updated docs and the integration page.
- change the docker image in examples
=> chore: pgvector - update docker image in examples

.github/workflows/snowflake.yml, integrations/snowflake/pyproject.toml, integrations/snowflake/src/haystack_integrations/components/retrievers/snowflake/snowflake_table_retriever.py
=> fix: fix Snowflake types + add py.typed

.github/workflows/optimum.yml, integrations/optimum/pyproject.toml, integrations/optimum/src/haystack_integrations/components/embedders/optimum/_backend.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/optimum_document_embedder.py, integrations/optimum/src/haystack_integrations/components/embedders/optimum/optimum_text_embedder.py
=> fix: fix Optimum types + add py.typed

.github/workflows/stackit.yml, integrations/stackit/pyproject.toml
(this means testing with all dependencies installed, differently from `hatch run lint:typing` that did not install dependencies) -> no type errors in this integration, already OK
- introduce stricter configuration in pyproject.toml -> no type errors in this integration, already OK
CI
- I added unit …
=> chore: stackit - improve type checking + add py.typed

integrations/ollama/pyproject.toml, integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py, integrations/ollama/tests/test_chat_generator.py
- fixes #1823
- pass `component_info` to `StreamingChunk` in `OllamaChatGenerator`
- other small improvements to tests and types
CI; new test
=> feat: pass `component_info` to `StreamingChunk` in `OllamaChatGenerator`

.github/workflows/openrouter.yml, integrations/openrouter/pyproject.toml, integrations/openrouter/src/haystack_integrations/components/generators/openrouter/chat/chat_generator.py
=> fix: fix openrouter types + add py.typed

integrations/mcp/src/haystack_integrations/tools/mcp/mcp_toolset.py
Fixes a garbage collection issue that prevented users from properly combining multiple MCPToolset instances using the inline syntax `tools.add(MCPToolset(...))`. When MCPToolset objects were created inline and added to another toolset, Python's garbage collector would prematurely destroy the temporary toolset objects, closing their MCP connections and leaving orphaned tools that failed with "Not connected to an MCP server" errors.
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1986
- Use`owner_toolset` parameter to maintain strong references to prevent garbage collection  
```python
server_info = SSEServerInfo(url="https://mcp.amap.com/sse?key=xxx")
htw_server_info = SSEServerInfo(url="http://127.0.0.1:8333/sse")
tools = MCPToolset(server_info=htw_server_info) …
```
=> fix: Prevent MCPToolset GC during toolset add

integrations/amazon_bedrock/pyproject.toml, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/utils.py, integrations/amazon_bedrock/tests/test_chat_generator.py, integrations/amazon_bedrock/tests/test_chat_generator_utils.py
- fixes #1819
- pass `component_info` to `StreamingChunk` in `AmazonBedrockChatGenerator`
CI, extended existing tests
=> feat: pass `component_info` to `StreamingChunk` in `AmazonBedrockChatGenerator`

integrations/anthropic/pyproject.toml, integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py, integrations/anthropic/tests/test_chat_generator.py
- fixes #1820 
pass `component_info` to `StreamingChunk` in `AnthropicChatGenerator`
Updated the test
=> feat: pass `component_info`to `StreamingChunk` in `AnthropicChatGenerator`

integrations/cohere/pyproject.toml
- fixes failing tests due to 5.16 release of cohere
=> fix: Pin cohere to less than 5.16

integrations/watsonx/tests/test_chat_generator.py, integrations/watsonx/tests/test_document_embedder.py, integrations/watsonx/tests/test_generator.py, integrations/watsonx/tests/test_text_embedder.py
Removed some integration tests and modified others to use less tokens. This is in response to us passing our quota for watsonx usage.
=> ci: Reduce impact of integration tests for Watsonx integration

integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/chat/chat_generator.py, integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/generator.py, integrations/llama_cpp/tests/test_chat_generator.py
- fixes  #730: streaming support only added for ChatGenerator. I don't think we should add new features to Generator.
- fixes #1825
- fixes #2075
- introduce streaming support for `LlamaCppChatGenerator`, using the new `StreamingChunk` and passing `ComponentInfo`
- CI, several new tests
- locally tested with `print_streaming_chunk`: both standard completions and tool calls are correctly printed
Don't get scared by the size of this PR. Most of the code consist of llama.cpp chunk objects for tests.
- I have updated the related issue with new insights and …
=> feat: `LlamaCppChatGenerator` streaming support

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py
As discussed internally, show a warning to suggest users to switch to Google GenAI (only for components available in Google GenAI)
=> chore: Google AI - suggest users to switch to Google GenAI

integrations/github/tests/test_file_editor_tool.py
- [nightly test failure](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/16610241446/job/46991677919) due to new `tool_invoker_kwargs` parameter introduced in Haystack 2.16.0 for Agent
- drop the parameter in the serialization test to keep compatibility with Haystack 2.12.0 (minum supported version)
CI
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: …
=> test: fix GitHub test

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/utils.py, integrations/amazon_bedrock/tests/test_chat_generator.py, integrations/amazon_bedrock/tests/test_chat_generator_utils.py
- fixes #2107
- update `_convert_streaming_chunks_to_chat_message` to properly handle when a Tool Call is made with no arguments.
- this is basically a copy of #1950, adapted for Bedrock
CI, new tests
Locally tested with Cohere model too. …
=> fix: `AmazonBedrockChatGenerator` - fix bug with streaming + tool calls with no arguments

integrations/mcp/src/haystack_integrations/tools/mcp/mcp_tool.py, integrations/mcp/tests/test_mcp_integration.py, integrations/mcp/tests/test_mcp_server_info.py, integrations/mcp/tests/test_mcp_timeout_reconnection.py
Fixes critical issue where MCP SSE connections timeout after 5-10 minutes of idle time, causing tool invocations to fail with `anyio.ClosedResourceError` wrapped in unhelpful empty `MCPInvocationError` messages, requiring manual MCPTool recreation.
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/2054
- Added automatic reconnection logic with exponential backoff to `MCPClient.call_tool()` for SSE/HTTP transports
- Enhanced error handling to provide meaningful messages even when underlying exceptions have empty string representations  
- Created integration test that simulates real SSE timeout scenarios by killing/restarting server processes
```python
try:
result = tool.invoke(data="some_data")
except MCPInvocationError as e:
print(e)  # Empty error message: "Failed …
```
=> fix: ClientSession expires after idle periods causing ClosedResourceError with empty error message

integrations/google_genai/src/haystack_integrations/components/generators/google_genai/chat/chat_generator.py, integrations/google_genai/tests/test_chat_generator.py
- fixes #2138
- use the same mapped `finish_reason` in streaming and non-streaming cases
CI, new assertions
This is a breaking change and I will release a new major version
=> fix!: `GoogleGenAIChatGenerator` - align `finish_reason` between streaming and non-streaming

integrations/google_genai/pyproject.toml, integrations/google_genai/src/haystack_integrations/components/generators/google_genai/chat/chat_generator.py
Add the optional `aiohttp` dependency which was recently used more often in google's update to google-genai in version 2.19.0 (released on August 6th).  See diff [here](https://github.com/googleapis/python-genai/compare/v1.28.0...v1.29.0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L40)
Previously we were able to run the async client without the optional dependency (<1.29.0) but now it is required so we add it.
It's listed as an optional dependency in their pyproject.toml
```
[project.optional-dependencies]
aiohttp = ["aiohttp<4.0.0"]
```
Existing tests …
=> fix: Add optional `aiohttp` to google-genai integration

integrations/llama_stack/pyproject.toml
- fixes failures due to openai's release of 1.99.3
We pin openai here since we are already pinning llama-stack so even when they fix the issue we won't be able to benefit from it unless we also unpin llama stack.
Existing tests
=> fix: Pin openai to `<=1.99.2` avoid errors in Llama Stack integration

integrations/amazon_bedrock/src/haystack_integrations/components/embedders/amazon_bedrock/document_embedder.py, integrations/amazon_bedrock/src/haystack_integrations/components/embedders/amazon_bedrock/text_embedder.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py
This PR adds the framework name into User-Agent header of Bedrock API call
This change only append the framework name `haystack` into the User-Agent header field for Bedrock API call, which can be used to collect the usage. Similar change had been made to other framework such as [langchain](https://github.com/langchain-ai/langchain-aws/pull/558)
Run through all tests.  …
=> chore: Add framework name into UserAgent header for bedrock integration

.github/workflows/llama_cpp.yml, integrations/llama_cpp/pyproject.toml
Nightly tests failing on macOS: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/17364348515/job/49288820099
CMake error: OpenMP not found
This likely happens because [new GitHub macOS runners](https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/) are not well configured or lack the dependency.
- Use pre-built wheels on macOS by adding a custom index (llama-cpp-python provides these wheels)
- on macOS, test with Python 3.10 and 3.12 because wheels are only available for python>=3.10, <=3.12
CI
This would not change things for end users. I have not seen many users reporting issues on this specific topic on llama-cpp-python and I would expect users to be able to install/configure …
=> ci: download pre-built wheels for llama-cpp-python on macOS

integrations/jina/pydoc/config.yml, integrations/jina/pyproject.toml, integrations/jina/src/haystack_integrations/components/embedders/jina/__init__.py, integrations/jina/src/haystack_integrations/components/embedders/jina/document_image_embedder.py, integrations/jina/tests/test_document_image_embedder.py
- part of #2135
This PR adds image embedding support to the Jina integration, enabling users to embed images using Jina's 
multimodal models (jina-clip series and jina-embeddings-v4). The implementation follows established 
patterns from the SentenceTransformersDocumentImageEmbedder and provides a consistent API for 
document-based image embedding.
**Key Features Added:**
- New `JinaDocumentImageEmbedder` component for processing images from Document metadata file paths
- Support for multiple Jina multimodal models: jina-clip-v1, jina-clip-v2, and jina-embeddings-v4
- Automatic image format detection and base64 encoding for API transmission
- PDF page extraction and conversion to images using existing Haystack utilities
- Configurable embedding dimensions for jina-embeddings-v4 model
- …
=> feat: add `JinaDocumentImageEmbedder`

integrations/cohere/README.md, integrations/cohere/examples/cohere_generation.py, integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py, integrations/cohere/src/haystack_integrations/components/generators/cohere/generator.py, integrations/cohere/tests/test_chat_generator.py, integrations/cohere/tests/test_chat_generator_async.py, integrations/cohere/tests/test_generator.py
Nightly Cohere tests are failing because the current default (`command-r-plus`) has been removed.
https://github.com/deepset-ai/haystack-core-integrations/actions/runs/17782605524/job/50544377520
It looks like `command-r-plus` was accidentally set as the default in #2157. Previously, #1691 had already set the default to `command-r-08-2024`.
**Why `command-r-08-2024`?**
- active model
- mid-level pricing, aligned with our standard Cohere defaults, while `command-r-plus` (removed) and `command-a` (newer) have higher prices
More information:
https://docs.cohere.com/docs/models#command
https://cohere.com/pricing
https://docs.cohere.com/changelog/command-gets-refreshed
- revert default model to `command-r-08-2024`
CI …
=> chore: revert default model to `command-r-08-2024`

.github/workflows/CI_readme_sync.yml, .github/workflows/amazon_bedrock.yml, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py, integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/utils.py, integrations/amazon_bedrock/tests/test_chat_generator.py, integrations/amazon_bedrock/tests/test_chat_generator_utils.py
- fixes #1685
- introduce a `guardrail_config` init parameter to allow users to pass a configuration for a guardrail they have created in Bedrock
- make sure this works properly both in streaming and non-streaming mode
- if available, store the guardrail `trace` in `message.meta`
- new unit tests
- new parametrized integration test that references to a guardrail I have created, that blocks investment topics …
=> feat: support AWS Bedrock Guardrails in `AmazonBedrockChatGenerator`

integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py, integrations/elasticsearch/tests/test_bm25_retriever.py, integrations/elasticsearch/tests/test_document_store.py, integrations/elasticsearch/tests/test_embedding_retriever.py
- fixes #2245 
- Adds API token authentication support to the `ElasticsearchDocumentStore` 
- Supports multiple authentication methods:
- Environment Variables: Support for ELASTIC_API_KEY and ELASTIC_API_KEY_ID environment variables
- Secret Objects: Direct parameter support for api_key and api_key_id as Secret objects
- Base64 Encoded Keys: Support for single base64-encoded API keys containing both ID and secret
- No Authentication: Graceful fallback to unauthenticated connections when no credentials are provided
- unit tests and manual verification
- tested Serialization and Deserialization with env vars
- tes auth with SecretToken string
- test with single API key validation
- error handling, when only API_ID is given and no API_TOKEN
- I did test connecting to locally Docker ES setup …
=> feat!: adding `api_token` and `apit_token_id` support to `ElasticSearchDocumentStore`

.github/workflows/ollama.yml
Use `nohup` when serving ollama to increase stability of tests.
=> ci: Try using nohup to serve ollama

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py, integrations/google_ai/tests/generators/chat/test_chat_gemini.py
The `gemini-1.5` models have been deprecated (more details [here](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions)). So we update the default model to be `gemini-2.0-flash` for the `GoogleAIGeminiChatGenerator` and update the tests to use the new model.
Updated existing tests. …
=> fix: Update default model to `gemini-2.0-flash` in `GoogleAIGeminiChatGenerator`

integrations/mcp/src/haystack_integrations/tools/mcp/mcp_tool.py, integrations/mcp/src/haystack_integrations/tools/mcp/mcp_toolset.py
- fixes #2337
Update docs for MCPTool and MCPToolset to mention, that SSE is deprecated.
Manual
No functionality, just comment
- ~~I added unit tests~~  and updated the docstrings
=> docs: recommend Streamable HTTP instead of SSE

integrations/amazon_bedrock/src/haystack_integrations/components/downloaders/s3/s3_downloader.py, integrations/amazon_bedrock/tests/test_s3_downloader.py
This PR is meant to replace #2336 and #2339, to support customization without sacrificing UX 
- add `s3_key_generation_function` init param to customize S3 key generation
- if provided, the function will be invoked to generate the S3 key (otherwise we'll keep using `Document.meta[file_name_meta_key]`)
- if `S3_DOWNLOADER_PREFIX` env var is set, its value will be automatically prefixed to the generated S3 key
CI, new unit and integration tests …
=> feat: S3Downloader - add `s3_key_generation_function` param to customize S3 key generation

integrations/pinecone/tests/test_document_store.py, integrations/pinecone/tests/test_document_store_async.py
These tests have been failing repeatedly: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/18266359971/job/52001249975
I tried a lot with different combinations of vectors but I realized that while the best vectors are returned, order is not guaranteed ([Pinecone forum](https://community.pinecone.io/t/pinecone-return-results-consistency/5389/2))
- relax the test to only check that the correct docs are returned (not the order)
CI …
=> test: Pinecone - relax flaky test

.github/workflows/amazon_bedrock.yml
I noticed that lately we were not running integration tests for Bedrock nightly: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/18298196689/job/52100828792
This happens because authentication only runs if `github.event.pull_request.head.repo.full_name == github.repository`.
This is false for scheduled events, which are not PRs.
- adjust the workflow to always run authentication (and consequently integration tests) in nightly runs
We'll see tonight.
- I added unit …
=> ci: make Bedrock integration tests run nightly
