deepset-ai/haystack-core-integrations

nodes/text2speech/tests/test_nodes.py
nodes/text2speech/text2speech/answer_to_speech.py
nodes/text2speech/text2speech/document_to_speech.py
nodes/text2speech/text2speech/utils/text_to_speech.py

After the migration, many imports were left broken. This PR fixes these imports.

fix: remove audio primitives and fix imports

---

stores/milvus-documentstore/README.md

The same should be added to the docs page

Add `MilvusDocumentStore` usage example

---

.github/labeler.yml

Add labeler configuration

---

document_stores/chroma/pyproject.toml
document_stores/chroma/src/chroma_haystack/document_store.py
document_stores/chroma/tests/test_document_store.py

Blocked on https://github.com/deepset-ai/haystack/pull/6318

[chroma] Update the code to account for the latest changes in haystack Document

---

.github/workflows/instructor_embedders.yml
integrations/chroma/example/example.py
integrations/chroma/pyproject.toml
integrations/chroma/src/chroma_haystack/document_store.py
integrations/chroma/src/chroma_haystack/errors.py
integrations/chroma/src/chroma_haystack/retriever.py
integrations/chroma/tests/test_document_store.py
integrations/instructor-embedders/instructor_embedders/embedding_backend/instructor_backend.py
integrations/instructor-embedders/instructor_embedders/instructor_document_embedder.py
integrations/instructor-embedders/instructor_embedders/instructor_text_embedder.py
integrations/instructor-embedders/tests/test_instructor_document_embedder.py
integrations/unstructured/fileconverter/README.md
integrations/unstructured/fileconverter/src/unstructured_fileconverter_haystack/fileconverter.py

replace `from hasytack.preview` with `from haystack`

update import paths

---

.github/labeler.yml

chore: add missing integrations to the labeller

---

.github/labeler.yml
.github/workflows/google_vertex.yml
README.md
integrations/google-vertex/LICENSE.txt
integrations/google-vertex/README.md
integrations/google-vertex/pyproject.toml
integrations/google-vertex/src/google_vertex_haystack/__about__.py
integrations/google-vertex/src/google_vertex_haystack/__init__.py
integrations/google-vertex/src/google_vertex_haystack/generators/__init__.py
integrations/google-vertex/src/google_vertex_haystack/generators/captioner.py
integrations/google-vertex/src/google_vertex_haystack/generators/code_generator.py
integrations/google-vertex/src/google_vertex_haystack/generators/gemini.py
integrations/google-vertex/src/google_vertex_haystack/generators/image_generator.py
integrations/google-vertex/src/google_vertex_haystack/generators/question_answering.py
integrations/google-vertex/src/google_vertex_haystack/generators/text_generator.py
integrations/google-vertex/tests/__init__.py
integrations/google-vertex/tests/test_captioner.py
integrations/google-vertex/tests/test_code_generator.py
integrations/google-vertex/tests/test_image_generator.py
integrations/google-vertex/tests/test_question_answering.py
integrations/google-vertex/tests/test_text_generator.py

Add 6 new components to integrate with Google Vertex AI.
Components added:
* `GeminiGenerator`
* `VertexAIImageGenerator`
* `VertexAITextGenerator`
* `VertexAIImageCaptioner`
* `VertexAICodeGenerator`
* `VertexAIImageQA`
Chat generators will be added with later PRs.

Add Google Vertex AI integration

---

.github/labeler.yml

Apply labels also when editing the workflow files

ci: fix labeller config

---

integrations/chroma/example/example.py
integrations/chroma/src/chroma_haystack/document_store.py

Fixes #123 
Also fix the example code. Colab will be fixed after the integration release.

fix: update to the latest Document format

---

integrations/ollama/example/example.py
integrations/ollama/pyproject.toml

Example of use of OllamaGenerator in a pipeline similar to https://docs.haystack.deepset.ai/v2.0/docs/huggingfacelocalgenerator#in-a-pipeline

add example of OllamaGenerator

---

integrations/ollama/LICENSE.txt

The license file was missing, so I'm adding it.

Ollama: add license

---

integrations/pinecone/pyproject.toml

Temporary fix for #223
(failing tests: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7549115594/job/20552526533)

Pin `pinecone-client<3`

---

integrations/llama_cpp/examples/llama_cpp_generator_example.py
integrations/llama_cpp/examples/rag_pipeline_example.py
integrations/llama_cpp/pyproject.toml
integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/__init__.py
integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/generator.py
integrations/llama_cpp/tests/test_generator.py

Mount llama_cpp in haystack_integrations

---

integrations/unstructured/pyproject.toml

Unpinning unstructured since latest version 0.12.2 passes with the tests

Unpin unstructured

---

.github/workflows/weaviate.yml
integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py
integrations/weaviate/tests/test_document_store.py

A test is skipped since we have a working `write_documents()` as of now.

Implement `count_document` for WeaviateDocumentStore

---

integrations/google_ai/pyproject.toml
integrations/google_ai/src/google_ai_haystack/__init__.py
integrations/google_ai/src/google_ai_haystack/generators/__init__.py
integrations/google_ai/src/haystack_integrations/components/generators/google_ai/__init__.py
integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py
integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py
integrations/google_ai/tests/generators/chat/test_chat_gemini.py
integrations/google_ai/tests/generators/test_gemini.py

Part of https://github.com/deepset-ai/haystack-core-integrations/issues/199

refact!: adjust import paths

---

integrations/uptrain/pyproject.toml

fix: Broken version pattern in `pyproject.toml`

---

.github/ISSUE_TEMPLATE/breaking-change-proposal.md

* Emphasize "Docstrings"
* Make a priority order
* Add more items to the list

Update Breaking Change Proposal issue template

---

.github/workflows/elasticsearch.yml
integrations/elasticsearch/pydoc/config.yml
integrations/elasticsearch/pyproject.toml

Fixes [#305](https://github.com/deepset-ai/haystack-core-integrations/issues/305)

elasticsearch: generate api docs

---

.github/workflows/cohere.yml
integrations/cohere/pydoc/config.yml
integrations/cohere/pyproject.toml

Fixes [#304](https://github.com/deepset-ai/haystack-core-integrations/issues/304)

cohere: generate api docs

---

.github/workflows/astra.yml
integrations/astra/pydoc/config.yml
integrations/astra/pyproject.toml

Fixes https://github.com/deepset-ai/haystack-core-integrations/issues/303

astra: generate api docs

---

.github/workflows/opensearch.yml
integrations/opensearch/pydoc/config.yml
integrations/opensearch/pyproject.toml

OpenSearch: generate API docs

---

.github/workflows/pgvector.yml
integrations/pgvector/pydoc/config.yml
integrations/pgvector/pyproject.toml

Pgvector: generate API docs

---

.github/workflows/ollama.yml
integrations/ollama/pydoc/config.yml
integrations/ollama/pyproject.toml

Fixes https://github.com/deepset-ai/haystack-core-integrations/issues/312

ollama: generate api docs

---

integrations/pgvector/examples/example.py
integrations/pgvector/pyproject.toml

Part of #142
Simple example on Pgvector Document Store.

Pgvector: add an example

---

.github/workflows/weaviate.yml
integrations/weaviate/pydoc/config.yml
integrations/weaviate/pyproject.toml

Generate API docs for weaviate subproject

feat: Generate weaviate API docs

---

integrations/cohere/tests/test_cohere_chat_generator.py
integrations/cohere/tests/test_cohere_generators.py

Fixing failing tests after the release of Haystack 2-beta6

fix: update to latest haystack-ai version

---

.github/workflows/google_vertex.yml
integrations/google_vertex/pydoc/config.yml
integrations/google_vertex/pyproject.toml

Fixes https://github.com/deepset-ai/haystack-core-integrations/issues/307

google_vertex: create api docs

---

.github/workflows/pinecone.yml
integrations/pinecone/pydoc/config.yml
integrations/pinecone/pyproject.toml

ci: Generate API docs for Pinecone

---

.github/workflows/amazon_bedrock.yml
integrations/amazon_bedrock/pydoc/config.yml
integrations/amazon_bedrock/pyproject.toml

Fixes https://github.com/deepset-ai/haystack-core-integrations/issues/302

amazon bedrock: generate api docs

---

.github/workflows/qdrant.yml
integrations/qdrant/pydoc/config.yml
integrations/qdrant/pyproject.toml

ci: Generate API docs for Qdrant

---

.github/workflows/instructor_embedders.yml
integrations/instructor_embedders/pydoc/config.yml
integrations/instructor_embedders/pyproject.toml

feat: Generate API docs

---

.github/workflows/gradient.yml
integrations/gradient/pydoc/config.yml
integrations/gradient/pyproject.toml

Fixes https://github.com/deepset-ai/haystack-core-integrations/issues/308

gradient: generate api docs

---

integrations/uptrain/example/example.py
integrations/uptrain/pydoc/config.yml
integrations/uptrain/pyproject.toml
integrations/uptrain/src/haystack_integrations/components/evaluators/__init__.py
integrations/uptrain/src/haystack_integrations/components/evaluators/uptrain/__init__.py
integrations/uptrain/src/haystack_integrations/components/evaluators/uptrain/evaluator.py
integrations/uptrain/src/haystack_integrations/components/evaluators/uptrain/metrics.py
integrations/uptrain/tests/test_evaluator.py
integrations/uptrain/tests/test_metrics.py

This will need updates to the docs, tutorials, etc, once a new build is released.

refactor!: Standardize namespace and add CI for API docs

---

integrations/astra/README.md
integrations/astra/examples/example.py
integrations/astra/examples/pipeline_example.py
integrations/astra/src/haystack_integrations/components/retrievers/astra/__init__.py
integrations/astra/src/haystack_integrations/components/retrievers/astra/retriever.py
integrations/astra/tests/test_retriever.py

part of #394 
for consistency, AstraRetriever -> AstraEmbeddingRetriever

Astra: rename retriever

---

integrations/pinecone/examples/example.py

Update outdated imports in the Pinecone example

Pinecone: fix imports in example

---

integrations/jina/src/haystack_integrations/components/embedders/jina/document_embedder.py
integrations/jina/src/haystack_integrations/components/embedders/jina/text_embedder.py
integrations/jina/tests/test_document_embedder.py
integrations/jina/tests/test_text_embedder.py

Jina: update secrets management

---

integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/__init__.py
integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/bm25_retriever.py
integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py
integrations/weaviate/tests/test_bm25_retriever.py
integrations/weaviate/tests/test_document_store.py

Add `WeaviateBM25Retriever`

---

integrations/jina/src/haystack_integrations/components/embedders/jina/document_embedder.py
integrations/jina/src/haystack_integrations/components/embedders/jina/text_embedder.py

See https://github.com/deepset-ai/haystack-core-integrations/pull/411#discussion_r1490713379

Jina - remove dead code

---

integrations/gradient/pyproject.toml
integrations/gradient/src/haystack_integrations/components/embedders/gradient/gradient_document_embedder.py
integrations/gradient/src/haystack_integrations/components/embedders/gradient/gradient_text_embedder.py
integrations/gradient/src/haystack_integrations/components/generators/gradient/base.py
integrations/gradient/tests/test_gradient_document_embedder.py
integrations/gradient/tests/test_gradient_text_embedder.py

Gradient - new secrets management

---

integrations/google_ai/pyproject.toml
integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py
integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py
integrations/google_ai/tests/generators/chat/test_chat_gemini.py
integrations/google_ai/tests/generators/test_gemini.py

Google AI - new secrets management

---

.github/workflows/ollama.yml
.github/workflows/unstructured.yml

- fixes #363 
Standardize global working-directory for integration tests
Fixes inconsistency by setting global working-directory for ollama and unstructured workflows.

Updated integration tests workflow to set global working directory

---

integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py

- fixed a typo docstring
- align arg with docstring param
- converted some methods to `@staticmethod`

small improvements

---

integrations/amazon_bedrock/pydoc/config.yml
integrations/amazon_sagemaker/pydoc/config.yml
integrations/astra/pydoc/config.yml
integrations/chroma/pydoc/config.yml
integrations/cohere/pydoc/config.yml
integrations/deepeval/pydoc/config.yml
integrations/elasticsearch/pydoc/config.yml
integrations/fastembed/pydoc/config.yml
integrations/google_ai/pydoc/config.yml
integrations/google_vertex/pydoc/config.yml
integrations/gradient/pydoc/config.yml
integrations/instructor_embedders/pydoc/config.yml
integrations/jina/pydoc/config.yml
integrations/llama_cpp/pydoc/config.yml
integrations/mistral/pydoc/config.yml
integrations/mongodb_atlas/pydoc/config.yml
integrations/ollama/pydoc/config.yml
integrations/opensearch/pydoc/config.yml
integrations/pgvector/pydoc/config.yml
integrations/pinecone/pydoc/config.yml
integrations/qdrant/pydoc/config.yml
integrations/ragas/pydoc/config.yml
integrations/unstructured/pydoc/config.yml
integrations/uptrain/pydoc/config.yml
integrations/weaviate/pydoc/config.yml

This PR will also push the docs to Readme

fix order of API docs

---

integrations/astra/src/haystack_integrations/document_stores/astra/astra_client.py
integrations/astra/src/haystack_integrations/document_stores/astra/document_store.py
integrations/astra/tests/test_document_store.py

Astra: fix integration tests

---

integrations/instructor_embedders/src/haystack_integrations/components/embedders/instructor_embedders/instructor_document_embedder.py
integrations/instructor_embedders/src/haystack_integrations/components/embedders/instructor_embedders/instructor_text_embedder.py
integrations/instructor_embedders/tests/test_instructor_document_embedder.py
integrations/instructor_embedders/tests/test_instructor_text_embedder.py

part of https://github.com/deepset-ai/haystack/issues/7000
- I refactored the Embedders according to the [new management of devices](https://docs.haystack.deepset.ai/v2.0/docs/device-management).
- no need to change the backend.
:warning: Reminder
Once I release the new package, I should also update the integration page

Instructor embedders - new devices mgmt

---

integrations/cohere/src/haystack_integrations/components/generators/cohere/generator.py

Related to [#415](https://github.com/deepset-ai/haystack-core-integrations/issues/415)

chore: Update Cohere integration to use new generic callable (de)serializers for their callback handlers

---

integrations/weaviate/tests/test_auth.py

Auth tests are faling: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8041695637/job/21961293666
This happens because of https://github.com/deepset-ai/haystack/pull/6994, recently released in beta-8.

Weaviate: fix auth tests

---

integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/bm25_retriever.py
integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/embedding_retriever.py

The issue has been reported on Discord.
The fix is straightforward.

Weaviate: make retrievers return dicts

---

integrations/ollama/pydoc/config.yml

Fixes [#7196](https://github.com/deepset-ai/haystack/issues/7196)

Update API docs adding embedders

---

integrations/chroma/.gitignore
integrations/chroma/pyproject.toml
integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py
integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py
integrations/chroma/tests/test_document_store.py
integrations/chroma/tests/test_retriever.py

Also update the serialization strategy that was outdated.

fix: serialize the path to the local db

---

integrations/llama_cpp/src/haystack_integrations/components/generators/llama_cpp/generator.py

- fixes https://github.com/deepset-ai/haystack/issues/7140

llama.cpp - review docstrings

---

.github/workflows/chroma.yml
integrations/chroma/pyproject.toml
integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py

Chroma is available for Python 3.8, let's make this integration available too

release chroma on python 3.8

---

integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_document_embedder.py
integrations/fastembed/src/haystack_integrations/components/embedders/fastembed/fastembed_text_embedder.py

- fixes https://github.com/deepset-ai/haystack/issues/7134

docs:Review and normalize docstrings - `integrations.fastembed`

---

integrations/cohere/src/haystack_integrations/components/embedders/cohere/document_embedder.py
integrations/cohere/src/haystack_integrations/components/embedders/cohere/text_embedder.py

Fixes failing linter https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8104416322

cohere: fix linting

---

integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/bm25_retriever.py
integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/embedding_retriever.py
integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py

- fixes https://github.com/deepset-ai/haystack/issues/7133

docs: Docstring update 

---

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py
integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py

fixes https://github.com/deepset-ai/haystack/issues/7135

Google AI - review docstrings

---

integrations/mongodb_atlas/src/haystack_integrations/components/retrievers/mongodb_atlas/embedding_retriever.py
integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py
integrations/mongodb_atlas/tests/test_embedding_retrieval.py
integrations/mongodb_atlas/tests/test_retriever.py

- fixes https://github.com/deepset-ai/haystack/issues/7142
Note to reviewer:
Please be super careful and rerun the examples I added.

docs: Mongo atlas

---

integrations/mongodb_atlas/pydoc/config.yml
integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py

- fixes https://github.com/deepset-ai/haystack/issues/7195

docs: Final API docs touches

---

integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/bm25_retriever.py
integrations/elasticsearch/src/haystack_integrations/components/retrievers/elasticsearch/embedding_retriever.py
integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py

**Proposed Changes**
- fix https://github.com/deepset-ai/haystack/issues/7186

docs: review Elastic

---

integrations/anthropic/example/documentation_rag_with_claude.py

chore: Use the correct sonnet model name

---

integrations/jina/pydoc/config.yml

part of https://github.com/deepset-ai/haystack-integrations/issues/213

Jina - add missing ranker to API reference

---

integrations/chroma/pyproject.toml

Latest version of `databind-core` causes pip to get stuck into dependency resolution, not sure why but pinning to fix tests

Pin databind-core

---

.github/workflows/astra.yml

[Astra] Fix integration tests

---

.github/workflows/gradient.yml
integrations/gradient/src/haystack_integrations/components/embedders/gradient/gradient_text_embedder.py
integrations/gradient/tests/test_gradient_rag_pipelines.py

[gradient] Run integration tests in the CI

---

integrations/google_vertex/pyproject.toml

Fixes https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8460244428

Add pyarrow as required dependency

---

integrations/optimum/pyproject.toml

fix docs build

---

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/adapters.py
integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/adapters.py
integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/chat/chat_generator.py
integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py
integrations/amazon_bedrock/tests/test_chat_generator.py
integrations/amazon_bedrock/tests/test_generator.py

Adds Mistral models in the Amazon Bedrock integration within the haystack-core-integration ecosystem. This addition allows the use of Mistral models for generating responses and enables handling chat message for applications requiring conversational agents.
- **Introduced MistralAdapter**: A new adapter for handling requests and responses for Mistral models.
- **Introduced MistralChatAdapter**: Extends support for chat interfaces utilizing Mistral models, including handling of chat templates and generation parameters specific to Mistral.
- **Integration with Amazon Bedrock Chat Generator**: Registered MistralChatAdapter to enable its selection based on model patterns within the Amazon Bedrock Chat Generator mechanism.
- **Test Coverage**: Added comprehensive testing for both …

feat: Add Mistral Amazon Bedrock support 

---

integrations/pinecone/tests/conftest.py

increase sleep time to avoid frequent failures in tests

Pinecone - increase sleep time

---

integrations/ragas/pyproject.toml
integrations/ragas/src/haystack_integrations/components/evaluators/ragas/evaluator.py
integrations/ragas/src/haystack_integrations/components/evaluators/ragas/metrics.py

fixes #674
@shadeMe please take a look.
The tests are passing but you mentioned some changes were breaking our integration...

unpin ragas

---

integrations/cohere/src/haystack_integrations/components/embedders/cohere/document_embedder.py
integrations/cohere/src/haystack_integrations/components/embedders/cohere/text_embedder.py
integrations/cohere/src/haystack_integrations/components/embedders/cohere/utils.py
integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py
integrations/cohere/src/haystack_integrations/components/generators/cohere/generator.py
integrations/cohere/tests/test_cohere_chat_generator.py
integrations/cohere/tests/test_cohere_generators.py
integrations/cohere/tests/test_document_embedder.py
integrations/cohere/tests/test_text_embedder.py

https://github.com/deepset-ai/haystack-core-integrations/pull/702 was not complete and integration tests were failing.
I removed the mocked unit tests, they are not helpful and in this case hid the underlying problem.

Follow up: update Cohere integration to use Cohere SDK v5

---

.github/workflows/CI_readme_sync.yml

fix: add multi-line variable to step output in the right way

---

integrations/pgvector/examples/hybrid_retrieval.py

[deepset-ai/haystack-core-integrations#727]

---

integrations/astra/src/haystack_integrations/document_stores/astra/document_store.py
integrations/astra/tests/test_document_store.py

feat: defer the database connection to when it's needed

---

.github/workflows/amazon_bedrock.yml
.github/workflows/amazon_sagemaker.yml
.github/workflows/anthropic.yml
.github/workflows/astra.yml
.github/workflows/chroma.yml
.github/workflows/cohere.yml
.github/workflows/deepeval.yml
.github/workflows/elasticsearch.yml
.github/workflows/fastembed.yml
.github/workflows/google_ai.yml
.github/workflows/google_vertex.yml
.github/workflows/gradient.yml
.github/workflows/instructor_embedders.yml
.github/workflows/jina.yml
.github/workflows/langfuse.yml
.github/workflows/llama_cpp.yml
.github/workflows/mistral.yml
.github/workflows/mongodb_atlas.yml
.github/workflows/nvidia.yml
.github/workflows/ollama.yml
.github/workflows/opensearch.yml
.github/workflows/optimum.yml
.github/workflows/pgvector.yml
.github/workflows/pinecone.yml
.github/workflows/qdrant.yml
.github/workflows/ragas.yml
.github/workflows/unstructured.yml
.github/workflows/weaviate.yml

- consistency
Remove unneeded logic for the Datadog alerting

clean up workflow files

---

integrations/cohere/examples/cohere_embedding.py
integrations/cohere/examples/cohere_generation.py
integrations/cohere/examples/cohere_ranker.py
integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py
integrations/cohere/src/haystack_integrations/components/generators/cohere/generator.py
integrations/cohere/tests/test_cohere_chat_generator.py
integrations/cohere/tests/test_cohere_generator.py

- Update default model to `command-r`
- Add examples

feat: Update Cohere default LLMs, add examples and update unit tests

---

integrations/anthropic/example/documentation_rag_with_claude.py
integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py
integrations/anthropic/src/haystack_integrations/components/generators/anthropic/generator.py
integrations/anthropic/tests/test_chat_generator.py

- Update default chat model to the latest and cheaper `claude-3-5-sonnet-20240620`
- Update pydocs, unit tests and example

feat: Update Anthropic default models, pydocs

---

integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py
integrations/weaviate/tests/test_document_store.py

fix: fix connection to Weaviate Cloud Service

---

integrations/amazon_bedrock/pyproject.toml
integrations/amazon_sagemaker/pyproject.toml
integrations/amazon_sagemaker/tests/test_sagemaker.py
integrations/anthropic/pyproject.toml
integrations/chroma/pyproject.toml
integrations/cohere/pyproject.toml
integrations/deepeval/pyproject.toml
integrations/elasticsearch/pyproject.toml
integrations/fastembed/pyproject.toml
integrations/google_ai/pyproject.toml
integrations/google_vertex/pyproject.toml
integrations/gradient/pyproject.toml
integrations/instructor_embedders/pyproject.toml
integrations/jina/pyproject.toml
integrations/llama_cpp/pyproject.toml
integrations/mistral/pyproject.toml
integrations/mongodb_atlas/pyproject.toml
integrations/nvidia/pyproject.toml
integrations/ollama/pyproject.toml
integrations/opensearch/pyproject.toml
integrations/optimum/pyproject.toml
integrations/pgvector/pyproject.toml
integrations/pinecone/pyproject.toml
integrations/qdrant/pyproject.toml
integrations/ragas/pyproject.toml
integrations/unstructured/pyproject.toml
integrations/weaviate/pyproject.toml

- Updates ruff invocation across integration to include check parameter. 
- langfuse and astra were already including check parameter and were not updated here

chore: Update ruff invocation to include check parameter

---

.gitignore

- fixes #857 
Update the .gitignore file to exclude system and cache files 
On local repository 
NA

chore: Add system files in git ignore

---

integrations/langfuse/example/chat.py
integrations/langfuse/src/haystack_integrations/components/connectors/langfuse/langfuse_connector.py

- In `integrations/langfuse/example/chat.py` replace removed DynamicChatPromptBuilder with ChatPromptBuilder

chore: `Langfuse` - replace DynamicChatPromptBuilder with ChatPromptBuilder

---

integrations/langfuse/README.md
integrations/langfuse/tests/test_tracing.py

- Removes remaining DynamicChatPromptBuilder from docs and tests

chore: Remove all `DynamicChatPromptBuilder` references in Langfuse integration

---

.github/workflows/elasticsearch.yml
.github/workflows/opensearch.yml
.github/workflows/weaviate.yml

- failing workflows for Elasticsearch and Weaviate
- https://github.com/actions/runner-images/issues/9692
replace `docker-compose` with `docker compose`
CI

ci: update docker compose to v2

---

integrations/anthropic/example/documentation_rag_with_claude.py
integrations/llama_cpp/pyproject.toml
integrations/llama_cpp/tests/test_chat_generator.py
integrations/mistral/examples/streaming_chat_with_rag.py

- part of solving [#8086](https://github.com/deepset-ai/haystack/issues/8086)
Replace DynamicChatPromptBuilder with ChatPromptBuilder
Ran tests

fix: replace DynamicChatPromptBuilder with ChatPromptBuilder

---

integrations/opensearch/src/haystack_integrations/components/retrievers/opensearch/embedding_retriever.py

Docs: Update OpenSearchEmbeddingRetriever docstrings

---

integrations/langfuse/README.md

- fixes https://github.com/deepset-ai/haystack/issues/8126

chore: Update Langfuse README to avoid common initialization issues

---

integrations/nvidia/src/haystack_integrations/components/generators/nvidia/generator.py

Docs: Update NvidiaGenerator docstrings

---

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py

Docs: Update GeminiGenerator docstrings

---

integrations/mistral/examples/indexing_pipeline.py
integrations/mistral/examples/streaming_chat_with_rag.py
integrations/mistral/pyproject.toml

Fix ruff 0.6 upgrade breakages.
CI

fix: Lints in `mistral-haystack`

---

integrations/cohere/examples/cohere_embedding.py
integrations/cohere/examples/cohere_generation.py
integrations/cohere/examples/cohere_ranker.py
integrations/cohere/pyproject.toml
integrations/cohere/src/haystack_integrations/components/embedders/cohere/document_embedder.py
integrations/cohere/src/haystack_integrations/components/embedders/cohere/text_embedder.py

fix: Lints in `cohere-haystack`

---

integrations/unstructured/pyproject.toml

Fix breakages from ruff upgrade.
CI

fix: Lints in `unstructured-haystack`

---

integrations/nvidia/pydoc/config.yml

Add missing modules to the PyDoc config.

docs: Update Nvidia API docs

---

integrations/unstructured/src/haystack_integrations/components/converters/unstructured/converter.py

docs: update links to Unstructured docs

---

integrations/jina/src/haystack_integrations/components/embedders/jina/document_embedder.py
integrations/jina/src/haystack_integrations/components/embedders/jina/text_embedder.py

docs: update docstrings of JinaDocumentEmbedder and JinaTextEmbedder

---

.github/workflows/snowflake.yml
integrations/snowflake/pydoc/config.yml

- adding missing github workflow for `Snowflake`

ci: adding github workflow for Snowflake

---

.github/workflows/chroma.yml
integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py
integrations/chroma/tests/test_document_store.py
integrations/chroma/tests/test_retriever.py
integrations/langfuse/tests/test_tracing.py

- fixes #1071
A remote http client is added
Manual test

feat: Chroma - allow remote HTTP connection

---

integrations/snowflake/pydoc/config.yml

The Snowflake integration is now showing up in API reference, so attempting to push it again with a few fixes.

docs: upd snowflake pydoc

---

integrations/google_ai/src/haystack_integrations/components/generators/google_ai/gemini.py
integrations/google_ai/tests/generators/test_gemini.py

- fixes #974
- remove support for tools
- change output type to `List[str]`
CI
This is a breaking change and I will release a major version.

fix: `GoogleAIGeminiGenerator` - remove support for tools and change output type

---

integrations/nvidia/src/haystack_integrations/components/rankers/nvidia/ranker.py

n/a
add a new model
ran existing tests w/ default model changed to this new model
n/a

feat: add nvidia/llama-3.2-nv-rerankqa-1b-v1 to set of known ranking models

---

integrations/azure_ai_search/README.md

Remove the link to incorrect tutorial in Readme file.

fix: Fix error in README file

---

integrations/ollama/CHANGELOG.md

Add the missing update to the changelog
(it was not generated because of some issues in the release process)

chore: update changelog for `ollama-haystack==2.0.0`

---

.github/labeler.yml

Add Azure AI Search to the labeler configuration: this workflow tags PRs related related to a specific integration
I also created the appropriate label

chore: add Azure AI Search to labeler.yml

---

integrations/anthropic/pydoc/config.yml

docs: add AnthropicVertexChatGenerator to pydoc

---

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py

- the internal function `_convert_message_to_openai_format` was made public and transformed into a class method in https://github.com/deepset-ai/haystack/pull/8666
- failing nightly tests with Haystack main: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12575687072/job/35050943162
- add a (not so nice) check to use the appropriate function: we can get rid of it after 2.9.0 release (I'll create an issue to track that).
CI; local tests with Haystack main
- I added …

fix: Langfuse - fix messages conversion to OpenAI format

---

.github/workflows/ollama.yml
integrations/ollama/pyproject.toml
integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py
integrations/ollama/tests/test_chat_generator.py
integrations/ollama/tests/test_generator.py

- fixes #1257
- add support for tools in `OllamaChatGenerator` (implementation coming from `haystack-experimental`)
CI, new tests
- the change is non-breaking
- this implementation was previously reviewed in https://github.com/deepset-ai/haystack-experimental/pull/106 …

feat: Ollama - add support for tools

---

integrations/opensearch/CHANGELOG.md

Manually fix the changelog, which was messed up in https://github.com/deepset-ai/haystack-core-integrations/commit/203182b22a04e295c1a413a728d93fe7dd777cce

chore: OpenSearch - manually fix changelog

---

integrations/langfuse/src/haystack_integrations/components/connectors/langfuse/langfuse_connector.py
integrations/langfuse/tests/test_tracing.py

Enhances the `LangfuseConnector` by introducing secure handling of API keys through environment variables, improving security and flexibility in configuration.
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1235
- Added `public_key` and `secret_key` parameters to the LangfuseConnector's constructor, utilizing environment variables for secure access.
- Introduced `to_dict` and `from_dict` methods for serialization and deserialization of the connector, facilitating easier configuration management.
- Updated test cases to ensure robust integration with the new key management system.
- These changes are backwards compatible
The `LangfuseConnector` can now be initialized with secure keys retrieved from environment variables, enhancing security in production …

feat: Add LangfuseConnector secure key management and serialization 

---

integrations/google_ai/pyproject.toml
integrations/google_ai/src/haystack_integrations/components/generators/google_ai/chat/gemini.py
integrations/google_ai/tests/generators/chat/test_chat_gemini.py

- part of https://github.com/deepset-ai/haystack/issues/8735
- add support for `Tool`: it is a breaking change because Google `tools` were somehow supported before
- general refactoring to improve this Chat Generator: for example, I found that system message was not handled properly
CI, several new tests
I decided not to use the new [Google Gen AI SDKs](https://googleapis.github.io/python-genai/):
> This is an early release. API is subject to change. Please do not use this SDK in production environments at this stage.
- I have updated the related issue …

feat!: Google AI - support for Tool + general refactoring

---

integrations/google_vertex/pyproject.toml
integrations/google_vertex/src/haystack_integrations/components/generators/google_vertex/chat/gemini.py
integrations/google_vertex/tests/chat/test_gemini.py

- part of https://github.com/deepset-ai/haystack/issues/8734
- add support for `Tool`: it is a breaking change because Vertex `Tools` were somehow supported before
- general refactoring to improve this Chat Generator (and make it more aligned with others)
- CI
- several new tests
- since there is no an easy way to perform integration tests on the CI, I extensively tested the new implementation locally with a GCP account
- I've used one of …

feat!: Google Vertex - support for Tool + general refactoring

---

integrations/optimum/pyproject.toml
integrations/optimum/tests/test_optimum_text_embedder.py

- nightly tests failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13103842692
- pin `transformers` (https://github.com/huggingface/transformers/issues/35639)
- avoid that a unit test contacts to the HF Hub
CI …

fix: Optimum - pin transformers and fix test

---

integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py
integrations/chroma/tests/test_document_store.py

- related to #1371
- better handle discarded fields (`blob` and `dataframe`)
CI; new tests

chore: Chroma - better handle discarded fields

---

integrations/astra/src/haystack_integrations/document_stores/astra/document_store.py
integrations/astra/src/haystack_integrations/document_stores/astra/filters.py
integrations/astra/tests/test_document_store.py

- remove dataframe support from Astra
CI

chore!: Astra - remove dataframe support

---

.github/ISSUE_TEMPLATE/new-integration-proposal.md

docs: updating template for new integration

---

integrations/qdrant/src/haystack_integrations/document_stores/qdrant/converters.py
integrations/qdrant/tests/test_converters.py
integrations/qdrant/tests/test_filters.py

- Remove dataframe support from Qdrant
CI; added specific tests

chore!: Qdrant - remove dataframe support

---

integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py

Added a one-sentence description to the document store. This is needed for deepset Pipeline Builder - it shows as a tooltip. 

Docs: Add docstore description

---

integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py
integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/document_store.py
integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py
integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py

Updated the descriptions so that they fit deepset Pipeline Builder where they're showed as a tooltip (only the first line).

Docs: Update document store descriptions for deepset Pipeline Builder

---

integrations/anthropic/src/haystack_integrations/components/generators/anthropic/chat/chat_generator.py
integrations/anthropic/src/haystack_integrations/components/generators/anthropic/generator.py

- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1454 by implementing a workaround for https://github.com/DataDog/dd-trace-py/issues/12562 in `AnthropicGenerator` and `AnthropicChatGenerator`
- decide response processing based on stream param
- adds `streaming_callback` run param to `AnthropicGenerator`
- tested against Anthropic API with `ddtrace.patch_all()` previous to `run()`
- I've used one of the [conventional …

fix: workaround for Anthropic streaming with ddtrace (#1454)

---

integrations/pgvector/pyproject.toml
integrations/pgvector/src/haystack_integrations/document_stores/pgvector/document_store.py

- remove dataframe checks (no tests affected)
CI

chore: pgvector - pin haystack and remove dataframe checks

---

integrations/weights_bias/README.md

docs: updating README.MD - project archived and moved

---

integrations/mcp/README.md

- Related to https://github.com/deepset-ai/haystack/issues/9137
- Update import

docs: fix MCPTool import in code example

---

cliff.toml

- related to #1588 - missing `endif`
- fix the incorrect Tera template

fix: fix error in changelog generation

---

integrations/chroma/pyproject.toml

- fixes failing [nightly tests ](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/14255046308/job/39956061441)
Chroma just released 1.0.0 last night from their previous version of 0.6.3. Pinning chroma to less than 1 for now until we can figure out how to fix the issues caused by the new release. …

fix: Pin chroma

---

integrations/chroma/pyproject.toml
integrations/chroma/src/haystack_integrations/components/retrievers/chroma/__init__.py
integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py
integrations/chroma/src/haystack_integrations/document_stores/chroma/__init__.py
integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py
integrations/chroma/src/haystack_integrations/document_stores/chroma/errors.py
integrations/chroma/src/haystack_integrations/document_stores/chroma/filters.py
integrations/chroma/src/haystack_integrations/document_stores/chroma/utils.py
integrations/chroma/tests/__init__.py
integrations/chroma/tests/test_document_store.py
integrations/chroma/tests/test_retriever.py

- fixes #1609 
Chroma updated what is returned when calling list_collections() making an if statement fail. Updated the code to accommodate this.
Existing tests.

fix: Update test and unpin chroma

---

integrations/google_ai/tests/generators/chat/test_chat_gemini.py
integrations/google_ai/tests/generators/test_gemini.py

Update tests for GoogleAIGenerator to actually test content returned by the LLM.
Updated tests

ci: Update to `GoogleAIGeminiGenerator` tests

---

integrations/unstructured/src/haystack_integrations/components/converters/unstructured/converter.py

Adding more information to the usage example snippet to help users understand how to run the converter when self-hosting.

docs: update Unstructured example

---

integrations/mongodb_atlas/pydoc/config.yml

Adding MongoDBAtlasFullTextRetriever to API Reference

docs: add MongoDBAtlasFullTextRetriever to API Reference

---

README.md

I've noticed that sometimes we tend to forgot to review the Changelog PR
- include a simple section about this aspect in the README
- refine the warning about the commit to tag: it's not always possible to tag the exact commit and this does not always lead to errors …

chore: review release guide

---

integrations/ollama/pyproject.toml
integrations/ollama/src/haystack_integrations/components/generators/ollama/chat/chat_generator.py

chore: remove import fallback for `deserialize_tools_or_toolset_inplace`

---

.github/ISSUE_TEMPLATE/breaking-change-proposal.md
.github/ISSUE_TEMPLATE/new-integration-proposal.md

The Tasks checklist in `new integration `issue template is currently displayed as a code block. Updated it to render as an interactive checklist instead.

fix: fix error in Tasks checklist

---

integrations/amazon_bedrock/examples/bedrock_ranker_example.py

- Follow up PR for https://github.com/deepset-ai/haystack-core-integrations/pull/1732
- With AmazonBedrockRanker as our recommended component instead of BedrockRanker, this PR updates the example code

chore: Update bedrock_ranker_example.py

---

integrations/azure_ai_search/src/haystack_integrations/document_stores/azure_ai_search/document_store.py

As requested by the Azure AI team, I’ve added a user agent policy to the client requests so they can track how our integration is being used.

feat: Add user-agent to `AzureAISearchDocumentStore`

---

integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py

- Added `OllamaGenerator` in `_SUPPORTED_GENERATORS` list in langfuse integration.
- Ran all pre-existing tests.
- Ran Ollama locally and to confirmed responses.
Seperated from #1753 for smoother release process and separate change logs.

feat: `OllamaGenerator` support in Langfuse

---

.github/workflows/langfuse.yml
integrations/langfuse/pyproject.toml
integrations/langfuse/tests/test_tracer.py

- fixes #1798
- pin the appropriate package version
- add CI job
CI

build: add Langfuse pins

---

.github/workflows/snowflake.yml
integrations/snowflake/pyproject.toml
integrations/snowflake/src/haystack_integrations/components/retrievers/snowflake/snowflake_table_retriever.py

- fixes #1808
- remove some direct dependencies that can be better installed via `polars`
- remove a lazy import block: `polars` is a mandatory dependency, so there is no need for a lazy import mechanism
- add CI job
CI
Not breaking -> bugfix version …

buid: add pins for Snowflake + small refactoring

---

integrations/chroma/pyproject.toml
integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py
integrations/chroma/src/haystack_integrations/document_stores/chroma/document_store.py
integrations/chroma/src/haystack_integrations/document_stores/chroma/utils.py

- related to  #1771
- (fixing the typing for Chroma started in #1697)
- in this PR, I'm fixing a previously undetected type error
- I'm also adding [py.typed files where needed](https://peps.python.org/pep-0561/#packaging-type-information), so that the types of this integration can be used by downstream projects (similar to https://github.com/deepset-ai/haystack/pull/9329). Since Haystack core integrations rely on namespace packages, each submodule needs a separate py.typed file.
CI; local tests:
- installing the current version of the integration, each of its types is treated as Any
- installing the version on this branch, types are correctly exposed
Something might not work as intended, but I would say that this change is low-risk and, once a new version is released, we could verify and …

feat: Chroma - fix typing + ship types by adding py.typed files

---

.github/workflows/qdrant.yml
integrations/qdrant/pyproject.toml
integrations/qdrant/src/haystack_integrations/components/retrievers/qdrant/retriever.py
integrations/qdrant/src/haystack_integrations/document_stores/qdrant/converters.py
integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py
integrations/qdrant/src/haystack_integrations/document_stores/qdrant/filters.py
integrations/qdrant/src/haystack_integrations/document_stores/qdrant/migrate_to_sparse.py

(this means testing with all dependencies installed, differently from `hatch run lint:typing` that did not install dependencies)
- fix the type errors by refactoring the Document Store a bit
CI …

fix: fix Qdrant types + add py.typed

---

integrations/mcp/README.md

chore: Update mcp-haystack integration README.md

---

.github/workflows/weaviate.yml
integrations/weaviate/pyproject.toml
integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/bm25_retriever.py
integrations/weaviate/src/haystack_integrations/components/retrievers/weaviate/embedding_retriever.py
integrations/weaviate/src/haystack_integrations/document_stores/weaviate/auth.py
integrations/weaviate/src/haystack_integrations/document_stores/weaviate/document_store.py

- use `hatch run test:types` in the test workflow and fix errors
- introduce stricter configuration in pyproject.toml and fix errors
CI …

fix: Weaviate - fix types + add py.typed

---

.github/workflows/mistral.yml
integrations/mistral/pyproject.toml
integrations/mistral/tests/test_mistral_document_embedder.py
integrations/mistral/tests/test_mistral_text_embedder.py

(this means testing with all dependencies installed, differently from `hatch run lint:typing` that did not install dependencies) -> no type errors in this integration, already OK
- introduce stricter configuration in pyproject.toml -> no type errors in this integration, already OK
CI
- I added unit …

chore: mistral - improve type checking + add py.typed

---

.github/workflows/google_genai.yml
integrations/google_genai/pyproject.toml
integrations/google_genai/src/haystack_integrations/components/generators/google_genai/chat/chat_generator.py
integrations/google_genai/src/haystack_integrations/components/generators/google_genai/chat/utils.py

fix: fix Google GenAI types + add py.typed

---

integrations/deepeval/pyproject.toml
integrations/deepeval/src/haystack_integrations/components/evaluators/deepeval/evaluator.py
integrations/deepeval/src/haystack_integrations/components/evaluators/deepeval/metrics.py
integrations/deepeval/tests/test_evaluator.py

- Unpin `deepeval` and update integration to work with the latest version of `deepeval`
- Updated unit tests

feat: Update deepeval integration to be unpinned

---

integrations/watsonx/README.md

fix: Fix watsonx-haystack Readme badges

---

integrations/cohere/pyproject.toml
integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py

- fixes #2082
- use the new classes from version 5.16.0
- update the pin (these classes were not available in previous versions)
CI

fix: update Cohere to client 5.16.0

---

.github/labeler.yml

fix: update labeler to include llama-stack

---

integrations/meta_llama/tests/test_llama_chat_generator.py

fix: Fix meta-llama integration test

---

integrations/cohere/src/haystack_integrations/components/generators/cohere/chat/chat_generator.py

Failing nightly tests: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/16737291017/job/47378640778
This happens because the Cohere API slightly changed, as it happened recently (#2082).
- separate `finish_reason` and usage handling
- for usage, try to support both the dictionary and object formats (the Cohere API has been switching between these two formats several times)
CI …

chore: `CohereChatGenerator` - make `finish_reason` and usage handling more robust

---

integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py
integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py

- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/2148
Needed to properly track LLM usage in Langfuse 
Tested manually

feat: Add AmazonBedrockChatGenerator to supported chat generators in Langfuse

---

integrations/weaviate/docker-compose.yml

fix: Update version of weaviate in docker-compose file

---

.github/labeler.yml

- partially addresses https://github.com/deepset-ai/haystack-core-integrations/issues/2349
- Updates labeler to tag PRs that make changes to the `aimlapi-haystack` integration

chore: Update labeler for `aimlapi` integration
